In [80]:

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

from scipy import stats
from scipy.stats import norm, skew

In [81]:
train_path = '../../../data/raw/train.csv'
test_path = '../../../data/raw/test.csv'

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [82]:
train_ID = train['Id']
test_ID = test['Id']

#Now drop the  'Id' colum since it's unnecessary for  the prediction process.
train.drop("Id", axis = 1, inplace = True)
test.drop("Id", axis = 1, inplace = True)

In [83]:
# train = train.drop(train[(train['GrLivArea'] > 4000) & (train['SalePrice'] < 300000)].index)
# train=train.drop(train[(train["LotArea"] >100000)].index)
# train=train.drop(train[(train['LotFrontage']>300)].index)
train["SalePrice"] = np.log1p(train["SalePrice"])

In [84]:
# train = train.drop(['Heating','RoofMatl','Condition2','Street','Utilities'],axis=1)
# test = test.drop(['Heating','RoofMatl','Condition2','Street','Utilities'],axis=1)

In [85]:
ntrain = train.shape[0]
ntest = test.shape[0]
y_train = train.SalePrice.values
all_data = pd.concat((train, test)).reset_index(drop=True)
all_data.drop(['SalePrice'], axis=1, inplace=True)
print("all_data size is : {}".format(all_data.shape))

all_data size is : (2919, 79)

In [86]:
all_data["FireplaceQu"] = all_data["FireplaceQu"].fillna("None")
all_data['PoolQC']=all_data['PoolQC'].fillna('None')
all_data["MiscFeature"] = all_data["MiscFeature"].fillna("None")
all_data["Alley"] = all_data["Alley"].fillna("None")
all_data["MasVnrType"] = all_data["MasVnrType"].fillna("None")
all_data["Fence"] = all_data["Fence"].fillna("None")
all_data["LotFrontage"] = all_data.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median()))
all_data['GarageYrBlt'] = all_data['GarageYrBlt'].fillna(all_data['YrSold']-35)

for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    all_data[col] = all_data[col].fillna('None')
for col in ( 'GarageArea', 'GarageCars'):
    all_data[col] = all_data[col].fillna(0)
for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF','TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath'):
    all_data[col] = all_data[col].fillna(0)
for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):
    all_data[col] = all_data[col].fillna('None')
all_data["MasVnrArea"] = all_data["MasVnrArea"].fillna(0)
all_data['MSZoning'] = all_data.groupby('MSSubClass')['MSZoning'].transform(lambda x: x.fillna(x.mode()[0]))
all_data["Functional"] = all_data["Functional"].fillna("Typ")
all_data['Electrical'] = all_data['Electrical'].fillna("SBrkr")
all_data['KitchenQual'] = all_data['KitchenQual'].fillna("TA")
all_data['Exterior1st'] = all_data['Exterior1st'].fillna(all_data['Exterior1st'].mode()[0])
all_data['Exterior2nd'] = all_data['Exterior2nd'].fillna(all_data['Exterior2nd'].mode()[0])
all_data['SaleType'] = all_data['SaleType'].fillna(all_data['SaleType'].mode()[0])
all_data['MSSubClass'] = all_data['MSSubClass'].fillna("None")

In [87]:
#Check remaining missing values if any 
all_data_na = (all_data.isnull().sum() / len(all_data)) * 100
all_data_na = all_data_na.drop(all_data_na[all_data_na == 0].index).sort_values(ascending=False)
missing_data = pd.DataFrame({'Missing Ratio' :all_data_na})
missing_data.head()

           Missing Ratio
Utilities       0.068517

In [88]:
# all_data['TotalSF'] = all_data['TotalBsmtSF'] + all_data['1stFlrSF'] + all_data['2ndFlrSF']
# all_data["HouseAge"] = all_data["YrSold"] - all_data["YearBuilt"]
# all_data["QualCond"] = all_data["OverallQual"]*all_data["OverallCond"]
# all_data['TotalBsmtBath'] = all_data['BsmtFullBath'] + all_data['BsmtFullBath']*0.5
# all_data['TotalBath'] = all_data['FullBath'] + all_data['HalfBath']*0.5

In [89]:
all_data['YrBltAndRemod']=all_data['YearBuilt']+all_data['YearRemodAdd']
all_data['TotalSF']=all_data['TotalBsmtSF'] + all_data['1stFlrSF'] + all_data['2ndFlrSF']

all_data['Total_sqr_footage'] = (all_data['BsmtFinSF1'] + all_data['BsmtFinSF2'] +
                                 all_data['1stFlrSF'] + all_data['2ndFlrSF'])

all_data['Total_Bathrooms'] = (all_data['FullBath'] + (0.5 * all_data['HalfBath']) +
                               all_data['BsmtFullBath'] + (0.5 * all_data['BsmtHalfBath']))

all_data['Total_porch_sf'] = (all_data['OpenPorchSF'] + all_data['3SsnPorch'] +
                              all_data['EnclosedPorch'] + all_data['ScreenPorch'] +
                              all_data['WoodDeckSF'])

all_data['haspool'] = all_data['PoolArea'].apply(lambda x: 1 if x > 0 else 0)
all_data['has2ndfloor'] = all_data['2ndFlrSF'].apply(lambda x: 1 if x > 0 else 0)
all_data['hasgarage'] = all_data['GarageArea'].apply(lambda x: 1 if x > 0 else 0)
all_data['hasbsmt'] = all_data['TotalBsmtSF'].apply(lambda x: 1 if x > 0 else 0)
all_data['hasfireplace'] = all_data['Fireplaces'].apply(lambda x: 1 if x > 0 else 0)

In [90]:
all_data = all_data.drop(['Utilities', 'Street', 'PoolQC',], axis=1)

In [91]:
#MSSubClass=The building class
all_data['MSSubClass'] = all_data['MSSubClass'].apply(str)


#Changing OverallCond into a categorical variable
all_data['OverallCond'] = all_data['OverallCond'].astype(str)


#Year and month sold are transformed into categorical features.
all_data['YrSold'] = all_data['YrSold'].astype(str)
all_data['MoSold'] = all_data['MoSold'].astype(str)

In [92]:
from sklearn.preprocessing import LabelEncoder
cols = ('FireplaceQu', 'BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond', 
        'ExterQual', 'ExterCond','HeatingQC', 'KitchenQual', 'BsmtFinType1', 
        'BsmtFinType2', 'Functional',  'BsmtExposure', 'GarageFinish', 'LandSlope',
        'LotShape', 'PavedDrive',  'CentralAir', 'MSSubClass', 'OverallCond', 
        'YrSold', 'MoSold')
# process columns, apply LabelEncoder to categorical features
for c in cols:
    lbl = LabelEncoder() 
    lbl.fit(list(all_data[c].values)) 
    all_data[c] = lbl.transform(list(all_data[c].values))

# shape        
print('Shape all_data: {}'.format(all_data.shape))

Shape all_data: (2919, 86)

In [93]:
numeric_feats = all_data.dtypes[all_data.dtypes != "object"].index

# Check the skew of all numerical features
skewed_feats = all_data[numeric_feats].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
print("\nSkew in numerical features: \n")
skewness = pd.DataFrame({'Skew' :skewed_feats})
skewness.head(10)

Skew in numerical features:

                    Skew
MiscVal        21.947195
PoolArea       16.898328
haspool        14.884318
LotArea        12.822431
LowQualFinSF   12.088761
3SsnPorch      11.376065
LandSlope       4.975157
KitchenAbvGr    4.302254
BsmtFinSF2      4.146143
EnclosedPorch   4.003891

In [94]:
skewness = skewness[abs(skewness) > 0.5]
print("There are {} skewed numerical features to Box Cox transform".format(skewness.shape[0]))

from scipy.special import boxcox1p
skewed_features = skewness.index
lam = 0.15
for feat in skewed_features:
    #all_data[feat] += 1
    all_data[feat] = boxcox1p(all_data[feat], lam)
    
#all_data[skewed_features] = np.log1p(all_data[skewed_features])

There are 64 skewed numerical features to Box Cox transform

In [95]:
all_data = pd.get_dummies(all_data)
print(all_data.shape)

(2919, 234)

In [96]:
train = all_data[:ntrain]
test = all_data[ntrain:]

In [97]:
outliers = [30, 88, 462, 631, 1322]
train = train.drop(outliers, errors='ignore').reset_index(drop=True)
y_train = np.delete(y_train, [i for i in outliers if i < len(y_train)])

In [98]:
overfit = []
for i in train.columns:
    counts = train[i].value_counts()
    zeros = counts.iloc[0]
    if zeros / len(train) * 100 > 99.94:
        overfit.append(i)

overfit = list(overfit)
overfit.append('MSZoning_C (all)')

train = train.drop(overfit, axis=1).copy()
test = test.drop(overfit, axis=1).copy()

In [99]:
import pandas as pd
# Giả sử df là DataFrame của bạn

# Kiểm tra tổng số NaN cho mỗi cột
nan_counts = train.isnull().sum()

# Lọc và chỉ hiển thị các cột có NaN > 0
columns_with_nan = nan_counts[nan_counts > 0].sort_values(ascending=False)

print("Tổng số giá trị NaN trên mỗi cột:")
print(columns_with_nan)

Tổng số giá trị NaN trên mỗi cột:
Series([], dtype: int64)

In [100]:
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb
import catboost as cb

In [102]:
n_folds = 5

def rmsle_cv(model):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(train.values)
    rmse= np.sqrt(-cross_val_score(model, train.values, y_train, scoring="neg_mean_squared_error", cv = kf))
    return(rmse)

In [103]:
from sklearn.linear_model import ElasticNetCV, LassoCV, RidgeCV

alphas_alt = [14.5, 14.6, 14.7, 14.8, 14.9, 15, 15.1, 15.2, 15.3, 15.4, 15.5]
alphas2 = [5e-05, 0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008]
e_alphas = [0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007]
e_l1ratio = [0.8, 0.85, 0.9, 0.95, 0.99, 1]
lasso = make_pipeline(RobustScaler(),
                      LassoCV(max_iter=10000000, alphas=alphas2,
                              random_state=42))
ridge = make_pipeline(RobustScaler(),
                      RidgeCV(alphas=alphas_alt))

ENet = make_pipeline(RobustScaler(),
                           ElasticNetCV(max_iter=10000000, alphas=e_alphas,
                                         random_state=42, l1_ratio=e_l1ratio))
KRR = KernelRidge(alpha=0.6, kernel='polynomial', degree=2, coef0=2.5)
GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
model_xgb = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)
model_lgb = lgb.LGBMRegressor(objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=720,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)
model_cat = cb.CatBoostRegressor(iterations=2000, learning_rate=0.05, depth=4,
                                 eval_metric='RMSE', random_seed =42, bagging_temperature = 0.2,
                                 od_type='Iter', metric_period = 75, od_wait=100)

In [104]:
score = rmsle_cv(lasso)
print("\nLasso score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Lasso score: 0.1228 (0.0180)

In [105]:
score = rmsle_cv(ENet)
print("\nEnet score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Enet score: 0.1229 (0.0180)

In [106]:
score = rmsle_cv(ridge)
print("\nRidge score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Ridge score: 0.1245 (0.0179)

In [107]:

score = rmsle_cv(KRR)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

KRR score: 0.1233 (0.0152)

In [108]:

score = rmsle_cv(GBoost)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

KRR score: 0.1196 (0.0132)

In [109]:
score = rmsle_cv(model_xgb)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [12:28:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [12:28:34] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [12:28:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [12:28:37] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [12:28:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

KRR score: 0.1209 (0.0091)

In [110]:
score = rmsle_cv(model_lgb)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002240 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1634
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 188
[LightGBM] [Info] Start training from score 12.022143

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001447 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1640
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 187
[LightGBM] [Info] Start training from score 12.024769

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002038 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1635
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 188
[LightGBM] [Info] Start training from score 12.023267

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003295 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1644
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 187
[LightGBM] [Info] Start training from score 12.035129

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001490 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1636
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 187
[LightGBM] [Info] Start training from score 12.024343
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

KRR score: 0.1186 (0.0111)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [111]:
score = rmsle_cv(model_cat)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

0:	learn: 0.3900131	total: 5.55ms	remaining: 11.1s
75:	learn: 0.1326741	total: 217ms	remaining: 5.5s
150:	learn: 0.1070496	total: 394ms	remaining: 4.82s
225:	learn: 0.0948810	total: 567ms	remaining: 4.45s
300:	learn: 0.0865520	total: 747ms	remaining: 4.22s
375:	learn: 0.0800224	total: 949ms	remaining: 4.1s
450:	learn: 0.0745109	total: 1.21s	remaining: 4.14s
525:	learn: 0.0692919	total: 1.38s	remaining: 3.88s
600:	learn: 0.0649656	total: 1.57s	remaining: 3.65s
675:	learn: 0.0612343	total: 1.74s	remaining: 3.4s
750:	learn: 0.0579884	total: 1.98s	remaining: 3.29s
825:	learn: 0.0547065	total: 2.16s	remaining: 3.07s
900:	learn: 0.0520757	total: 2.33s	remaining: 2.84s
975:	learn: 0.0495665	total: 2.48s	remaining: 2.6s
1050:	learn: 0.0471433	total: 2.64s	remaining: 2.39s
1125:	learn: 0.0447865	total: 2.85s	remaining: 2.21s
1200:	learn: 0.0425607	total: 3.07s	remaining: 2.04s
1275:	learn: 0.0406564	total: 3.29s	remaining: 1.87s
1350:	learn: 0.0388262	total: 3.48s	remaining: 1.67s
1425:	learn: 0.0371089	total: 3.67s	remaining: 1.48s
1500:	learn: 0.0354527	total: 3.83s	remaining: 1.27s
1575:	learn: 0.0341585	total: 3.99s	remaining: 1.07s
1650:	learn: 0.0328071	total: 4.14s	remaining: 876ms
1725:	learn: 0.0314254	total: 4.3s	remaining: 683ms
1800:	learn: 0.0301400	total: 4.47s	remaining: 494ms
1875:	learn: 0.0288917	total: 4.64s	remaining: 306ms
1950:	learn: 0.0276633	total: 4.79s	remaining: 120ms
1999:	learn: 0.0270032	total: 4.9s	remaining: 0us
0:	learn: 0.3789812	total: 2.44ms	remaining: 4.87s
75:	learn: 0.1279609	total: 175ms	remaining: 4.43s
150:	learn: 0.1046739	total: 326ms	remaining: 3.99s
225:	learn: 0.0936471	total: 495ms	remaining: 3.88s
300:	learn: 0.0859479	total: 669ms	remaining: 3.78s
375:	learn: 0.0796236	total: 841ms	remaining: 3.63s
450:	learn: 0.0750874	total: 996ms	remaining: 3.42s
525:	learn: 0.0700077	total: 1.17s	remaining: 3.28s
600:	learn: 0.0656152	total: 1.36s	remaining: 3.18s
675:	learn: 0.0620428	total: 1.58s	remaining: 3.1s
750:	learn: 0.0582520	total: 1.75s	remaining: 2.92s
825:	learn: 0.0552318	total: 1.94s	remaining: 2.75s
900:	learn: 0.0521909	total: 2.22s	remaining: 2.71s
975:	learn: 0.0492164	total: 2.39s	remaining: 2.51s
1050:	learn: 0.0466926	total: 2.56s	remaining: 2.31s
1125:	learn: 0.0443239	total: 2.72s	remaining: 2.11s
1200:	learn: 0.0420815	total: 2.87s	remaining: 1.91s
1275:	learn: 0.0398920	total: 3.02s	remaining: 1.71s
1350:	learn: 0.0378448	total: 3.18s	remaining: 1.53s
1425:	learn: 0.0359654	total: 3.33s	remaining: 1.34s
1500:	learn: 0.0341647	total: 3.51s	remaining: 1.17s
1575:	learn: 0.0326372	total: 3.67s	remaining: 988ms
1650:	learn: 0.0311660	total: 3.83s	remaining: 810ms
1725:	learn: 0.0298591	total: 3.98s	remaining: 632ms
1800:	learn: 0.0284771	total: 4.13s	remaining: 456ms
1875:	learn: 0.0272864	total: 4.28s	remaining: 283ms
1950:	learn: 0.0261483	total: 4.44s	remaining: 112ms
1999:	learn: 0.0254206	total: 4.54s	remaining: 0us
0:	learn: 0.3819148	total: 2.46ms	remaining: 4.92s
75:	learn: 0.1279853	total: 171ms	remaining: 4.33s
150:	learn: 0.1013252	total: 318ms	remaining: 3.9s
225:	learn: 0.0892077	total: 469ms	remaining: 3.68s
300:	learn: 0.0815619	total: 616ms	remaining: 3.48s
375:	learn: 0.0754015	total: 773ms	remaining: 3.34s
450:	learn: 0.0702009	total: 932ms	remaining: 3.2s
525:	learn: 0.0661209	total: 1.08s	remaining: 3.04s
600:	learn: 0.0618950	total: 1.25s	remaining: 2.91s
675:	learn: 0.0582641	total: 1.4s	remaining: 2.73s
750:	learn: 0.0549919	total: 1.54s	remaining: 2.56s
825:	learn: 0.0520682	total: 1.71s	remaining: 2.42s
900:	learn: 0.0490955	total: 1.85s	remaining: 2.26s
975:	learn: 0.0464305	total: 2s	remaining: 2.1s
1050:	learn: 0.0439045	total: 2.15s	remaining: 1.94s
1125:	learn: 0.0416881	total: 2.32s	remaining: 1.8s
1200:	learn: 0.0398478	total: 2.47s	remaining: 1.64s
1275:	learn: 0.0380367	total: 2.62s	remaining: 1.48s
1350:	learn: 0.0364769	total: 2.76s	remaining: 1.33s
1425:	learn: 0.0348599	total: 2.9s	remaining: 1.17s
1500:	learn: 0.0334816	total: 3.07s	remaining: 1.02s
1575:	learn: 0.0321528	total: 3.22s	remaining: 867ms
1650:	learn: 0.0308892	total: 3.37s	remaining: 712ms
1725:	learn: 0.0295526	total: 3.51s	remaining: 558ms
1800:	learn: 0.0283560	total: 3.66s	remaining: 404ms
1875:	learn: 0.0273646	total: 3.81s	remaining: 252ms
1950:	learn: 0.0265310	total: 3.97s	remaining: 99.6ms
1999:	learn: 0.0259302	total: 4.07s	remaining: 0us
0:	learn: 0.3875419	total: 2.45ms	remaining: 4.91s
75:	learn: 0.1310808	total: 169ms	remaining: 4.29s
150:	learn: 0.1065297	total: 320ms	remaining: 3.91s
225:	learn: 0.0944377	total: 469ms	remaining: 3.68s
300:	learn: 0.0863079	total: 622ms	remaining: 3.51s
375:	learn: 0.0800462	total: 778ms	remaining: 3.36s
450:	learn: 0.0747445	total: 939ms	remaining: 3.23s
525:	learn: 0.0702342	total: 1.1s	remaining: 3.07s
600:	learn: 0.0656538	total: 1.27s	remaining: 2.95s
675:	learn: 0.0617229	total: 1.42s	remaining: 2.77s
750:	learn: 0.0580209	total: 1.58s	remaining: 2.63s
825:	learn: 0.0548540	total: 1.74s	remaining: 2.47s
900:	learn: 0.0522697	total: 1.89s	remaining: 2.3s
975:	learn: 0.0496410	total: 2.04s	remaining: 2.14s
1050:	learn: 0.0473268	total: 2.21s	remaining: 1.99s
1125:	learn: 0.0449347	total: 2.36s	remaining: 1.83s
1200:	learn: 0.0429052	total: 2.51s	remaining: 1.67s
1275:	learn: 0.0409070	total: 2.66s	remaining: 1.51s
1350:	learn: 0.0388815	total: 2.83s	remaining: 1.36s
1425:	learn: 0.0371406	total: 2.99s	remaining: 1.2s
1500:	learn: 0.0353684	total: 3.14s	remaining: 1.04s
1575:	learn: 0.0337431	total: 3.29s	remaining: 886ms
1650:	learn: 0.0322899	total: 3.44s	remaining: 727ms
1725:	learn: 0.0308553	total: 3.6s	remaining: 572ms
1800:	learn: 0.0296883	total: 3.77s	remaining: 416ms
1875:	learn: 0.0285593	total: 3.91s	remaining: 259ms
1950:	learn: 0.0274468	total: 4.06s	remaining: 102ms
1999:	learn: 0.0268284	total: 4.16s	remaining: 0us
0:	learn: 0.3860166	total: 2.42ms	remaining: 4.83s
75:	learn: 0.1283223	total: 168ms	remaining: 4.24s
150:	learn: 0.1041560	total: 327ms	remaining: 4s
225:	learn: 0.0924173	total: 479ms	remaining: 3.76s
300:	learn: 0.0843169	total: 627ms	remaining: 3.54s
375:	learn: 0.0782115	total: 775ms	remaining: 3.35s
450:	learn: 0.0732138	total: 922ms	remaining: 3.17s
525:	learn: 0.0693064	total: 1.06s	remaining: 2.98s
600:	learn: 0.0649043	total: 1.22s	remaining: 2.83s
675:	learn: 0.0614279	total: 1.38s	remaining: 2.7s
750:	learn: 0.0580671	total: 1.53s	remaining: 2.54s
825:	learn: 0.0548178	total: 1.69s	remaining: 2.4s
900:	learn: 0.0520272	total: 1.84s	remaining: 2.25s
975:	learn: 0.0494724	total: 2.02s	remaining: 2.12s
1050:	learn: 0.0473672	total: 2.17s	remaining: 1.96s
1125:	learn: 0.0452152	total: 2.32s	remaining: 1.8s
1200:	learn: 0.0429432	total: 2.48s	remaining: 1.65s
1275:	learn: 0.0411606	total: 2.64s	remaining: 1.5s
1350:	learn: 0.0393331	total: 2.79s	remaining: 1.34s
1425:	learn: 0.0376439	total: 2.94s	remaining: 1.18s
1500:	learn: 0.0360049	total: 3.08s	remaining: 1.02s
1575:	learn: 0.0345169	total: 3.25s	remaining: 875ms
1650:	learn: 0.0330625	total: 3.43s	remaining: 725ms
1725:	learn: 0.0316872	total: 3.58s	remaining: 568ms
1800:	learn: 0.0304288	total: 3.73s	remaining: 412ms
1875:	learn: 0.0293094	total: 3.88s	remaining: 256ms
1950:	learn: 0.0283129	total: 4.04s	remaining: 102ms
1999:	learn: 0.0275538	total: 4.14s	remaining: 0us

KRR score: 0.1176 (0.0103)

In [112]:
class AveragingModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, models):
        self.models = models
        
    # we define clones of the original models to fit the data in
    def fit(self, X, y):
        self.models_ = [clone(x) for x in self.models]
        
        # Train cloned base models
        for model in self.models_:
            model.fit(X, y)

        return self
    
    #Now we do the predictions for cloned models and average them
    def predict(self, X):
        predictions = np.column_stack([
            model.predict(X) for model in self.models_
        ])
        return np.mean(predictions, axis=1)

In [113]:
averaged_models = AveragingModels(models = (ENet, model_lgb, model_cat, lasso))

score = rmsle_cv(averaged_models)
print(" Averaged base models score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001146 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1634
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 188
[LightGBM] [Info] Start training from score 12.022143
0:	learn: 0.3900131	total: 4.17ms	remaining: 8.35s
75:	learn: 0.1326741	total: 211ms	remaining: 5.35s
150:	learn: 0.1070496	total: 576ms	remaining: 7.05s
225:	learn: 0.0948810	total: 742ms	remaining: 5.82s
300:	learn: 0.0865520	total: 897ms	remaining: 5.06s
375:	learn: 0.0800224	total: 1.05s	remaining: 4.55s
450:	learn: 0.0745109	total: 1.25s	remaining: 4.28s
525:	learn: 0.0692919	total: 1.43s	remaining: 4.01s
600:	learn: 0.0649656	total: 1.64s	remaining: 3.81s
675:	learn: 0.0612343	total: 1.81s	remaining: 3.55s
750:	learn: 0.0579884	total: 2s	remaining: 3.33s
825:	learn: 0.0547065	total: 2.18s	remaining: 3.1s
900:	learn: 0.0520757	total: 2.36s	remaining: 2.87s
975:	learn: 0.0495665	total: 2.59s	remaining: 2.71s
1050:	learn: 0.0471433	total: 2.79s	remaining: 2.52s
1125:	learn: 0.0447865	total: 2.98s	remaining: 2.31s
1200:	learn: 0.0425607	total: 3.17s	remaining: 2.11s
1275:	learn: 0.0406564	total: 3.37s	remaining: 1.91s
1350:	learn: 0.0388262	total: 3.58s	remaining: 1.72s
1425:	learn: 0.0371089	total: 3.74s	remaining: 1.5s
1500:	learn: 0.0354527	total: 3.94s	remaining: 1.31s
1575:	learn: 0.0341585	total: 4.11s	remaining: 1.1s
1650:	learn: 0.0328071	total: 4.29s	remaining: 906ms
1725:	learn: 0.0314254	total: 4.49s	remaining: 713ms
1800:	learn: 0.0301400	total: 4.67s	remaining: 516ms
1875:	learn: 0.0288917	total: 4.85s	remaining: 321ms
1950:	learn: 0.0276633	total: 5.01s	remaining: 126ms
1999:	learn: 0.0270032	total: 5.12s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001537 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1640
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 187
[LightGBM] [Info] Start training from score 12.024769
0:	learn: 0.3789812	total: 3.84ms	remaining: 7.68s
75:	learn: 0.1279609	total: 180ms	remaining: 4.57s
150:	learn: 0.1046739	total: 353ms	remaining: 4.32s
225:	learn: 0.0936471	total: 544ms	remaining: 4.27s
300:	learn: 0.0859479	total: 744ms	remaining: 4.2s
375:	learn: 0.0796236	total: 923ms	remaining: 3.98s
450:	learn: 0.0750874	total: 1.13s	remaining: 3.88s
525:	learn: 0.0700077	total: 1.32s	remaining: 3.71s
600:	learn: 0.0656152	total: 1.5s	remaining: 3.5s
675:	learn: 0.0620428	total: 1.7s	remaining: 3.33s
750:	learn: 0.0582520	total: 1.86s	remaining: 3.1s
825:	learn: 0.0552318	total: 2.04s	remaining: 2.9s
900:	learn: 0.0521909	total: 2.2s	remaining: 2.68s
975:	learn: 0.0492164	total: 2.37s	remaining: 2.48s
1050:	learn: 0.0466926	total: 2.54s	remaining: 2.29s
1125:	learn: 0.0443239	total: 2.74s	remaining: 2.12s
1200:	learn: 0.0420815	total: 2.9s	remaining: 1.93s
1275:	learn: 0.0398920	total: 3.06s	remaining: 1.74s
1350:	learn: 0.0378448	total: 3.21s	remaining: 1.54s
1425:	learn: 0.0359654	total: 3.39s	remaining: 1.36s
1500:	learn: 0.0341647	total: 3.65s	remaining: 1.22s
1575:	learn: 0.0326372	total: 3.86s	remaining: 1.04s
1650:	learn: 0.0311660	total: 4.05s	remaining: 856ms
1725:	learn: 0.0298591	total: 4.28s	remaining: 680ms
1800:	learn: 0.0284771	total: 4.45s	remaining: 492ms
1875:	learn: 0.0272864	total: 4.61s	remaining: 305ms
1950:	learn: 0.0261483	total: 4.8s	remaining: 121ms
1999:	learn: 0.0254206	total: 4.92s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002075 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1635
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 188
[LightGBM] [Info] Start training from score 12.023267
0:	learn: 0.3819148	total: 2.3ms	remaining: 4.6s
75:	learn: 0.1279853	total: 225ms	remaining: 5.69s
150:	learn: 0.1013252	total: 426ms	remaining: 5.22s
225:	learn: 0.0892077	total: 661ms	remaining: 5.19s
300:	learn: 0.0815619	total: 861ms	remaining: 4.86s
375:	learn: 0.0754015	total: 1.12s	remaining: 4.83s
450:	learn: 0.0702009	total: 1.33s	remaining: 4.56s
525:	learn: 0.0661209	total: 1.53s	remaining: 4.29s
600:	learn: 0.0618950	total: 1.82s	remaining: 4.23s
675:	learn: 0.0582641	total: 2.05s	remaining: 4.01s
750:	learn: 0.0549919	total: 2.24s	remaining: 3.73s
825:	learn: 0.0520682	total: 2.43s	remaining: 3.46s
900:	learn: 0.0490955	total: 2.64s	remaining: 3.22s
975:	learn: 0.0464305	total: 2.85s	remaining: 2.99s
1050:	learn: 0.0439045	total: 3.03s	remaining: 2.74s
1125:	learn: 0.0416881	total: 3.28s	remaining: 2.55s
1200:	learn: 0.0398478	total: 3.48s	remaining: 2.32s
1275:	learn: 0.0380367	total: 3.67s	remaining: 2.08s
1350:	learn: 0.0364769	total: 3.83s	remaining: 1.84s
1425:	learn: 0.0348599	total: 4s	remaining: 1.61s
1500:	learn: 0.0334816	total: 4.21s	remaining: 1.4s
1575:	learn: 0.0321528	total: 4.37s	remaining: 1.18s
1650:	learn: 0.0308892	total: 4.53s	remaining: 959ms
1725:	learn: 0.0295526	total: 4.71s	remaining: 747ms
1800:	learn: 0.0283560	total: 4.9s	remaining: 542ms
1875:	learn: 0.0273646	total: 5.06s	remaining: 335ms
1950:	learn: 0.0265310	total: 5.23s	remaining: 131ms
1999:	learn: 0.0259302	total: 5.34s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001118 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1644
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 187
[LightGBM] [Info] Start training from score 12.035129
0:	learn: 0.3875419	total: 3.47ms	remaining: 6.94s
75:	learn: 0.1310808	total: 187ms	remaining: 4.74s
150:	learn: 0.1065297	total: 357ms	remaining: 4.38s
225:	learn: 0.0944377	total: 519ms	remaining: 4.07s
300:	learn: 0.0863079	total: 678ms	remaining: 3.83s
375:	learn: 0.0800462	total: 839ms	remaining: 3.62s
450:	learn: 0.0747445	total: 1s	remaining: 3.45s
525:	learn: 0.0702342	total: 1.16s	remaining: 3.25s
600:	learn: 0.0656538	total: 1.33s	remaining: 3.1s
675:	learn: 0.0617229	total: 1.5s	remaining: 2.93s
750:	learn: 0.0580209	total: 1.66s	remaining: 2.76s
825:	learn: 0.0548540	total: 1.82s	remaining: 2.59s
900:	learn: 0.0522697	total: 1.99s	remaining: 2.43s
975:	learn: 0.0496410	total: 2.15s	remaining: 2.26s
1050:	learn: 0.0473268	total: 2.32s	remaining: 2.09s
1125:	learn: 0.0449347	total: 2.48s	remaining: 1.92s
1200:	learn: 0.0429052	total: 2.64s	remaining: 1.75s
1275:	learn: 0.0409070	total: 2.81s	remaining: 1.59s
1350:	learn: 0.0388815	total: 2.96s	remaining: 1.42s
1425:	learn: 0.0371406	total: 3.11s	remaining: 1.25s
1500:	learn: 0.0353684	total: 3.27s	remaining: 1.09s
1575:	learn: 0.0337431	total: 3.44s	remaining: 925ms
1650:	learn: 0.0322899	total: 3.6s	remaining: 760ms
1725:	learn: 0.0308553	total: 3.77s	remaining: 599ms
1800:	learn: 0.0296883	total: 3.95s	remaining: 437ms
1875:	learn: 0.0285593	total: 4.13s	remaining: 273ms
1950:	learn: 0.0274468	total: 4.33s	remaining: 109ms
1999:	learn: 0.0268284	total: 4.44s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001065 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1636
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 187
[LightGBM] [Info] Start training from score 12.024343
0:	learn: 0.3860166	total: 4.3ms	remaining: 8.61s
75:	learn: 0.1283223	total: 223ms	remaining: 5.64s
150:	learn: 0.1041560	total: 406ms	remaining: 4.97s
225:	learn: 0.0924173	total: 562ms	remaining: 4.41s
300:	learn: 0.0843169	total: 710ms	remaining: 4.01s
375:	learn: 0.0782115	total: 881ms	remaining: 3.8s
450:	learn: 0.0732138	total: 1.02s	remaining: 3.52s
525:	learn: 0.0693064	total: 1.18s	remaining: 3.31s
600:	learn: 0.0649043	total: 1.32s	remaining: 3.09s
675:	learn: 0.0614279	total: 1.49s	remaining: 2.91s
750:	learn: 0.0580671	total: 1.64s	remaining: 2.73s
825:	learn: 0.0548178	total: 1.79s	remaining: 2.55s
900:	learn: 0.0520272	total: 1.94s	remaining: 2.37s
975:	learn: 0.0494724	total: 2.1s	remaining: 2.2s
1050:	learn: 0.0473672	total: 2.24s	remaining: 2.02s
1125:	learn: 0.0452152	total: 2.4s	remaining: 1.87s
1200:	learn: 0.0429432	total: 2.55s	remaining: 1.7s
1275:	learn: 0.0411606	total: 2.7s	remaining: 1.53s
1350:	learn: 0.0393331	total: 2.85s	remaining: 1.37s
1425:	learn: 0.0376439	total: 2.99s	remaining: 1.21s
1500:	learn: 0.0360049	total: 3.14s	remaining: 1.04s
1575:	learn: 0.0345169	total: 3.29s	remaining: 885ms
1650:	learn: 0.0330625	total: 3.45s	remaining: 729ms
1725:	learn: 0.0316872	total: 3.6s	remaining: 571ms
1800:	learn: 0.0304288	total: 3.77s	remaining: 416ms
1875:	learn: 0.0293094	total: 3.91s	remaining: 259ms
1950:	learn: 0.0283129	total: 4.07s	remaining: 102ms
1999:	learn: 0.0275538	total: 4.18s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
 Averaged base models score: 0.1156 (0.0140)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [114]:
class StackingAveragedModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, base_models, meta_model, n_folds=5):
        self.base_models = base_models
        self.meta_model = meta_model
        self.n_folds = n_folds
   
    # We again fit the data on clones of the original models
    def fit(self, X, y):
        self.base_models_ = [list() for x in self.base_models]
        self.meta_model_ = clone(self.meta_model)
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=156)
        
        # Train cloned base models then create out-of-fold predictions
        # that are needed to train the cloned meta-model
        out_of_fold_predictions = np.zeros((X.shape[0], len(self.base_models)))
        for i, model in enumerate(self.base_models):
            for train_index, holdout_index in kfold.split(X, y):
                instance = clone(model)
                self.base_models_[i].append(instance)
                instance.fit(X[train_index], y[train_index])
                y_pred = instance.predict(X[holdout_index])
                out_of_fold_predictions[holdout_index, i] = y_pred
                
        # Now train the cloned  meta-model using the out-of-fold predictions as new feature
        self.meta_model_.fit(out_of_fold_predictions, y)
        return self
    def predict(self, X):
        meta_features = np.column_stack([
            np.column_stack([model.predict(X) for model in base_models]).mean(axis=1)
            for base_models in self.base_models_ ])
        return self.meta_model_.predict(meta_features)

In [115]:
stacked_averaged_models = StackingAveragedModels(base_models = (ENet, model_lgb, model_cat),
                                                 meta_model = lasso)

score = rmsle_cv(stacked_averaged_models)
print("Stacking Averaged models score: {:.4f} ({:.4f})".format(score.mean(), score.std()))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002055 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1596
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.020986

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002289 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1587
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.031195

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002051 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1587
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 181
[LightGBM] [Info] Start training from score 12.015888

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001497 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1595
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.015910

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001957 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1586
[LightGBM] [Info] Number of data points in the train set: 932, number of used features: 182
[LightGBM] [Info] Start training from score 12.026731

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3874200	total: 2.57ms	remaining: 5.14s
75:	learn: 0.1268976	total: 167ms	remaining: 4.22s
150:	learn: 0.1029327	total: 314ms	remaining: 3.85s
225:	learn: 0.0912864	total: 480ms	remaining: 3.77s
300:	learn: 0.0821058	total: 634ms	remaining: 3.58s
375:	learn: 0.0748250	total: 788ms	remaining: 3.4s
450:	learn: 0.0690713	total: 931ms	remaining: 3.2s
525:	learn: 0.0638439	total: 1.08s	remaining: 3.04s
600:	learn: 0.0588561	total: 1.23s	remaining: 2.86s
675:	learn: 0.0550844	total: 1.4s	remaining: 2.73s
750:	learn: 0.0510074	total: 1.55s	remaining: 2.58s
825:	learn: 0.0477294	total: 1.71s	remaining: 2.43s
900:	learn: 0.0448470	total: 1.85s	remaining: 2.25s
975:	learn: 0.0422935	total: 2s	remaining: 2.1s
1050:	learn: 0.0399025	total: 2.15s	remaining: 1.94s
1125:	learn: 0.0377565	total: 2.3s	remaining: 1.78s
1200:	learn: 0.0354517	total: 2.46s	remaining: 1.64s
1275:	learn: 0.0337186	total: 2.62s	remaining: 1.48s
1350:	learn: 0.0320620	total: 2.78s	remaining: 1.33s
1425:	learn: 0.0305040	total: 2.96s	remaining: 1.19s
1500:	learn: 0.0289474	total: 3.12s	remaining: 1.04s
1575:	learn: 0.0275669	total: 3.33s	remaining: 897ms
1650:	learn: 0.0259920	total: 3.49s	remaining: 738ms
1725:	learn: 0.0247748	total: 3.67s	remaining: 582ms
1800:	learn: 0.0234229	total: 3.82s	remaining: 422ms
1875:	learn: 0.0222687	total: 3.98s	remaining: 263ms
1950:	learn: 0.0213021	total: 4.12s	remaining: 103ms
1999:	learn: 0.0206758	total: 4.22s	remaining: 0us
0:	learn: 0.3840241	total: 2.27ms	remaining: 4.54s
75:	learn: 0.1281286	total: 164ms	remaining: 4.14s
150:	learn: 0.1037429	total: 309ms	remaining: 3.79s
225:	learn: 0.0895236	total: 460ms	remaining: 3.61s
300:	learn: 0.0816718	total: 604ms	remaining: 3.41s
375:	learn: 0.0754650	total: 760ms	remaining: 3.28s
450:	learn: 0.0704301	total: 916ms	remaining: 3.15s
525:	learn: 0.0654951	total: 1.06s	remaining: 2.98s
600:	learn: 0.0612701	total: 1.21s	remaining: 2.81s
675:	learn: 0.0571731	total: 1.35s	remaining: 2.65s
750:	learn: 0.0534177	total: 1.53s	remaining: 2.54s
825:	learn: 0.0504140	total: 1.69s	remaining: 2.4s
900:	learn: 0.0472966	total: 1.84s	remaining: 2.24s
975:	learn: 0.0444644	total: 1.99s	remaining: 2.08s
1050:	learn: 0.0421575	total: 2.14s	remaining: 1.94s
1125:	learn: 0.0399350	total: 2.3s	remaining: 1.79s
1200:	learn: 0.0376065	total: 2.45s	remaining: 1.63s
1275:	learn: 0.0358122	total: 2.6s	remaining: 1.47s
1350:	learn: 0.0338639	total: 2.76s	remaining: 1.32s
1425:	learn: 0.0320935	total: 2.92s	remaining: 1.18s
1500:	learn: 0.0306147	total: 3.07s	remaining: 1.02s
1575:	learn: 0.0293123	total: 3.22s	remaining: 867ms
1650:	learn: 0.0279095	total: 3.38s	remaining: 715ms
1725:	learn: 0.0265505	total: 3.53s	remaining: 561ms
1800:	learn: 0.0253109	total: 3.68s	remaining: 407ms
1875:	learn: 0.0243562	total: 3.86s	remaining: 255ms
1950:	learn: 0.0232893	total: 4.01s	remaining: 101ms
1999:	learn: 0.0225685	total: 4.1s	remaining: 0us
0:	learn: 0.3922692	total: 3.04ms	remaining: 6.08s
75:	learn: 0.1379008	total: 176ms	remaining: 4.45s
150:	learn: 0.1090546	total: 332ms	remaining: 4.06s
225:	learn: 0.0970853	total: 481ms	remaining: 3.77s
300:	learn: 0.0884986	total: 627ms	remaining: 3.54s
375:	learn: 0.0807673	total: 776ms	remaining: 3.35s
450:	learn: 0.0738943	total: 923ms	remaining: 3.17s
525:	learn: 0.0680078	total: 1.09s	remaining: 3.05s
600:	learn: 0.0630022	total: 1.23s	remaining: 2.87s
675:	learn: 0.0591805	total: 1.38s	remaining: 2.71s
750:	learn: 0.0556577	total: 1.53s	remaining: 2.54s
825:	learn: 0.0520189	total: 1.67s	remaining: 2.38s
900:	learn: 0.0487996	total: 1.82s	remaining: 2.22s
975:	learn: 0.0456503	total: 1.98s	remaining: 2.07s
1050:	learn: 0.0431575	total: 2.12s	remaining: 1.92s
1125:	learn: 0.0404722	total: 2.27s	remaining: 1.76s
1200:	learn: 0.0383753	total: 2.41s	remaining: 1.61s
1275:	learn: 0.0366703	total: 2.56s	remaining: 1.45s
1350:	learn: 0.0348394	total: 2.7s	remaining: 1.3s
1425:	learn: 0.0330689	total: 2.86s	remaining: 1.15s
1500:	learn: 0.0316648	total: 3.01s	remaining: 1s
1575:	learn: 0.0301212	total: 3.18s	remaining: 856ms
1650:	learn: 0.0287306	total: 3.33s	remaining: 703ms
1725:	learn: 0.0273312	total: 3.47s	remaining: 552ms
1800:	learn: 0.0263264	total: 3.64s	remaining: 402ms
1875:	learn: 0.0252323	total: 3.79s	remaining: 250ms
1950:	learn: 0.0240401	total: 3.95s	remaining: 99.1ms
1999:	learn: 0.0233654	total: 4.05s	remaining: 0us
0:	learn: 0.3937355	total: 2.54ms	remaining: 5.07s
75:	learn: 0.1338741	total: 180ms	remaining: 4.56s
150:	learn: 0.1081099	total: 328ms	remaining: 4.01s
225:	learn: 0.0947084	total: 476ms	remaining: 3.73s
300:	learn: 0.0857075	total: 633ms	remaining: 3.57s
375:	learn: 0.0788075	total: 777ms	remaining: 3.36s
450:	learn: 0.0735502	total: 922ms	remaining: 3.17s
525:	learn: 0.0683351	total: 1.07s	remaining: 3s
600:	learn: 0.0631350	total: 1.23s	remaining: 2.86s
675:	learn: 0.0589962	total: 1.37s	remaining: 2.69s
750:	learn: 0.0552290	total: 1.52s	remaining: 2.52s
825:	learn: 0.0518612	total: 1.68s	remaining: 2.38s
900:	learn: 0.0487886	total: 1.84s	remaining: 2.24s
975:	learn: 0.0457784	total: 1.98s	remaining: 2.08s
1050:	learn: 0.0428184	total: 2.13s	remaining: 1.92s
1125:	learn: 0.0403829	total: 2.28s	remaining: 1.77s
1200:	learn: 0.0383105	total: 2.42s	remaining: 1.61s
1275:	learn: 0.0363734	total: 2.57s	remaining: 1.46s
1350:	learn: 0.0344818	total: 2.73s	remaining: 1.31s
1425:	learn: 0.0327449	total: 2.9s	remaining: 1.17s
1500:	learn: 0.0312579	total: 3.04s	remaining: 1.01s
1575:	learn: 0.0296236	total: 3.19s	remaining: 859ms
1650:	learn: 0.0282002	total: 3.34s	remaining: 706ms
1725:	learn: 0.0269460	total: 3.48s	remaining: 553ms
1800:	learn: 0.0257405	total: 3.65s	remaining: 403ms
1875:	learn: 0.0245043	total: 3.79s	remaining: 251ms
1950:	learn: 0.0232725	total: 3.94s	remaining: 99.1ms
1999:	learn: 0.0226262	total: 4.04s	remaining: 0us
0:	learn: 0.3885027	total: 2.66ms	remaining: 5.33s
75:	learn: 0.1320596	total: 159ms	remaining: 4.03s
150:	learn: 0.1055496	total: 305ms	remaining: 3.74s
225:	learn: 0.0914184	total: 447ms	remaining: 3.5s
300:	learn: 0.0824594	total: 609ms	remaining: 3.44s
375:	learn: 0.0754621	total: 751ms	remaining: 3.24s
450:	learn: 0.0688524	total: 920ms	remaining: 3.16s
525:	learn: 0.0631249	total: 1.06s	remaining: 2.98s
600:	learn: 0.0584314	total: 1.21s	remaining: 2.81s
675:	learn: 0.0548389	total: 1.36s	remaining: 2.67s
750:	learn: 0.0515271	total: 1.51s	remaining: 2.52s
825:	learn: 0.0482139	total: 1.66s	remaining: 2.36s
900:	learn: 0.0454589	total: 1.8s	remaining: 2.2s
975:	learn: 0.0428546	total: 1.96s	remaining: 2.06s
1050:	learn: 0.0402709	total: 2.11s	remaining: 1.91s
1125:	learn: 0.0377959	total: 2.26s	remaining: 1.75s
1200:	learn: 0.0356609	total: 2.4s	remaining: 1.6s
1275:	learn: 0.0339165	total: 2.54s	remaining: 1.44s
1350:	learn: 0.0322852	total: 2.72s	remaining: 1.3s
1425:	learn: 0.0306501	total: 2.86s	remaining: 1.15s
1500:	learn: 0.0290400	total: 3.01s	remaining: 1s
1575:	learn: 0.0275894	total: 3.15s	remaining: 848ms
1650:	learn: 0.0263058	total: 3.3s	remaining: 698ms
1725:	learn: 0.0251769	total: 3.45s	remaining: 548ms
1800:	learn: 0.0238495	total: 3.61s	remaining: 399ms
1875:	learn: 0.0226865	total: 3.75s	remaining: 248ms
1950:	learn: 0.0217442	total: 3.92s	remaining: 98.3ms
1999:	learn: 0.0210358	total: 4.01s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001145 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1594
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.029148

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001677 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1582
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 179
[LightGBM] [Info] Start training from score 12.027216

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001636 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1598
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.013956

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002424 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1600
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 185
[LightGBM] [Info] Start training from score 12.018727

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002698 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1588
[LightGBM] [Info] Number of data points in the train set: 932, number of used features: 180
[LightGBM] [Info] Start training from score 12.034786

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3719875	total: 2.31ms	remaining: 4.62s
75:	learn: 0.1260433	total: 187ms	remaining: 4.73s
150:	learn: 0.1012823	total: 329ms	remaining: 4.03s
225:	learn: 0.0885098	total: 489ms	remaining: 3.84s
300:	learn: 0.0795048	total: 646ms	remaining: 3.65s
375:	learn: 0.0732060	total: 797ms	remaining: 3.44s
450:	learn: 0.0683154	total: 945ms	remaining: 3.24s
525:	learn: 0.0634189	total: 1.11s	remaining: 3.12s
600:	learn: 0.0589397	total: 1.27s	remaining: 2.95s
675:	learn: 0.0551556	total: 1.42s	remaining: 2.78s
750:	learn: 0.0515899	total: 1.57s	remaining: 2.6s
825:	learn: 0.0483777	total: 1.74s	remaining: 2.47s
900:	learn: 0.0457691	total: 1.89s	remaining: 2.3s
975:	learn: 0.0430927	total: 2.05s	remaining: 2.15s
1050:	learn: 0.0404350	total: 2.2s	remaining: 1.99s
1125:	learn: 0.0382896	total: 2.36s	remaining: 1.83s
1200:	learn: 0.0362236	total: 2.52s	remaining: 1.68s
1275:	learn: 0.0343841	total: 2.68s	remaining: 1.52s
1350:	learn: 0.0326490	total: 2.82s	remaining: 1.35s
1425:	learn: 0.0311816	total: 2.97s	remaining: 1.2s
1500:	learn: 0.0296976	total: 3.12s	remaining: 1.04s
1575:	learn: 0.0283365	total: 3.27s	remaining: 880ms
1650:	learn: 0.0271158	total: 3.43s	remaining: 725ms
1725:	learn: 0.0259740	total: 3.58s	remaining: 569ms
1800:	learn: 0.0247420	total: 3.74s	remaining: 413ms
1875:	learn: 0.0236765	total: 3.9s	remaining: 258ms
1950:	learn: 0.0225614	total: 4.05s	remaining: 102ms
1999:	learn: 0.0218050	total: 4.14s	remaining: 0us
0:	learn: 0.3785489	total: 3.44ms	remaining: 6.87s
75:	learn: 0.1221759	total: 175ms	remaining: 4.43s
150:	learn: 0.0964716	total: 331ms	remaining: 4.05s
225:	learn: 0.0852141	total: 489ms	remaining: 3.84s
300:	learn: 0.0777452	total: 632ms	remaining: 3.57s
375:	learn: 0.0713287	total: 798ms	remaining: 3.45s
450:	learn: 0.0660214	total: 952ms	remaining: 3.27s
525:	learn: 0.0616494	total: 1.12s	remaining: 3.13s
600:	learn: 0.0574513	total: 1.26s	remaining: 2.94s
675:	learn: 0.0535330	total: 1.42s	remaining: 2.78s
750:	learn: 0.0503580	total: 1.58s	remaining: 2.62s
825:	learn: 0.0473524	total: 1.72s	remaining: 2.45s
900:	learn: 0.0443372	total: 1.87s	remaining: 2.28s
975:	learn: 0.0416301	total: 2.02s	remaining: 2.12s
1050:	learn: 0.0392091	total: 2.19s	remaining: 1.98s
1125:	learn: 0.0369769	total: 2.35s	remaining: 1.82s
1200:	learn: 0.0349572	total: 2.5s	remaining: 1.66s
1275:	learn: 0.0331449	total: 2.65s	remaining: 1.5s
1350:	learn: 0.0314620	total: 2.81s	remaining: 1.35s
1425:	learn: 0.0298452	total: 2.95s	remaining: 1.19s
1500:	learn: 0.0283649	total: 3.1s	remaining: 1.03s
1575:	learn: 0.0271258	total: 3.25s	remaining: 874ms
1650:	learn: 0.0259252	total: 3.42s	remaining: 722ms
1725:	learn: 0.0247979	total: 3.58s	remaining: 568ms
1800:	learn: 0.0236554	total: 3.73s	remaining: 412ms
1875:	learn: 0.0226231	total: 3.87s	remaining: 256ms
1950:	learn: 0.0215754	total: 4.02s	remaining: 101ms
1999:	learn: 0.0209349	total: 4.11s	remaining: 0us
0:	learn: 0.3791764	total: 2.82ms	remaining: 5.64s
75:	learn: 0.1341231	total: 171ms	remaining: 4.33s
150:	learn: 0.1071353	total: 323ms	remaining: 3.96s
225:	learn: 0.0944333	total: 467ms	remaining: 3.67s
300:	learn: 0.0853841	total: 622ms	remaining: 3.51s
375:	learn: 0.0786614	total: 767ms	remaining: 3.31s
450:	learn: 0.0728134	total: 914ms	remaining: 3.14s
525:	learn: 0.0678523	total: 1.05s	remaining: 2.95s
600:	learn: 0.0634663	total: 1.21s	remaining: 2.81s
675:	learn: 0.0593712	total: 1.37s	remaining: 2.68s
750:	learn: 0.0556137	total: 1.52s	remaining: 2.52s
825:	learn: 0.0524707	total: 1.68s	remaining: 2.38s
900:	learn: 0.0493609	total: 1.82s	remaining: 2.23s
975:	learn: 0.0465074	total: 1.97s	remaining: 2.06s
1050:	learn: 0.0435762	total: 2.13s	remaining: 1.92s
1125:	learn: 0.0412205	total: 2.27s	remaining: 1.76s
1200:	learn: 0.0386359	total: 2.42s	remaining: 1.61s
1275:	learn: 0.0366575	total: 2.56s	remaining: 1.45s
1350:	learn: 0.0346019	total: 2.72s	remaining: 1.31s
1425:	learn: 0.0325153	total: 2.88s	remaining: 1.16s
1500:	learn: 0.0305422	total: 3.02s	remaining: 1s
1575:	learn: 0.0288797	total: 3.17s	remaining: 852ms
1650:	learn: 0.0272781	total: 3.31s	remaining: 701ms
1725:	learn: 0.0257098	total: 3.47s	remaining: 551ms
1800:	learn: 0.0244686	total: 3.62s	remaining: 400ms
1875:	learn: 0.0232507	total: 3.76s	remaining: 249ms
1950:	learn: 0.0222229	total: 3.91s	remaining: 98.2ms
1999:	learn: 0.0215485	total: 4s	remaining: 0us
0:	learn: 0.3822589	total: 2.27ms	remaining: 4.53s
75:	learn: 0.1289973	total: 195ms	remaining: 4.93s
150:	learn: 0.1050315	total: 350ms	remaining: 4.29s
225:	learn: 0.0935568	total: 495ms	remaining: 3.88s
300:	learn: 0.0848129	total: 636ms	remaining: 3.59s
375:	learn: 0.0787816	total: 780ms	remaining: 3.37s
450:	learn: 0.0738920	total: 923ms	remaining: 3.17s
525:	learn: 0.0693944	total: 1.06s	remaining: 2.99s
600:	learn: 0.0643370	total: 1.21s	remaining: 2.82s
675:	learn: 0.0600167	total: 1.37s	remaining: 2.69s
750:	learn: 0.0566050	total: 1.51s	remaining: 2.52s
825:	learn: 0.0531186	total: 1.66s	remaining: 2.36s
900:	learn: 0.0498722	total: 1.8s	remaining: 2.2s
975:	learn: 0.0468864	total: 1.95s	remaining: 2.04s
1050:	learn: 0.0442210	total: 2.09s	remaining: 1.89s
1125:	learn: 0.0416818	total: 2.24s	remaining: 1.74s
1200:	learn: 0.0394207	total: 2.39s	remaining: 1.59s
1275:	learn: 0.0374405	total: 2.55s	remaining: 1.45s
1350:	learn: 0.0352415	total: 2.69s	remaining: 1.29s
1425:	learn: 0.0333602	total: 2.86s	remaining: 1.15s
1500:	learn: 0.0315501	total: 3.02s	remaining: 1s
1575:	learn: 0.0300121	total: 3.17s	remaining: 852ms
1650:	learn: 0.0284720	total: 3.33s	remaining: 703ms
1725:	learn: 0.0270938	total: 3.47s	remaining: 551ms
1800:	learn: 0.0259704	total: 3.62s	remaining: 400ms
1875:	learn: 0.0247799	total: 3.76s	remaining: 249ms
1950:	learn: 0.0234590	total: 3.95s	remaining: 99.2ms
1999:	learn: 0.0227026	total: 4.08s	remaining: 0us
0:	learn: 0.3787112	total: 2.64ms	remaining: 5.27s
75:	learn: 0.1263035	total: 168ms	remaining: 4.24s
150:	learn: 0.1016680	total: 355ms	remaining: 4.34s
225:	learn: 0.0892985	total: 577ms	remaining: 4.53s
300:	learn: 0.0817709	total: 778ms	remaining: 4.39s
375:	learn: 0.0754690	total: 980ms	remaining: 4.23s
450:	learn: 0.0700221	total: 1.16s	remaining: 3.99s
525:	learn: 0.0655716	total: 1.36s	remaining: 3.8s
600:	learn: 0.0607740	total: 1.6s	remaining: 3.73s
675:	learn: 0.0563888	total: 1.78s	remaining: 3.49s
750:	learn: 0.0527715	total: 1.95s	remaining: 3.24s
825:	learn: 0.0493395	total: 2.12s	remaining: 3.02s
900:	learn: 0.0460736	total: 2.3s	remaining: 2.81s
975:	learn: 0.0434423	total: 2.48s	remaining: 2.6s
1050:	learn: 0.0408218	total: 2.66s	remaining: 2.4s
1125:	learn: 0.0385918	total: 2.85s	remaining: 2.21s
1200:	learn: 0.0363428	total: 3.05s	remaining: 2.03s
1275:	learn: 0.0341830	total: 3.25s	remaining: 1.84s
1350:	learn: 0.0321846	total: 3.44s	remaining: 1.65s
1425:	learn: 0.0301987	total: 3.64s	remaining: 1.47s
1500:	learn: 0.0284761	total: 3.81s	remaining: 1.26s
1575:	learn: 0.0270232	total: 4s	remaining: 1.08s
1650:	learn: 0.0255110	total: 4.18s	remaining: 884ms
1725:	learn: 0.0242471	total: 4.36s	remaining: 692ms
1800:	learn: 0.0229358	total: 4.53s	remaining: 501ms
1875:	learn: 0.0218128	total: 4.69s	remaining: 310ms
1950:	learn: 0.0207810	total: 4.84s	remaining: 122ms
1999:	learn: 0.0200918	total: 4.95s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001459 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1575
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 180
[LightGBM] [Info] Start training from score 12.028196

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001886 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1581
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.022511

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001788 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1595
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 183
[LightGBM] [Info] Start training from score 12.015887

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001309 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1592
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 184
[LightGBM] [Info] Start training from score 12.011535

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001446 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1575
[LightGBM] [Info] Number of data points in the train set: 932, number of used features: 179
[LightGBM] [Info] Start training from score 12.038191

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3763566	total: 3.46ms	remaining: 6.91s
75:	learn: 0.1275100	total: 179ms	remaining: 4.53s
150:	learn: 0.0983300	total: 335ms	remaining: 4.11s
225:	learn: 0.0858680	total: 489ms	remaining: 3.84s
300:	learn: 0.0764976	total: 646ms	remaining: 3.65s
375:	learn: 0.0694147	total: 810ms	remaining: 3.5s
450:	learn: 0.0637143	total: 959ms	remaining: 3.29s
525:	learn: 0.0589906	total: 1.13s	remaining: 3.17s
600:	learn: 0.0552121	total: 1.34s	remaining: 3.12s
675:	learn: 0.0516000	total: 1.55s	remaining: 3.04s
750:	learn: 0.0484538	total: 1.84s	remaining: 3.06s
825:	learn: 0.0452590	total: 2.11s	remaining: 3s
900:	learn: 0.0426362	total: 2.39s	remaining: 2.91s
975:	learn: 0.0402393	total: 2.54s	remaining: 2.67s
1050:	learn: 0.0379336	total: 2.71s	remaining: 2.45s
1125:	learn: 0.0358950	total: 2.88s	remaining: 2.23s
1200:	learn: 0.0340423	total: 3.05s	remaining: 2.03s
1275:	learn: 0.0323503	total: 3.19s	remaining: 1.81s
1350:	learn: 0.0308045	total: 3.36s	remaining: 1.61s
1425:	learn: 0.0291661	total: 3.56s	remaining: 1.43s
1500:	learn: 0.0276046	total: 3.75s	remaining: 1.25s
1575:	learn: 0.0261706	total: 3.93s	remaining: 1.06s
1650:	learn: 0.0248031	total: 4.12s	remaining: 870ms
1725:	learn: 0.0235616	total: 4.31s	remaining: 684ms
1800:	learn: 0.0223630	total: 4.48s	remaining: 495ms
1875:	learn: 0.0213710	total: 4.66s	remaining: 308ms
1950:	learn: 0.0203643	total: 4.87s	remaining: 122ms
1999:	learn: 0.0197338	total: 5s	remaining: 0us
0:	learn: 0.3817620	total: 3.89ms	remaining: 7.77s
75:	learn: 0.1276056	total: 216ms	remaining: 5.48s
150:	learn: 0.1000488	total: 429ms	remaining: 5.26s
225:	learn: 0.0860230	total: 653ms	remaining: 5.12s
300:	learn: 0.0765735	total: 854ms	remaining: 4.82s
375:	learn: 0.0699318	total: 1.01s	remaining: 4.35s
450:	learn: 0.0646741	total: 1.19s	remaining: 4.1s
525:	learn: 0.0602807	total: 1.36s	remaining: 3.83s
600:	learn: 0.0564092	total: 1.51s	remaining: 3.52s
675:	learn: 0.0534003	total: 1.67s	remaining: 3.26s
750:	learn: 0.0500996	total: 1.84s	remaining: 3.06s
825:	learn: 0.0470792	total: 2.06s	remaining: 2.92s
900:	learn: 0.0443855	total: 2.28s	remaining: 2.78s
975:	learn: 0.0419272	total: 2.54s	remaining: 2.66s
1050:	learn: 0.0395916	total: 2.77s	remaining: 2.5s
1125:	learn: 0.0373864	total: 2.98s	remaining: 2.31s
1200:	learn: 0.0355763	total: 3.17s	remaining: 2.11s
1275:	learn: 0.0337752	total: 3.36s	remaining: 1.91s
1350:	learn: 0.0321682	total: 3.52s	remaining: 1.69s
1425:	learn: 0.0308366	total: 3.68s	remaining: 1.48s
1500:	learn: 0.0295406	total: 3.89s	remaining: 1.29s
1575:	learn: 0.0282971	total: 4.18s	remaining: 1.12s
1650:	learn: 0.0269773	total: 4.44s	remaining: 939ms
1725:	learn: 0.0257765	total: 4.65s	remaining: 738ms
1800:	learn: 0.0246270	total: 4.85s	remaining: 536ms
1875:	learn: 0.0235531	total: 5.07s	remaining: 335ms
1950:	learn: 0.0224051	total: 5.34s	remaining: 134ms
1999:	learn: 0.0217985	total: 5.5s	remaining: 0us
0:	learn: 0.3839096	total: 2.65ms	remaining: 5.3s
75:	learn: 0.1316587	total: 179ms	remaining: 4.53s
150:	learn: 0.1032545	total: 411ms	remaining: 5.03s
225:	learn: 0.0897678	total: 616ms	remaining: 4.84s
300:	learn: 0.0807275	total: 835ms	remaining: 4.71s
375:	learn: 0.0734706	total: 1.04s	remaining: 4.5s
450:	learn: 0.0677342	total: 1.19s	remaining: 4.1s
525:	learn: 0.0626979	total: 1.39s	remaining: 3.89s
600:	learn: 0.0582494	total: 1.57s	remaining: 3.66s
675:	learn: 0.0543057	total: 1.75s	remaining: 3.42s
750:	learn: 0.0505610	total: 1.89s	remaining: 3.15s
825:	learn: 0.0473461	total: 2.06s	remaining: 2.92s
900:	learn: 0.0441381	total: 2.23s	remaining: 2.72s
975:	learn: 0.0416939	total: 2.38s	remaining: 2.5s
1050:	learn: 0.0394460	total: 2.53s	remaining: 2.29s
1125:	learn: 0.0371944	total: 2.7s	remaining: 2.09s
1200:	learn: 0.0350297	total: 2.85s	remaining: 1.89s
1275:	learn: 0.0331273	total: 3.05s	remaining: 1.73s
1350:	learn: 0.0310962	total: 3.25s	remaining: 1.56s
1425:	learn: 0.0294950	total: 3.49s	remaining: 1.4s
1500:	learn: 0.0277707	total: 3.73s	remaining: 1.24s
1575:	learn: 0.0261975	total: 3.96s	remaining: 1.06s
1650:	learn: 0.0250433	total: 4.17s	remaining: 881ms
1725:	learn: 0.0237829	total: 4.37s	remaining: 694ms
1800:	learn: 0.0226244	total: 4.6s	remaining: 508ms
1875:	learn: 0.0216727	total: 4.84s	remaining: 320ms
1950:	learn: 0.0207124	total: 5.14s	remaining: 129ms
1999:	learn: 0.0200386	total: 5.25s	remaining: 0us
0:	learn: 0.3817699	total: 2.66ms	remaining: 5.33s
75:	learn: 0.1258100	total: 210ms	remaining: 5.31s
150:	learn: 0.1008358	total: 428ms	remaining: 5.25s
225:	learn: 0.0875201	total: 637ms	remaining: 5s
300:	learn: 0.0797917	total: 837ms	remaining: 4.72s
375:	learn: 0.0729980	total: 1.06s	remaining: 4.59s
450:	learn: 0.0675187	total: 1.26s	remaining: 4.35s
525:	learn: 0.0628404	total: 1.46s	remaining: 4.09s
600:	learn: 0.0582066	total: 1.68s	remaining: 3.91s
675:	learn: 0.0543758	total: 1.9s	remaining: 3.73s
750:	learn: 0.0507791	total: 2.13s	remaining: 3.54s
825:	learn: 0.0471991	total: 2.32s	remaining: 3.29s
900:	learn: 0.0441851	total: 2.53s	remaining: 3.09s
975:	learn: 0.0413267	total: 2.75s	remaining: 2.88s
1050:	learn: 0.0389570	total: 2.92s	remaining: 2.63s
1125:	learn: 0.0365843	total: 3.07s	remaining: 2.38s
1200:	learn: 0.0344877	total: 3.24s	remaining: 2.15s
1275:	learn: 0.0325694	total: 3.45s	remaining: 1.96s
1350:	learn: 0.0306462	total: 3.68s	remaining: 1.77s
1425:	learn: 0.0288398	total: 3.9s	remaining: 1.57s
1500:	learn: 0.0270595	total: 4.21s	remaining: 1.4s
1575:	learn: 0.0255993	total: 4.43s	remaining: 1.19s
1650:	learn: 0.0242462	total: 4.63s	remaining: 979ms
1725:	learn: 0.0229593	total: 4.85s	remaining: 769ms
1800:	learn: 0.0217087	total: 5.02s	remaining: 555ms
1875:	learn: 0.0206493	total: 5.17s	remaining: 342ms
1950:	learn: 0.0195594	total: 5.4s	remaining: 136ms
1999:	learn: 0.0188481	total: 5.56s	remaining: 0us
0:	learn: 0.3821743	total: 5.57ms	remaining: 11.1s
75:	learn: 0.1282519	total: 169ms	remaining: 4.28s
150:	learn: 0.0982343	total: 342ms	remaining: 4.19s
225:	learn: 0.0846284	total: 610ms	remaining: 4.79s
300:	learn: 0.0758356	total: 765ms	remaining: 4.32s
375:	learn: 0.0695254	total: 914ms	remaining: 3.95s
450:	learn: 0.0634145	total: 1.1s	remaining: 3.77s
525:	learn: 0.0585739	total: 1.32s	remaining: 3.71s
600:	learn: 0.0544445	total: 1.53s	remaining: 3.56s
675:	learn: 0.0505073	total: 1.75s	remaining: 3.43s
750:	learn: 0.0472078	total: 1.95s	remaining: 3.24s
825:	learn: 0.0440335	total: 2.14s	remaining: 3.05s
900:	learn: 0.0410787	total: 2.35s	remaining: 2.86s
975:	learn: 0.0387860	total: 2.51s	remaining: 2.64s
1050:	learn: 0.0363843	total: 2.67s	remaining: 2.41s
1125:	learn: 0.0345162	total: 2.86s	remaining: 2.22s
1200:	learn: 0.0327795	total: 3.07s	remaining: 2.04s
1275:	learn: 0.0308034	total: 3.24s	remaining: 1.84s
1350:	learn: 0.0290938	total: 3.4s	remaining: 1.64s
1425:	learn: 0.0274816	total: 3.58s	remaining: 1.44s
1500:	learn: 0.0260617	total: 3.79s	remaining: 1.26s
1575:	learn: 0.0248151	total: 3.97s	remaining: 1.07s
1650:	learn: 0.0236469	total: 4.13s	remaining: 872ms
1725:	learn: 0.0224421	total: 4.28s	remaining: 680ms
1800:	learn: 0.0213459	total: 4.44s	remaining: 491ms
1875:	learn: 0.0204094	total: 4.61s	remaining: 305ms
1950:	learn: 0.0193936	total: 4.8s	remaining: 121ms
1999:	learn: 0.0187654	total: 4.92s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001558 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1587
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 181
[LightGBM] [Info] Start training from score 12.035459

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002955 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1600
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 181
[LightGBM] [Info] Start training from score 12.035729

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002593 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1607
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 183
[LightGBM] [Info] Start training from score 12.032068

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001596 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1612
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 185
[LightGBM] [Info] Start training from score 12.023840

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001528 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1599
[LightGBM] [Info] Number of data points in the train set: 932, number of used features: 179
[LightGBM] [Info] Start training from score 12.048534

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3775246	total: 2.44ms	remaining: 4.88s
75:	learn: 0.1318417	total: 204ms	remaining: 5.16s
150:	learn: 0.1035312	total: 380ms	remaining: 4.66s
225:	learn: 0.0892103	total: 568ms	remaining: 4.46s
300:	learn: 0.0796683	total: 765ms	remaining: 4.32s
375:	learn: 0.0728603	total: 961ms	remaining: 4.15s
450:	learn: 0.0667877	total: 1.13s	remaining: 3.88s
525:	learn: 0.0616128	total: 1.31s	remaining: 3.67s
600:	learn: 0.0572236	total: 1.49s	remaining: 3.46s
675:	learn: 0.0537512	total: 1.68s	remaining: 3.29s
750:	learn: 0.0508866	total: 1.87s	remaining: 3.11s
825:	learn: 0.0482036	total: 2.04s	remaining: 2.91s
900:	learn: 0.0456694	total: 2.2s	remaining: 2.69s
975:	learn: 0.0432232	total: 2.37s	remaining: 2.49s
1050:	learn: 0.0409133	total: 2.57s	remaining: 2.32s
1125:	learn: 0.0388421	total: 2.75s	remaining: 2.13s
1200:	learn: 0.0368583	total: 2.92s	remaining: 1.94s
1275:	learn: 0.0349464	total: 3.08s	remaining: 1.75s
1350:	learn: 0.0330698	total: 3.27s	remaining: 1.57s
1425:	learn: 0.0313707	total: 3.45s	remaining: 1.39s
1500:	learn: 0.0298813	total: 3.71s	remaining: 1.23s
1575:	learn: 0.0284178	total: 3.87s	remaining: 1.04s
1650:	learn: 0.0268592	total: 4.04s	remaining: 853ms
1725:	learn: 0.0255919	total: 4.18s	remaining: 664ms
1800:	learn: 0.0245308	total: 4.34s	remaining: 479ms
1875:	learn: 0.0234613	total: 4.48s	remaining: 296ms
1950:	learn: 0.0224489	total: 4.64s	remaining: 117ms
1999:	learn: 0.0218011	total: 4.75s	remaining: 0us
0:	learn: 0.3901847	total: 2.89ms	remaining: 5.79s
75:	learn: 0.1265730	total: 164ms	remaining: 4.16s
150:	learn: 0.1014347	total: 315ms	remaining: 3.86s
225:	learn: 0.0903780	total: 500ms	remaining: 3.92s
300:	learn: 0.0814868	total: 726ms	remaining: 4.1s
375:	learn: 0.0740472	total: 934ms	remaining: 4.03s
450:	learn: 0.0678385	total: 1.13s	remaining: 3.88s
525:	learn: 0.0626615	total: 1.33s	remaining: 3.72s
600:	learn: 0.0585409	total: 1.51s	remaining: 3.52s
675:	learn: 0.0544528	total: 1.72s	remaining: 3.36s
750:	learn: 0.0510753	total: 1.9s	remaining: 3.16s
825:	learn: 0.0481957	total: 2.08s	remaining: 2.95s
900:	learn: 0.0453891	total: 2.27s	remaining: 2.77s
975:	learn: 0.0432793	total: 2.46s	remaining: 2.58s
1050:	learn: 0.0407175	total: 2.63s	remaining: 2.37s
1125:	learn: 0.0384606	total: 2.82s	remaining: 2.19s
1200:	learn: 0.0363079	total: 3.01s	remaining: 2s
1275:	learn: 0.0344395	total: 3.19s	remaining: 1.81s
1350:	learn: 0.0325128	total: 3.37s	remaining: 1.62s
1425:	learn: 0.0307422	total: 3.55s	remaining: 1.43s
1500:	learn: 0.0290212	total: 3.74s	remaining: 1.24s
1575:	learn: 0.0278097	total: 3.92s	remaining: 1.05s
1650:	learn: 0.0263678	total: 4.11s	remaining: 868ms
1725:	learn: 0.0251141	total: 4.29s	remaining: 681ms
1800:	learn: 0.0239151	total: 4.47s	remaining: 494ms
1875:	learn: 0.0230269	total: 4.68s	remaining: 309ms
1950:	learn: 0.0219586	total: 4.87s	remaining: 122ms
1999:	learn: 0.0213244	total: 5s	remaining: 0us
0:	learn: 0.3935880	total: 3.32ms	remaining: 6.64s
75:	learn: 0.1346746	total: 181ms	remaining: 4.59s
150:	learn: 0.1066249	total: 366ms	remaining: 4.48s
225:	learn: 0.0930130	total: 548ms	remaining: 4.3s
300:	learn: 0.0838565	total: 720ms	remaining: 4.07s
375:	learn: 0.0760944	total: 889ms	remaining: 3.84s
450:	learn: 0.0698932	total: 1.06s	remaining: 3.65s
525:	learn: 0.0647792	total: 1.25s	remaining: 3.49s
600:	learn: 0.0601398	total: 1.44s	remaining: 3.34s
675:	learn: 0.0563864	total: 1.62s	remaining: 3.18s
750:	learn: 0.0527313	total: 1.82s	remaining: 3.02s
825:	learn: 0.0497759	total: 1.99s	remaining: 2.83s
900:	learn: 0.0468809	total: 2.18s	remaining: 2.66s
975:	learn: 0.0439456	total: 2.38s	remaining: 2.49s
1050:	learn: 0.0411413	total: 2.58s	remaining: 2.33s
1125:	learn: 0.0389086	total: 2.78s	remaining: 2.16s
1200:	learn: 0.0364707	total: 2.95s	remaining: 1.96s
1275:	learn: 0.0345833	total: 3.13s	remaining: 1.78s
1350:	learn: 0.0326648	total: 3.35s	remaining: 1.61s
1425:	learn: 0.0308105	total: 3.52s	remaining: 1.42s
1500:	learn: 0.0290651	total: 3.68s	remaining: 1.22s
1575:	learn: 0.0275493	total: 3.83s	remaining: 1.03s
1650:	learn: 0.0261586	total: 3.99s	remaining: 843ms
1725:	learn: 0.0248384	total: 4.14s	remaining: 657ms
1800:	learn: 0.0236143	total: 4.29s	remaining: 474ms
1875:	learn: 0.0224630	total: 4.43s	remaining: 293ms
1950:	learn: 0.0213628	total: 4.58s	remaining: 115ms
1999:	learn: 0.0206687	total: 4.68s	remaining: 0us
0:	learn: 0.3867541	total: 2.94ms	remaining: 5.88s
75:	learn: 0.1297882	total: 174ms	remaining: 4.41s
150:	learn: 0.1063776	total: 318ms	remaining: 3.9s
225:	learn: 0.0931513	total: 463ms	remaining: 3.64s
300:	learn: 0.0842001	total: 614ms	remaining: 3.46s
375:	learn: 0.0774687	total: 759ms	remaining: 3.28s
450:	learn: 0.0707138	total: 910ms	remaining: 3.12s
525:	learn: 0.0650302	total: 1.07s	remaining: 3s
600:	learn: 0.0604584	total: 1.23s	remaining: 2.86s
675:	learn: 0.0562214	total: 1.39s	remaining: 2.72s
750:	learn: 0.0521447	total: 1.55s	remaining: 2.57s
825:	learn: 0.0487096	total: 1.69s	remaining: 2.4s
900:	learn: 0.0456929	total: 1.85s	remaining: 2.26s
975:	learn: 0.0431787	total: 2.02s	remaining: 2.12s
1050:	learn: 0.0408641	total: 2.17s	remaining: 1.96s
1125:	learn: 0.0384706	total: 2.32s	remaining: 1.8s
1200:	learn: 0.0362095	total: 2.48s	remaining: 1.65s
1275:	learn: 0.0342079	total: 2.63s	remaining: 1.49s
1350:	learn: 0.0323871	total: 2.77s	remaining: 1.33s
1425:	learn: 0.0307896	total: 2.93s	remaining: 1.18s
1500:	learn: 0.0293179	total: 3.08s	remaining: 1.02s
1575:	learn: 0.0277616	total: 3.23s	remaining: 870ms
1650:	learn: 0.0263335	total: 3.4s	remaining: 719ms
1725:	learn: 0.0250790	total: 3.55s	remaining: 564ms
1800:	learn: 0.0239961	total: 3.7s	remaining: 409ms
1875:	learn: 0.0229011	total: 3.84s	remaining: 254ms
1950:	learn: 0.0217771	total: 4.01s	remaining: 101ms
1999:	learn: 0.0211012	total: 4.11s	remaining: 0us
0:	learn: 0.3886809	total: 2.11ms	remaining: 4.21s
75:	learn: 0.1311216	total: 170ms	remaining: 4.3s
150:	learn: 0.1042494	total: 318ms	remaining: 3.9s
225:	learn: 0.0910863	total: 473ms	remaining: 3.71s
300:	learn: 0.0823953	total: 625ms	remaining: 3.52s
375:	learn: 0.0751449	total: 786ms	remaining: 3.4s
450:	learn: 0.0694800	total: 937ms	remaining: 3.22s
525:	learn: 0.0645908	total: 1.08s	remaining: 3.03s
600:	learn: 0.0605962	total: 1.23s	remaining: 2.86s
675:	learn: 0.0565158	total: 1.38s	remaining: 2.69s
750:	learn: 0.0529432	total: 1.53s	remaining: 2.54s
825:	learn: 0.0494037	total: 1.68s	remaining: 2.38s
900:	learn: 0.0462777	total: 1.84s	remaining: 2.25s
975:	learn: 0.0435654	total: 1.99s	remaining: 2.09s
1050:	learn: 0.0410524	total: 2.18s	remaining: 1.97s
1125:	learn: 0.0388519	total: 2.33s	remaining: 1.81s
1200:	learn: 0.0363556	total: 2.48s	remaining: 1.65s
1275:	learn: 0.0340528	total: 2.64s	remaining: 1.5s
1350:	learn: 0.0322111	total: 2.79s	remaining: 1.34s
1425:	learn: 0.0304003	total: 2.94s	remaining: 1.18s
1500:	learn: 0.0288384	total: 3.13s	remaining: 1.04s
1575:	learn: 0.0273469	total: 3.3s	remaining: 887ms
1650:	learn: 0.0258522	total: 3.45s	remaining: 728ms
1725:	learn: 0.0245472	total: 3.59s	remaining: 570ms
1800:	learn: 0.0235077	total: 3.74s	remaining: 414ms
1875:	learn: 0.0223831	total: 3.9s	remaining: 258ms
1950:	learn: 0.0214374	total: 4.06s	remaining: 102ms
1999:	learn: 0.0208279	total: 4.16s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001089 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1587
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.020331

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003009 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1589
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 182
[LightGBM] [Info] Start training from score 12.022733

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002038 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1598
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 184
[LightGBM] [Info] Start training from score 12.030170

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002760 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1605
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 185
[LightGBM] [Info] Start training from score 12.013869

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001505 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1591
[LightGBM] [Info] Number of data points in the train set: 932, number of used features: 180
[LightGBM] [Info] Start training from score 12.034603

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3788043	total: 2.45ms	remaining: 4.89s
75:	learn: 0.1276875	total: 175ms	remaining: 4.44s
150:	learn: 0.1024401	total: 321ms	remaining: 3.93s
225:	learn: 0.0888873	total: 489ms	remaining: 3.84s
300:	learn: 0.0799474	total: 631ms	remaining: 3.56s
375:	learn: 0.0729584	total: 786ms	remaining: 3.4s
450:	learn: 0.0676452	total: 932ms	remaining: 3.2s
525:	learn: 0.0627979	total: 1.09s	remaining: 3.05s
600:	learn: 0.0583699	total: 1.25s	remaining: 2.9s
675:	learn: 0.0546039	total: 1.41s	remaining: 2.75s
750:	learn: 0.0516762	total: 1.55s	remaining: 2.57s
825:	learn: 0.0485023	total: 1.7s	remaining: 2.41s
900:	learn: 0.0456432	total: 1.84s	remaining: 2.24s
975:	learn: 0.0428116	total: 2s	remaining: 2.1s
1050:	learn: 0.0405010	total: 2.16s	remaining: 1.95s
1125:	learn: 0.0382167	total: 2.32s	remaining: 1.8s
1200:	learn: 0.0362526	total: 2.46s	remaining: 1.64s
1275:	learn: 0.0341860	total: 2.68s	remaining: 1.52s
1350:	learn: 0.0324944	total: 2.82s	remaining: 1.35s
1425:	learn: 0.0308983	total: 2.98s	remaining: 1.2s
1500:	learn: 0.0294517	total: 3.14s	remaining: 1.04s
1575:	learn: 0.0282424	total: 3.53s	remaining: 950ms
1650:	learn: 0.0268435	total: 4.05s	remaining: 856ms
1725:	learn: 0.0256962	total: 4.41s	remaining: 700ms
1800:	learn: 0.0243033	total: 4.67s	remaining: 516ms
1875:	learn: 0.0230554	total: 4.79s	remaining: 317ms
1950:	learn: 0.0220045	total: 4.9s	remaining: 123ms
1999:	learn: 0.0213469	total: 4.98s	remaining: 0us
0:	learn: 0.3889581	total: 1.61ms	remaining: 3.21s
75:	learn: 0.1255290	total: 131ms	remaining: 3.32s
150:	learn: 0.0990884	total: 246ms	remaining: 3.01s
225:	learn: 0.0861636	total: 335ms	remaining: 2.63s
300:	learn: 0.0778651	total: 432ms	remaining: 2.44s
375:	learn: 0.0711375	total: 524ms	remaining: 2.27s
450:	learn: 0.0659114	total: 640ms	remaining: 2.2s
525:	learn: 0.0612381	total: 735ms	remaining: 2.06s
600:	learn: 0.0573524	total: 860ms	remaining: 2s
675:	learn: 0.0538714	total: 959ms	remaining: 1.88s
750:	learn: 0.0508399	total: 1.05s	remaining: 1.74s
825:	learn: 0.0479295	total: 1.14s	remaining: 1.61s
900:	learn: 0.0451672	total: 1.23s	remaining: 1.5s
975:	learn: 0.0424330	total: 1.32s	remaining: 1.38s
1050:	learn: 0.0400882	total: 1.41s	remaining: 1.27s
1125:	learn: 0.0377098	total: 1.49s	remaining: 1.16s
1200:	learn: 0.0354153	total: 1.59s	remaining: 1.06s
1275:	learn: 0.0334310	total: 1.7s	remaining: 963ms
1350:	learn: 0.0316339	total: 1.8s	remaining: 864ms
1425:	learn: 0.0300175	total: 1.93s	remaining: 776ms
1500:	learn: 0.0283337	total: 2.03s	remaining: 676ms
1575:	learn: 0.0268010	total: 2.13s	remaining: 574ms
1650:	learn: 0.0254703	total: 2.24s	remaining: 473ms
1725:	learn: 0.0241840	total: 2.35s	remaining: 374ms
1800:	learn: 0.0228608	total: 2.46s	remaining: 271ms
1875:	learn: 0.0217548	total: 2.54s	remaining: 168ms
1950:	learn: 0.0207186	total: 2.63s	remaining: 66.1ms
1999:	learn: 0.0200377	total: 2.69s	remaining: 0us
0:	learn: 0.3896589	total: 1.58ms	remaining: 3.17s
75:	learn: 0.1294413	total: 112ms	remaining: 2.83s
150:	learn: 0.1055052	total: 224ms	remaining: 2.74s
225:	learn: 0.0920703	total: 314ms	remaining: 2.46s
300:	learn: 0.0841228	total: 404ms	remaining: 2.28s
375:	learn: 0.0774249	total: 496ms	remaining: 2.14s
450:	learn: 0.0723812	total: 623ms	remaining: 2.14s
525:	learn: 0.0672786	total: 754ms	remaining: 2.11s
600:	learn: 0.0625645	total: 861ms	remaining: 2s
675:	learn: 0.0583341	total: 966ms	remaining: 1.89s
750:	learn: 0.0548766	total: 1.07s	remaining: 1.79s
825:	learn: 0.0516666	total: 1.19s	remaining: 1.7s
900:	learn: 0.0489964	total: 1.31s	remaining: 1.6s
975:	learn: 0.0463460	total: 1.45s	remaining: 1.52s
1050:	learn: 0.0435936	total: 1.56s	remaining: 1.41s
1125:	learn: 0.0410878	total: 1.67s	remaining: 1.3s
1200:	learn: 0.0388086	total: 1.78s	remaining: 1.19s
1275:	learn: 0.0365910	total: 1.9s	remaining: 1.08s
1350:	learn: 0.0346083	total: 2.02s	remaining: 973ms
1425:	learn: 0.0327550	total: 2.15s	remaining: 867ms
1500:	learn: 0.0309622	total: 2.27s	remaining: 755ms
1575:	learn: 0.0293732	total: 2.39s	remaining: 642ms
1650:	learn: 0.0278121	total: 2.5s	remaining: 528ms
1725:	learn: 0.0263811	total: 2.61s	remaining: 414ms
1800:	learn: 0.0250888	total: 2.8s	remaining: 309ms
1875:	learn: 0.0241255	total: 2.91s	remaining: 193ms
1950:	learn: 0.0229904	total: 3.03s	remaining: 76.2ms
1999:	learn: 0.0223142	total: 3.11s	remaining: 0us
0:	learn: 0.3849681	total: 1.83ms	remaining: 3.65s
75:	learn: 0.1223199	total: 122ms	remaining: 3.09s
150:	learn: 0.0968919	total: 235ms	remaining: 2.88s
225:	learn: 0.0854947	total: 344ms	remaining: 2.7s
300:	learn: 0.0774296	total: 453ms	remaining: 2.55s
375:	learn: 0.0714271	total: 562ms	remaining: 2.42s
450:	learn: 0.0661693	total: 667ms	remaining: 2.29s
525:	learn: 0.0621506	total: 772ms	remaining: 2.16s
600:	learn: 0.0580306	total: 879ms	remaining: 2.04s
675:	learn: 0.0545948	total: 993ms	remaining: 1.94s
750:	learn: 0.0514902	total: 1.11s	remaining: 1.84s
825:	learn: 0.0486253	total: 1.22s	remaining: 1.73s
900:	learn: 0.0456743	total: 1.34s	remaining: 1.64s
975:	learn: 0.0431390	total: 1.45s	remaining: 1.52s
1050:	learn: 0.0407734	total: 1.56s	remaining: 1.41s
1125:	learn: 0.0383194	total: 1.67s	remaining: 1.3s
1200:	learn: 0.0361057	total: 1.8s	remaining: 1.2s
1275:	learn: 0.0341982	total: 1.9s	remaining: 1.08s
1350:	learn: 0.0326071	total: 2.01s	remaining: 965ms
1425:	learn: 0.0308071	total: 2.12s	remaining: 853ms
1500:	learn: 0.0294268	total: 2.23s	remaining: 742ms
1575:	learn: 0.0280835	total: 2.35s	remaining: 632ms
1650:	learn: 0.0270001	total: 2.46s	remaining: 520ms
1725:	learn: 0.0258601	total: 2.57s	remaining: 408ms
1800:	learn: 0.0248384	total: 2.68s	remaining: 297ms
1875:	learn: 0.0237468	total: 2.8s	remaining: 185ms
1950:	learn: 0.0225439	total: 2.92s	remaining: 73.3ms
1999:	learn: 0.0219954	total: 3.01s	remaining: 0us
0:	learn: 0.3871577	total: 2.76ms	remaining: 5.52s
75:	learn: 0.1296017	total: 116ms	remaining: 2.93s
150:	learn: 0.1045624	total: 230ms	remaining: 2.81s
225:	learn: 0.0930735	total: 348ms	remaining: 2.73s
300:	learn: 0.0850557	total: 470ms	remaining: 2.65s
375:	learn: 0.0784104	total: 588ms	remaining: 2.54s
450:	learn: 0.0728871	total: 697ms	remaining: 2.39s
525:	learn: 0.0676526	total: 814ms	remaining: 2.28s
600:	learn: 0.0629243	total: 927ms	remaining: 2.16s
675:	learn: 0.0587267	total: 1.04s	remaining: 2.04s
750:	learn: 0.0549645	total: 1.15s	remaining: 1.91s
825:	learn: 0.0513812	total: 1.28s	remaining: 1.82s
900:	learn: 0.0485007	total: 1.4s	remaining: 1.71s
975:	learn: 0.0458803	total: 1.54s	remaining: 1.61s
1050:	learn: 0.0433538	total: 1.65s	remaining: 1.49s
1125:	learn: 0.0408386	total: 1.76s	remaining: 1.36s
1200:	learn: 0.0385141	total: 1.86s	remaining: 1.24s
1275:	learn: 0.0364802	total: 1.97s	remaining: 1.12s
1350:	learn: 0.0346283	total: 2.08s	remaining: 998ms
1425:	learn: 0.0328288	total: 2.2s	remaining: 884ms
1500:	learn: 0.0310578	total: 2.31s	remaining: 768ms
1575:	learn: 0.0295724	total: 2.43s	remaining: 653ms
1650:	learn: 0.0280570	total: 2.54s	remaining: 538ms
1725:	learn: 0.0266968	total: 2.65s	remaining: 421ms
1800:	learn: 0.0254054	total: 2.76s	remaining: 305ms
1875:	learn: 0.0241453	total: 2.87s	remaining: 190ms
1950:	learn: 0.0228678	total: 2.98s	remaining: 74.9ms
1999:	learn: 0.0222021	total: 3.05s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
Stacking Averaged models score: 0.1156 (0.0134)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [116]:
def rmsle(y, y_pred):
    return np.sqrt(mean_squared_error(y, y_pred))

In [117]:
stacked_averaged_models.fit(train.values, y_train)
stacked_train_pred = stacked_averaged_models.predict(train.values)
stacked_pred = np.expm1(stacked_averaged_models.predict(test.values))
print(rmsle(y_train, stacked_train_pred))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001348 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1643
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 189
[LightGBM] [Info] Start training from score 12.028248

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000856 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1639
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 187
[LightGBM] [Info] Start training from score 12.022875

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000969 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1638
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 188
[LightGBM] [Info] Start training from score 12.021521

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001268 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1639
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 190
[LightGBM] [Info] Start training from score 12.021395

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000843 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1629
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 185
[LightGBM] [Info] Start training from score 12.035611

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3841874	total: 1.72ms	remaining: 3.43s
75:	learn: 0.1325050	total: 125ms	remaining: 3.15s
150:	learn: 0.1068643	total: 239ms	remaining: 2.92s
225:	learn: 0.0938399	total: 350ms	remaining: 2.75s
300:	learn: 0.0858683	total: 460ms	remaining: 2.6s
375:	learn: 0.0796624	total: 569ms	remaining: 2.46s
450:	learn: 0.0745751	total: 677ms	remaining: 2.33s
525:	learn: 0.0700969	total: 786ms	remaining: 2.2s
600:	learn: 0.0657365	total: 895ms	remaining: 2.08s
675:	learn: 0.0619249	total: 1s	remaining: 1.97s
750:	learn: 0.0587963	total: 1.11s	remaining: 1.85s
825:	learn: 0.0556860	total: 1.23s	remaining: 1.75s
900:	learn: 0.0527038	total: 1.34s	remaining: 1.64s
975:	learn: 0.0500187	total: 1.45s	remaining: 1.52s
1050:	learn: 0.0476752	total: 1.56s	remaining: 1.41s
1125:	learn: 0.0456366	total: 1.69s	remaining: 1.31s
1200:	learn: 0.0436302	total: 1.81s	remaining: 1.2s
1275:	learn: 0.0414277	total: 1.92s	remaining: 1.09s
1350:	learn: 0.0397517	total: 2.03s	remaining: 974ms
1425:	learn: 0.0379978	total: 2.13s	remaining: 859ms
1500:	learn: 0.0364654	total: 2.24s	remaining: 746ms
1575:	learn: 0.0348859	total: 2.35s	remaining: 633ms
1650:	learn: 0.0335379	total: 2.46s	remaining: 521ms
1725:	learn: 0.0321869	total: 2.58s	remaining: 410ms
1800:	learn: 0.0309045	total: 2.69s	remaining: 298ms
1875:	learn: 0.0298658	total: 2.8s	remaining: 185ms
1950:	learn: 0.0287796	total: 2.91s	remaining: 73.1ms
1999:	learn: 0.0281033	total: 2.98s	remaining: 0us
0:	learn: 0.3824759	total: 1.73ms	remaining: 3.46s
75:	learn: 0.1282991	total: 121ms	remaining: 3.05s
150:	learn: 0.1019108	total: 234ms	remaining: 2.86s
225:	learn: 0.0900067	total: 344ms	remaining: 2.7s
300:	learn: 0.0820388	total: 457ms	remaining: 2.58s
375:	learn: 0.0756237	total: 579ms	remaining: 2.5s
450:	learn: 0.0706066	total: 689ms	remaining: 2.37s
525:	learn: 0.0662469	total: 801ms	remaining: 2.24s
600:	learn: 0.0625493	total: 919ms	remaining: 2.14s
675:	learn: 0.0590747	total: 1.04s	remaining: 2.03s
750:	learn: 0.0558878	total: 1.15s	remaining: 1.91s
825:	learn: 0.0527969	total: 1.26s	remaining: 1.79s
900:	learn: 0.0502905	total: 1.37s	remaining: 1.67s
975:	learn: 0.0480139	total: 1.48s	remaining: 1.56s
1050:	learn: 0.0456982	total: 1.6s	remaining: 1.44s
1125:	learn: 0.0435457	total: 1.72s	remaining: 1.34s
1200:	learn: 0.0414132	total: 1.84s	remaining: 1.22s
1275:	learn: 0.0394293	total: 1.95s	remaining: 1.1s
1350:	learn: 0.0379974	total: 2.1s	remaining: 1.01s
1425:	learn: 0.0364962	total: 2.21s	remaining: 892ms
1500:	learn: 0.0350207	total: 2.33s	remaining: 774ms
1575:	learn: 0.0335597	total: 2.45s	remaining: 659ms
1650:	learn: 0.0321871	total: 2.58s	remaining: 545ms
1725:	learn: 0.0309488	total: 2.72s	remaining: 432ms
1800:	learn: 0.0297875	total: 2.86s	remaining: 316ms
1875:	learn: 0.0286434	total: 3s	remaining: 198ms
1950:	learn: 0.0273920	total: 3.11s	remaining: 78.2ms
1999:	learn: 0.0266435	total: 3.2s	remaining: 0us
0:	learn: 0.3849148	total: 1.76ms	remaining: 3.52s
75:	learn: 0.1303493	total: 122ms	remaining: 3.08s
150:	learn: 0.1050019	total: 237ms	remaining: 2.9s
225:	learn: 0.0942976	total: 354ms	remaining: 2.78s
300:	learn: 0.0858397	total: 473ms	remaining: 2.67s
375:	learn: 0.0791724	total: 596ms	remaining: 2.57s
450:	learn: 0.0732365	total: 726ms	remaining: 2.5s
525:	learn: 0.0681947	total: 853ms	remaining: 2.39s
600:	learn: 0.0639884	total: 980ms	remaining: 2.28s
675:	learn: 0.0598836	total: 1.1s	remaining: 2.15s
750:	learn: 0.0564013	total: 1.22s	remaining: 2.04s
825:	learn: 0.0534873	total: 1.36s	remaining: 1.94s
900:	learn: 0.0505734	total: 1.48s	remaining: 1.81s
975:	learn: 0.0484502	total: 1.62s	remaining: 1.7s
1050:	learn: 0.0459729	total: 1.75s	remaining: 1.58s
1125:	learn: 0.0437155	total: 1.86s	remaining: 1.45s
1200:	learn: 0.0417214	total: 1.98s	remaining: 1.32s
1275:	learn: 0.0398798	total: 2.1s	remaining: 1.19s
1350:	learn: 0.0380981	total: 2.21s	remaining: 1.06s
1425:	learn: 0.0367477	total: 2.33s	remaining: 937ms
1500:	learn: 0.0351232	total: 2.44s	remaining: 813ms
1575:	learn: 0.0335599	total: 2.56s	remaining: 689ms
1650:	learn: 0.0322637	total: 2.68s	remaining: 566ms
1725:	learn: 0.0310800	total: 2.81s	remaining: 446ms
1800:	learn: 0.0297883	total: 2.93s	remaining: 324ms
1875:	learn: 0.0285048	total: 3.05s	remaining: 202ms
1950:	learn: 0.0273146	total: 3.17s	remaining: 79.5ms
1999:	learn: 0.0266480	total: 3.24s	remaining: 0us
0:	learn: 0.3864333	total: 1.76ms	remaining: 3.51s
75:	learn: 0.1312401	total: 128ms	remaining: 3.23s
150:	learn: 0.1080843	total: 239ms	remaining: 2.93s
225:	learn: 0.0962385	total: 351ms	remaining: 2.75s
300:	learn: 0.0888665	total: 469ms	remaining: 2.65s
375:	learn: 0.0821263	total: 599ms	remaining: 2.59s
450:	learn: 0.0761140	total: 722ms	remaining: 2.48s
525:	learn: 0.0709571	total: 839ms	remaining: 2.35s
600:	learn: 0.0667133	total: 959ms	remaining: 2.23s
675:	learn: 0.0627888	total: 1.09s	remaining: 2.14s
750:	learn: 0.0589295	total: 1.21s	remaining: 2.02s
825:	learn: 0.0555675	total: 1.33s	remaining: 1.89s
900:	learn: 0.0525630	total: 1.44s	remaining: 1.76s
975:	learn: 0.0497735	total: 1.56s	remaining: 1.64s
1050:	learn: 0.0469476	total: 1.68s	remaining: 1.52s
1125:	learn: 0.0446013	total: 1.81s	remaining: 1.41s
1200:	learn: 0.0423157	total: 1.95s	remaining: 1.3s
1275:	learn: 0.0402635	total: 2.07s	remaining: 1.17s
1350:	learn: 0.0383643	total: 2.19s	remaining: 1.05s
1425:	learn: 0.0364421	total: 2.3s	remaining: 927ms
1500:	learn: 0.0347386	total: 2.42s	remaining: 805ms
1575:	learn: 0.0331332	total: 2.54s	remaining: 683ms
1650:	learn: 0.0316903	total: 2.67s	remaining: 564ms
1725:	learn: 0.0303619	total: 2.8s	remaining: 445ms
1800:	learn: 0.0291683	total: 2.93s	remaining: 323ms
1875:	learn: 0.0278762	total: 3.05s	remaining: 202ms
1950:	learn: 0.0266586	total: 3.17s	remaining: 79.6ms
1999:	learn: 0.0259820	total: 3.24s	remaining: 0us
0:	learn: 0.3835841	total: 1.78ms	remaining: 3.57s
75:	learn: 0.1252940	total: 114ms	remaining: 2.89s
150:	learn: 0.1023354	total: 229ms	remaining: 2.8s
225:	learn: 0.0912359	total: 344ms	remaining: 2.7s
300:	learn: 0.0832148	total: 468ms	remaining: 2.64s
375:	learn: 0.0769440	total: 602ms	remaining: 2.6s
450:	learn: 0.0721222	total: 744ms	remaining: 2.56s
525:	learn: 0.0672205	total: 878ms	remaining: 2.46s
600:	learn: 0.0637279	total: 998ms	remaining: 2.32s
675:	learn: 0.0599742	total: 1.11s	remaining: 2.18s
750:	learn: 0.0567018	total: 1.23s	remaining: 2.04s
825:	learn: 0.0538749	total: 1.34s	remaining: 1.91s
900:	learn: 0.0509977	total: 1.46s	remaining: 1.78s
975:	learn: 0.0485765	total: 1.58s	remaining: 1.66s
1050:	learn: 0.0461732	total: 1.72s	remaining: 1.55s
1125:	learn: 0.0441608	total: 1.84s	remaining: 1.43s
1200:	learn: 0.0421905	total: 1.96s	remaining: 1.3s
1275:	learn: 0.0401702	total: 2.08s	remaining: 1.18s
1350:	learn: 0.0381667	total: 2.19s	remaining: 1.05s
1425:	learn: 0.0364497	total: 2.31s	remaining: 929ms
1500:	learn: 0.0349914	total: 2.43s	remaining: 809ms
1575:	learn: 0.0334309	total: 2.56s	remaining: 689ms
1650:	learn: 0.0319209	total: 2.7s	remaining: 571ms
1725:	learn: 0.0303729	total: 2.89s	remaining: 459ms
1800:	learn: 0.0290845	total: 3.05s	remaining: 337ms
1875:	learn: 0.0278343	total: 3.21s	remaining: 212ms
1950:	learn: 0.0266503	total: 3.34s	remaining: 83.9ms
1999:	learn: 0.0258222	total: 3.42s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0.07242350035456925

In [118]:
model_xgb.fit(train, y_train)
xgb_train_pred = model_xgb.predict(train)
xgb_pred = np.expm1(model_xgb.predict(test))
print(rmsle(y_train, xgb_train_pred))

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [12:33:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

0.0847060254313097

In [119]:
model_lgb.fit(train, y_train)
lgb_train_pred = model_lgb.predict(train)
lgb_pred = np.expm1(model_lgb.predict(test.values))
print(rmsle(y_train, lgb_train_pred))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001970 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1669
[LightGBM] [Info] Number of data points in the train set: 1455, number of used features: 192
[LightGBM] [Info] Start training from score 12.025930
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0.07095204549177013

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [120]:
ENet.fit(train, y_train)
ENet_train_pred = ENet.predict(train)
ENet_pred = np.expm1(ENet.predict(test.values))
print(rmsle(y_train, ENet_train_pred))

0.1089992627933918

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(

In [121]:
model_cat.fit(train, y_train)
cat_train_pred = model_cat.predict(train)
cat_pred = np.expm1(model_cat.predict(test.values))
print(rmsle(y_train, cat_train_pred))

0:	learn: 0.3851186	total: 2.24ms	remaining: 4.48s
75:	learn: 0.1307489	total: 121ms	remaining: 3.07s
150:	learn: 0.1073968	total: 238ms	remaining: 2.92s
225:	learn: 0.0955584	total: 367ms	remaining: 2.88s
300:	learn: 0.0884731	total: 484ms	remaining: 2.73s
375:	learn: 0.0824081	total: 598ms	remaining: 2.58s
450:	learn: 0.0771140	total: 713ms	remaining: 2.45s
525:	learn: 0.0723772	total: 850ms	remaining: 2.38s
600:	learn: 0.0684970	total: 984ms	remaining: 2.29s
675:	learn: 0.0648397	total: 1.1s	remaining: 2.16s
750:	learn: 0.0614244	total: 1.24s	remaining: 2.07s
825:	learn: 0.0584835	total: 1.4s	remaining: 1.99s
900:	learn: 0.0555042	total: 1.53s	remaining: 1.87s
975:	learn: 0.0528329	total: 1.66s	remaining: 1.74s
1050:	learn: 0.0504757	total: 1.79s	remaining: 1.62s
1125:	learn: 0.0482462	total: 1.93s	remaining: 1.5s
1200:	learn: 0.0462874	total: 2.1s	remaining: 1.39s
1275:	learn: 0.0444161	total: 2.23s	remaining: 1.27s
1350:	learn: 0.0425494	total: 2.35s	remaining: 1.13s
1425:	learn: 0.0408891	total: 2.48s	remaining: 999ms
1500:	learn: 0.0394353	total: 2.66s	remaining: 886ms
1575:	learn: 0.0379053	total: 2.77s	remaining: 745ms
1650:	learn: 0.0366126	total: 2.88s	remaining: 608ms
1725:	learn: 0.0351470	total: 3s	remaining: 475ms
1800:	learn: 0.0338742	total: 3.12s	remaining: 344ms
1875:	learn: 0.0326245	total: 3.23s	remaining: 214ms
1950:	learn: 0.0315594	total: 3.37s	remaining: 84.7ms
1999:	learn: 0.0308169	total: 3.46s	remaining: 0us
0.030816916966032438

In [122]:
print('RMSLE score on train data:')
print(rmsle(y_train,stacked_train_pred*0.70 +
               cat_train_pred*0.15 + ENet_train_pred*0.15 ))

RMSLE score on train data:
0.07012420897158257

In [123]:
ensemble = stacked_pred*0.70 + cat_pred*0.15 + lgb_pred*0.15

In [124]:
sub = pd.DataFrame()
sub['Id'] = test_ID
sub['SalePrice'] = ensemble
sub.to_csv('submission.csv',index=False)