In [1]:

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

from scipy import stats
from scipy.stats import norm, skew

In [2]:
train_path = '../../../data/raw/train.csv'
test_path = '../../../data/raw/test.csv'

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [3]:
train_ID = train['Id']
test_ID = test['Id']

#Now drop the  'Id' colum since it's unnecessary for  the prediction process.
train.drop("Id", axis = 1, inplace = True)
test.drop("Id", axis = 1, inplace = True)

In [4]:
# train = train.drop(train[(train['GrLivArea'] > 4000) & (train['SalePrice'] < 300000)].index)
train=train.drop(train[(train["LotArea"] >100000)].index)
train=train.drop(train[(train['LotFrontage']>300)].index)
train["SalePrice"] = np.log1p(train["SalePrice"])

In [5]:
train = train.drop(['Heating','RoofMatl','Condition2','Street','Utilities'],axis=1)
test = test.drop(['Heating','RoofMatl','Condition2','Street','Utilities'],axis=1)

In [6]:
ntrain = train.shape[0]
ntest = test.shape[0]
y_train = train.SalePrice.values
all_data = pd.concat((train, test)).reset_index(drop=True)
all_data.drop(['SalePrice'], axis=1, inplace=True)
print("all_data size is : {}".format(all_data.shape))

all_data size is : (2913, 74)

In [7]:
all_data["FireplaceQu"] = all_data["FireplaceQu"].fillna("None")
all_data['PoolQC']=all_data['PoolQC'].fillna('None')
all_data["MiscFeature"] = all_data["MiscFeature"].fillna("None")
all_data["Alley"] = all_data["Alley"].fillna("None")
all_data["MasVnrType"] = all_data["MasVnrType"].fillna("None")
all_data["Fence"] = all_data["Fence"].fillna("None")
all_data["LotFrontage"] = all_data.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median()))
all_data['GarageYrBlt'] = all_data['GarageYrBlt'].fillna(all_data['YrSold']-35)

for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    all_data[col] = all_data[col].fillna('None')
for col in ( 'GarageArea', 'GarageCars'):
    all_data[col] = all_data[col].fillna(0)
for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF','TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath'):
    all_data[col] = all_data[col].fillna(0)
for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):
    all_data[col] = all_data[col].fillna('None')
all_data["MasVnrArea"] = all_data["MasVnrArea"].fillna(0)
all_data['MSZoning'] = all_data['MSZoning'].fillna(all_data['MSZoning'].mode()[0])
all_data["Functional"] = all_data["Functional"].fillna("Typ")
all_data['Electrical'] = all_data['Electrical'].fillna(all_data['Electrical'].mode()[0])
all_data['KitchenQual'] = all_data['KitchenQual'].fillna(all_data['KitchenQual'].mode()[0])
all_data['Exterior1st'] = all_data['Exterior1st'].fillna(all_data['Exterior1st'].mode()[0])
all_data['Exterior2nd'] = all_data['Exterior2nd'].fillna(all_data['Exterior2nd'].mode()[0])
all_data['SaleType'] = all_data['SaleType'].fillna(all_data['SaleType'].mode()[0])
all_data['MSSubClass'] = all_data['MSSubClass'].fillna("None")

In [8]:
#Check remaining missing values if any 
all_data_na = (all_data.isnull().sum() / len(all_data)) * 100
all_data_na = all_data_na.drop(all_data_na[all_data_na == 0].index).sort_values(ascending=False)
missing_data = pd.DataFrame({'Missing Ratio' :all_data_na})
missing_data.head()

Empty DataFrame
Columns: [Missing Ratio]
Index: []

In [9]:
all_data['TotalSF'] = all_data['TotalBsmtSF'] + all_data['1stFlrSF'] + all_data['2ndFlrSF']
all_data["HouseAge"] = all_data["YrSold"] - all_data["YearBuilt"]
all_data["QualCond"] = all_data["OverallQual"]*all_data["OverallCond"]
all_data['TotalBsmtBath'] = all_data['BsmtFullBath'] + all_data['BsmtFullBath']*0.5
all_data['TotalBath'] = all_data['FullBath'] + all_data['HalfBath']*0.5

In [10]:


all_data['HasBasement'] = (
    all_data['BsmtQual'] != 'None'
).map({True: 1, False: 0})



all_data['IsHomeNew'] = (
    all_data['SaleType'] == 'New'
).map({True: 1, False: 0})



all_data['HasGarage'] = all_data['GarageFinish'] != 'None'
all_data['HasGarage'] = all_data['HasGarage'].map({True: 1, False: 0})



all_data['HasSecondGarage'] = all_data['MiscFeature'] == 'Gar2'
all_data['HasSecondGarage'] = all_data['HasSecondGarage'].map({True: 1, False: 0})



all_data['MultipleExteriorMaterials'] = (
    (all_data['Exterior1st'] != all_data['Exterior2nd']).astype(int)
)

all_data['HasMasonryVeneer'] = (all_data['MasVnrType'] != 'None').astype(int)

In [11]:
#MSSubClass=The building class
all_data['MSSubClass'] = all_data['MSSubClass'].apply(str)


#Changing OverallCond into a categorical variable
all_data['OverallCond'] = all_data['OverallCond'].astype(str)


#Year and month sold are transformed into categorical features.
all_data['YrSold'] = all_data['YrSold'].astype(str)
all_data['MoSold'] = all_data['MoSold'].astype(str)

In [12]:
from sklearn.preprocessing import LabelEncoder
cols = ('FireplaceQu', 'BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond', 
        'ExterQual', 'ExterCond','HeatingQC', 'KitchenQual', 'BsmtFinType1', 
        'BsmtFinType2', 'Functional',  'BsmtExposure', 'GarageFinish', 'LandSlope',
        'LotShape', 'PavedDrive',  'CentralAir', 'MSSubClass', 'OverallCond', 
        'YrSold', 'MoSold')
# process columns, apply LabelEncoder to categorical features
for c in cols:
    lbl = LabelEncoder() 
    lbl.fit(list(all_data[c].values)) 
    all_data[c] = lbl.transform(list(all_data[c].values))

# shape        
print('Shape all_data: {}'.format(all_data.shape))

Shape all_data: (2913, 85)

In [13]:
numeric_feats = all_data.dtypes[all_data.dtypes != "object"].index

# Check the skew of all numerical features
skewed_feats = all_data[numeric_feats].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
print("\nSkew in numerical features: \n")
skewness = pd.DataFrame({'Skew' :skewed_feats})
skewness.head(10)

Skew in numerical features:

                      Skew
HasSecondGarage  24.074919
MiscVal          21.947774
PoolArea         17.676417
LowQualFinSF     12.076090
3SsnPorch        11.364106
LandSlope         4.977652
KitchenAbvGr      4.297140
BsmtFinSF2        4.159265
EnclosedPorch     3.999248
ScreenPorch       3.941914

In [14]:
skewness = skewness[abs(skewness) > 0.75]
print("There are {} skewed numerical features to Box Cox transform".format(skewness.shape[0]))

from scipy.special import boxcox1p
skewed_features = skewness.index
lam = 0.15
for feat in skewed_features:
    #all_data[feat] += 1
    all_data[feat] = boxcox1p(all_data[feat], lam)
    
#all_data[skewed_features] = np.log1p(all_data[skewed_features])

There are 65 skewed numerical features to Box Cox transform

In [15]:
all_data = pd.get_dummies(all_data)
print(all_data.shape)

(2913, 217)

In [16]:
train = all_data[:ntrain]
test = all_data[ntrain:]

In [17]:
import pandas as pd
# Giả sử df là DataFrame của bạn

# Kiểm tra tổng số NaN cho mỗi cột
nan_counts = train.isnull().sum()

# Lọc và chỉ hiển thị các cột có NaN > 0
columns_with_nan = nan_counts[nan_counts > 0].sort_values(ascending=False)

print("Tổng số giá trị NaN trên mỗi cột:")
print(columns_with_nan)

Tổng số giá trị NaN trên mỗi cột:
Series([], dtype: int64)

In [18]:
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb
import catboost as cb

In [19]:
# import numpy as np
# import optuna
# from optuna.samplers import TPESampler
# from sklearn.model_selection import KFold, cross_val_score
# from sklearn.linear_model import Ridge, ElasticNet
# from sklearn.kernel_ridge import KernelRidge
# from lightgbm import LGBMRegressor
# from xgboost import XGBRegressor

# # Số lần gập (cross validation)
# n_folds = 5
# kf = KFold(n_splits=n_folds, shuffle=True, random_state=42)

# # ----- Các hàm objective cho từng mô hình -----
# objectives = {}

# def objective_lgbm(trial):
#     params = {
#         "n_estimators": 1000,
#         "random_state": 42,
#         "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
#         "num_leaves": trial.suggest_int("num_leaves", 20, 300),
#         "max_depth": trial.suggest_int("max_depth", -1, 15),
#         "subsample": trial.suggest_float("subsample", 0.5, 1.0),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
#         "reg_alpha": trial.suggest_float("reg_alpha", 1e-4, 10.0, log=True),
#         "reg_lambda": trial.suggest_float("reg_lambda", 1e-4, 10.0, log=True),
#         "verbose": -1
#     }
#     model = LGBMRegressor(**params)
#     score = -cross_val_score(model, train, y_train, cv=kf, scoring="neg_root_mean_squared_error").mean()
#     return score
# objectives["LightGBM"] = objective_lgbm

# def objective_ridge(trial):
#     alpha = trial.suggest_float("alpha", 1e-3, 100.0, log=True)
#     model = Ridge(alpha=alpha, random_state=132)
#     score = -cross_val_score(model, train, y_train, cv=kf, scoring="neg_root_mean_squared_error").mean()
#     return score
# objectives["Ridge"] = objective_ridge

# def objective_elastic(trial):
#     alpha = trial.suggest_float("alpha", 1e-4, 1.0, log=True)
#     l1_ratio = trial.suggest_float("l1_ratio", 0.1, 1.0)
#     model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=132, max_iter=20000)
#     score = -cross_val_score(model, train, y_train, cv=kf, scoring="neg_root_mean_squared_error").mean()
#     return score
# objectives["ElasticNet"] = objective_elastic

# def objective_krr(trial):
#     alpha = trial.suggest_float("alpha", 1e-3, 10.0, log=True)
#     kernel = trial.suggest_categorical("kernel", ["linear", "polynomial", "rbf"])
#     if kernel == "polynomial":
#         degree = trial.suggest_int("degree", 2, 5)
#         coef0 = trial.suggest_float("coef0", 0.0, 5.0)
#         model = KernelRidge(alpha=alpha, kernel=kernel, degree=degree, coef0=coef0)
#     else:
#         model = KernelRidge(alpha=alpha, kernel=kernel)
#     score = -cross_val_score(model, train, y_train, cv=kf, scoring="neg_root_mean_squared_error").mean()
#     return score
# objectives["KernelRidge"] = objective_krr

# def objective_xgb(trial):
#     params = {
#         "objective": "reg:squarederror",
#         "tree_method": "hist",
#         "n_estimators": 1000,
#         "random_state": 42,
#         "max_depth": trial.suggest_int("max_depth", 3, 10),
#         "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
#         "subsample": trial.suggest_float("subsample", 0.5, 1.0),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
#         "reg_alpha": trial.suggest_float("reg_alpha", 1e-4, 10.0, log=True),
#         "reg_lambda": trial.suggest_float("reg_lambda", 1e-4, 10.0, log=True),
#     }
#     model = XGBRegressor(**params)
#     score = -cross_val_score(model, train, y_train, cv=kf, scoring="neg_root_mean_squared_error").mean()
#     return score
# objectives["XGBoost"] = objective_xgb

# # ----- Chạy tối ưu bằng Optuna -----
# best_results = {}

# for name, objective_func in objectives.items():
#     print(f"\n🔍 Đang tối ưu mô hình: {name}")
#     study = optuna.create_study(
#         direction="minimize",
#         sampler=TPESampler(seed=42),
#         study_name=name
#     )
#     study.optimize(objective_func, n_trials=5, show_progress_bar=True)

#     print(f"✅ Mô hình {name} hoàn thành!")
#     print(f"👉 Best RMSE: {study.best_value:.5f}")
#     print(f"👉 Best Params: {study.best_params}")

#     best_results[name] = {
#         "best_score": study.best_value,
#         "best_params": study.best_params
#     }

# # ----- Tổng hợp kết quả -----
# print("\n📊 Tổng hợp kết quả:")
# for model, result in best_results.items():
#     print(f"{model}: RMSE={result['best_score']:.5f}")

# best_model_name = min(best_results, key=lambda m: best_results[m]["best_score"])
# print(f"\n🏆 Mô hình tốt nhất: {best_model_name}")
# print(f"RMSE = {best_results[best_model_name]['best_score']:.5f}")
# print("Thông số tối ưu:", best_results[best_model_name]["best_params"])

In [20]:
n_folds = 5

def rmsle_cv(model):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(train.values)
    rmse= np.sqrt(-cross_val_score(model, train.values, y_train, scoring="neg_mean_squared_error", cv = kf))
    return(rmse)

In [21]:
lasso = make_pipeline(RobustScaler(), Lasso(alpha =0.0005, random_state=1))
ENet = make_pipeline(RobustScaler(), ElasticNet(alpha=0.0005, l1_ratio=.9, random_state=3))
KRR = KernelRidge(alpha=0.6, kernel='polynomial', degree=2, coef0=2.5)
GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
model_xgb = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)
model_lgb = lgb.LGBMRegressor(objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=720,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)
model_cat = cb.CatBoostRegressor(iterations=2000, learning_rate=0.05, depth=4,
                                 eval_metric='RMSE', random_seed =42, bagging_temperature = 0.2,
                                 od_type='Iter', metric_period = 75, od_wait=100)

In [22]:
score = rmsle_cv(lasso)
print("\nLasso score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Lasso score: 0.1170 (0.0123)

In [23]:
score = rmsle_cv(ENet)
print("\nEnet score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Enet score: 0.1171 (0.0124)

In [24]:

score = rmsle_cv(KRR)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

KRR score: 0.1220 (0.0140)

In [25]:

score = rmsle_cv(GBoost)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

KRR score: 0.1195 (0.0167)

In [26]:
score = rmsle_cv(model_xgb)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [11:38:31] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [11:38:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [11:38:33] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [11:38:35] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [11:38:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

KRR score: 0.1205 (0.0119)

In [27]:
score = rmsle_cv(model_lgb)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002394 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1539
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 182
[LightGBM] [Info] Start training from score 12.019632

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003124 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1550
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 184
[LightGBM] [Info] Start training from score 12.022246

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002589 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1539
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 182
[LightGBM] [Info] Start training from score 12.019036

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002649 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1554
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 184
[LightGBM] [Info] Start training from score 12.030618

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000963 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1542
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 183
[LightGBM] [Info] Start training from score 12.019949
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

KRR score: 0.1203 (0.0139)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [28]:
score = rmsle_cv(model_cat)
print("\nKRR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

0:	learn: 0.3903336	total: 172ms	remaining: 5m 42s
75:	learn: 0.1318063	total: 365ms	remaining: 9.23s
150:	learn: 0.1089452	total: 534ms	remaining: 6.54s
225:	learn: 0.0968738	total: 699ms	remaining: 5.48s
300:	learn: 0.0886320	total: 857ms	remaining: 4.84s
375:	learn: 0.0821777	total: 1.01s	remaining: 4.35s
450:	learn: 0.0771170	total: 1.17s	remaining: 4.01s
525:	learn: 0.0715888	total: 1.38s	remaining: 3.87s
600:	learn: 0.0671837	total: 1.57s	remaining: 3.66s
675:	learn: 0.0632406	total: 1.75s	remaining: 3.44s
750:	learn: 0.0598644	total: 2s	remaining: 3.32s
825:	learn: 0.0564384	total: 2.16s	remaining: 3.07s
900:	learn: 0.0533364	total: 2.33s	remaining: 2.85s
975:	learn: 0.0504999	total: 2.52s	remaining: 2.64s
1050:	learn: 0.0481557	total: 2.68s	remaining: 2.42s
1125:	learn: 0.0456028	total: 2.85s	remaining: 2.21s
1200:	learn: 0.0434779	total: 3.02s	remaining: 2.01s
1275:	learn: 0.0416634	total: 3.22s	remaining: 1.83s
1350:	learn: 0.0398286	total: 3.44s	remaining: 1.65s
1425:	learn: 0.0379485	total: 3.67s	remaining: 1.48s
1500:	learn: 0.0362219	total: 3.89s	remaining: 1.29s
1575:	learn: 0.0346518	total: 4.14s	remaining: 1.11s
1650:	learn: 0.0332021	total: 4.39s	remaining: 928ms
1725:	learn: 0.0319612	total: 4.62s	remaining: 734ms
1800:	learn: 0.0307338	total: 4.84s	remaining: 535ms
1875:	learn: 0.0294636	total: 5.1s	remaining: 337ms
1950:	learn: 0.0282507	total: 5.33s	remaining: 134ms
1999:	learn: 0.0275223	total: 5.48s	remaining: 0us
0:	learn: 0.3794933	total: 5.33ms	remaining: 10.7s
75:	learn: 0.1238816	total: 242ms	remaining: 6.13s
150:	learn: 0.1008531	total: 509ms	remaining: 6.23s
225:	learn: 0.0904449	total: 752ms	remaining: 5.91s
300:	learn: 0.0832352	total: 990ms	remaining: 5.59s
375:	learn: 0.0770592	total: 1.19s	remaining: 5.13s
450:	learn: 0.0724820	total: 1.37s	remaining: 4.72s
525:	learn: 0.0684937	total: 1.6s	remaining: 4.49s
600:	learn: 0.0641690	total: 1.83s	remaining: 4.27s
675:	learn: 0.0602022	total: 2.07s	remaining: 4.05s
750:	learn: 0.0571032	total: 2.31s	remaining: 3.84s
825:	learn: 0.0539333	total: 2.56s	remaining: 3.63s
900:	learn: 0.0512490	total: 2.79s	remaining: 3.4s
975:	learn: 0.0489364	total: 3.01s	remaining: 3.16s
1050:	learn: 0.0466126	total: 3.25s	remaining: 2.94s
1125:	learn: 0.0442171	total: 3.52s	remaining: 2.73s
1200:	learn: 0.0423151	total: 3.75s	remaining: 2.5s
1275:	learn: 0.0402283	total: 3.93s	remaining: 2.23s
1350:	learn: 0.0383734	total: 4.14s	remaining: 1.99s
1425:	learn: 0.0367087	total: 4.34s	remaining: 1.75s
1500:	learn: 0.0351318	total: 4.55s	remaining: 1.51s
1575:	learn: 0.0337620	total: 4.73s	remaining: 1.27s
1650:	learn: 0.0323280	total: 4.93s	remaining: 1.04s
1725:	learn: 0.0309662	total: 5.17s	remaining: 821ms
1800:	learn: 0.0297058	total: 5.4s	remaining: 597ms
1875:	learn: 0.0286152	total: 5.63s	remaining: 372ms
1950:	learn: 0.0274549	total: 5.94s	remaining: 149ms
1999:	learn: 0.0267448	total: 6.09s	remaining: 0us
0:	learn: 0.3830375	total: 4.52ms	remaining: 9.04s
75:	learn: 0.1276382	total: 248ms	remaining: 6.27s
150:	learn: 0.1036298	total: 413ms	remaining: 5.05s
225:	learn: 0.0915664	total: 592ms	remaining: 4.65s
300:	learn: 0.0830051	total: 801ms	remaining: 4.52s
375:	learn: 0.0762551	total: 1.04s	remaining: 4.5s
450:	learn: 0.0709330	total: 1.29s	remaining: 4.42s
525:	learn: 0.0662381	total: 1.49s	remaining: 4.18s
600:	learn: 0.0618611	total: 1.74s	remaining: 4.05s
675:	learn: 0.0585125	total: 1.96s	remaining: 3.85s
750:	learn: 0.0551521	total: 2.21s	remaining: 3.68s
825:	learn: 0.0522209	total: 2.51s	remaining: 3.56s
900:	learn: 0.0495586	total: 2.73s	remaining: 3.33s
975:	learn: 0.0469809	total: 2.96s	remaining: 3.1s
1050:	learn: 0.0446712	total: 3.19s	remaining: 2.88s
1125:	learn: 0.0425087	total: 3.38s	remaining: 2.63s
1200:	learn: 0.0406153	total: 3.59s	remaining: 2.39s
1275:	learn: 0.0388726	total: 3.82s	remaining: 2.17s
1350:	learn: 0.0372206	total: 4.07s	remaining: 1.95s
1425:	learn: 0.0354792	total: 4.33s	remaining: 1.74s
1500:	learn: 0.0338721	total: 4.57s	remaining: 1.52s
1575:	learn: 0.0324336	total: 4.8s	remaining: 1.29s
1650:	learn: 0.0309736	total: 5s	remaining: 1.06s
1725:	learn: 0.0296868	total: 5.19s	remaining: 823ms
1800:	learn: 0.0284672	total: 5.36s	remaining: 592ms
1875:	learn: 0.0271668	total: 5.52s	remaining: 365ms
1950:	learn: 0.0261413	total: 5.7s	remaining: 143ms
1999:	learn: 0.0254961	total: 5.83s	remaining: 0us
0:	learn: 0.3893995	total: 2.39ms	remaining: 4.78s
75:	learn: 0.1317075	total: 185ms	remaining: 4.68s
150:	learn: 0.1076008	total: 358ms	remaining: 4.39s
225:	learn: 0.0970346	total: 579ms	remaining: 4.54s
300:	learn: 0.0886722	total: 803ms	remaining: 4.53s
375:	learn: 0.0824410	total: 1.04s	remaining: 4.48s
450:	learn: 0.0768542	total: 1.28s	remaining: 4.41s
525:	learn: 0.0720036	total: 1.5s	remaining: 4.21s
600:	learn: 0.0676609	total: 1.74s	remaining: 4.06s
675:	learn: 0.0637814	total: 1.96s	remaining: 3.83s
750:	learn: 0.0599449	total: 2.11s	remaining: 3.51s
825:	learn: 0.0563209	total: 2.28s	remaining: 3.24s
900:	learn: 0.0535927	total: 2.51s	remaining: 3.07s
975:	learn: 0.0509674	total: 2.77s	remaining: 2.9s
1050:	learn: 0.0484635	total: 3s	remaining: 2.71s
1125:	learn: 0.0460092	total: 3.32s	remaining: 2.58s
1200:	learn: 0.0440123	total: 3.56s	remaining: 2.37s
1275:	learn: 0.0419448	total: 3.78s	remaining: 2.15s
1350:	learn: 0.0401043	total: 3.98s	remaining: 1.91s
1425:	learn: 0.0383702	total: 4.2s	remaining: 1.69s
1500:	learn: 0.0368212	total: 4.42s	remaining: 1.47s
1575:	learn: 0.0353567	total: 4.63s	remaining: 1.25s
1650:	learn: 0.0339563	total: 4.85s	remaining: 1.02s
1725:	learn: 0.0326664	total: 5.05s	remaining: 802ms
1800:	learn: 0.0314878	total: 5.25s	remaining: 581ms
1875:	learn: 0.0303597	total: 5.47s	remaining: 362ms
1950:	learn: 0.0291622	total: 5.67s	remaining: 142ms
1999:	learn: 0.0284581	total: 5.8s	remaining: 0us
0:	learn: 0.3875552	total: 4.13ms	remaining: 8.25s
75:	learn: 0.1298652	total: 225ms	remaining: 5.7s
150:	learn: 0.1066443	total: 421ms	remaining: 5.16s
225:	learn: 0.0946802	total: 622ms	remaining: 4.88s
300:	learn: 0.0864497	total: 799ms	remaining: 4.51s
375:	learn: 0.0805015	total: 1.03s	remaining: 4.46s
450:	learn: 0.0743562	total: 1.23s	remaining: 4.23s
525:	learn: 0.0693321	total: 1.44s	remaining: 4.04s
600:	learn: 0.0649944	total: 1.67s	remaining: 3.88s
675:	learn: 0.0610757	total: 1.9s	remaining: 3.71s
750:	learn: 0.0576736	total: 2.12s	remaining: 3.52s
825:	learn: 0.0548723	total: 2.28s	remaining: 3.24s
900:	learn: 0.0524626	total: 2.46s	remaining: 3s
975:	learn: 0.0501943	total: 2.62s	remaining: 2.74s
1050:	learn: 0.0477231	total: 2.82s	remaining: 2.54s
1125:	learn: 0.0455092	total: 3s	remaining: 2.33s
1200:	learn: 0.0435910	total: 3.21s	remaining: 2.13s
1275:	learn: 0.0417373	total: 3.47s	remaining: 1.97s
1350:	learn: 0.0400044	total: 3.7s	remaining: 1.78s
1425:	learn: 0.0385135	total: 3.94s	remaining: 1.59s
1500:	learn: 0.0370922	total: 4.18s	remaining: 1.39s
1575:	learn: 0.0356355	total: 4.38s	remaining: 1.18s
1650:	learn: 0.0341630	total: 4.61s	remaining: 974ms
1725:	learn: 0.0329213	total: 4.79s	remaining: 760ms
1800:	learn: 0.0316948	total: 4.96s	remaining: 548ms
1875:	learn: 0.0305004	total: 5.1s	remaining: 337ms
1950:	learn: 0.0292612	total: 5.27s	remaining: 132ms
1999:	learn: 0.0285425	total: 5.39s	remaining: 0us

KRR score: 0.1191 (0.0147)

In [29]:
class AveragingModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, models):
        self.models = models
        
    # we define clones of the original models to fit the data in
    def fit(self, X, y):
        self.models_ = [clone(x) for x in self.models]
        
        # Train cloned base models
        for model in self.models_:
            model.fit(X, y)

        return self
    
    #Now we do the predictions for cloned models and average them
    def predict(self, X):
        predictions = np.column_stack([
            model.predict(X) for model in self.models_
        ])
        return np.mean(predictions, axis=1)

In [30]:
averaged_models = AveragingModels(models = (ENet, model_lgb, model_cat, lasso))

score = rmsle_cv(averaged_models)
print(" Averaged base models score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002727 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1539
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 182
[LightGBM] [Info] Start training from score 12.019632
0:	learn: 0.3903336	total: 2.3ms	remaining: 4.6s
75:	learn: 0.1318063	total: 176ms	remaining: 4.46s
150:	learn: 0.1089452	total: 330ms	remaining: 4.04s
225:	learn: 0.0968738	total: 485ms	remaining: 3.81s
300:	learn: 0.0886320	total: 668ms	remaining: 3.77s
375:	learn: 0.0821777	total: 847ms	remaining: 3.66s
450:	learn: 0.0771170	total: 1.04s	remaining: 3.58s
525:	learn: 0.0715888	total: 1.22s	remaining: 3.42s
600:	learn: 0.0671837	total: 1.42s	remaining: 3.29s
675:	learn: 0.0632406	total: 1.63s	remaining: 3.2s
750:	learn: 0.0598644	total: 1.86s	remaining: 3.1s
825:	learn: 0.0564384	total: 2.08s	remaining: 2.96s
900:	learn: 0.0533364	total: 2.31s	remaining: 2.82s
975:	learn: 0.0504999	total: 2.52s	remaining: 2.64s
1050:	learn: 0.0481557	total: 2.72s	remaining: 2.46s
1125:	learn: 0.0456028	total: 2.92s	remaining: 2.27s
1200:	learn: 0.0434779	total: 3.09s	remaining: 2.06s
1275:	learn: 0.0416634	total: 3.29s	remaining: 1.87s
1350:	learn: 0.0398286	total: 3.48s	remaining: 1.67s
1425:	learn: 0.0379485	total: 3.68s	remaining: 1.48s
1500:	learn: 0.0362219	total: 3.89s	remaining: 1.29s
1575:	learn: 0.0346518	total: 4.18s	remaining: 1.12s
1650:	learn: 0.0332021	total: 4.52s	remaining: 955ms
1725:	learn: 0.0319612	total: 4.75s	remaining: 753ms
1800:	learn: 0.0307338	total: 5.04s	remaining: 557ms
1875:	learn: 0.0294636	total: 5.26s	remaining: 348ms
1950:	learn: 0.0282507	total: 5.48s	remaining: 138ms
1999:	learn: 0.0275223	total: 5.62s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002444 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1550
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 184
[LightGBM] [Info] Start training from score 12.022246
0:	learn: 0.3794933	total: 3.72ms	remaining: 7.44s
75:	learn: 0.1238816	total: 180ms	remaining: 4.56s
150:	learn: 0.1008531	total: 369ms	remaining: 4.51s
225:	learn: 0.0904449	total: 531ms	remaining: 4.16s
300:	learn: 0.0832352	total: 700ms	remaining: 3.95s
375:	learn: 0.0770592	total: 870ms	remaining: 3.76s
450:	learn: 0.0724820	total: 1.04s	remaining: 3.57s
525:	learn: 0.0684937	total: 1.19s	remaining: 3.35s
600:	learn: 0.0641690	total: 1.35s	remaining: 3.15s
675:	learn: 0.0602022	total: 1.5s	remaining: 2.94s
750:	learn: 0.0571032	total: 1.67s	remaining: 2.78s
825:	learn: 0.0539333	total: 1.83s	remaining: 2.6s
900:	learn: 0.0512490	total: 1.99s	remaining: 2.43s
975:	learn: 0.0489364	total: 2.14s	remaining: 2.24s
1050:	learn: 0.0466126	total: 2.29s	remaining: 2.07s
1125:	learn: 0.0442171	total: 2.46s	remaining: 1.91s
1200:	learn: 0.0423151	total: 2.64s	remaining: 1.75s
1275:	learn: 0.0402283	total: 2.79s	remaining: 1.58s
1350:	learn: 0.0383734	total: 2.94s	remaining: 1.41s
1425:	learn: 0.0367087	total: 3.12s	remaining: 1.25s
1500:	learn: 0.0351318	total: 3.32s	remaining: 1.1s
1575:	learn: 0.0337620	total: 3.53s	remaining: 949ms
1650:	learn: 0.0323280	total: 3.8s	remaining: 803ms
1725:	learn: 0.0309662	total: 4.04s	remaining: 642ms
1800:	learn: 0.0297058	total: 4.47s	remaining: 494ms
1875:	learn: 0.0286152	total: 4.7s	remaining: 310ms
1950:	learn: 0.0274549	total: 4.88s	remaining: 123ms
1999:	learn: 0.0267448	total: 5s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002443 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1539
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 182
[LightGBM] [Info] Start training from score 12.019036
0:	learn: 0.3830375	total: 4.01ms	remaining: 8.03s
75:	learn: 0.1276382	total: 228ms	remaining: 5.78s
150:	learn: 0.1036298	total: 412ms	remaining: 5.05s
225:	learn: 0.0915664	total: 656ms	remaining: 5.15s
300:	learn: 0.0830051	total: 852ms	remaining: 4.81s
375:	learn: 0.0762551	total: 1.02s	remaining: 4.4s
450:	learn: 0.0709330	total: 1.2s	remaining: 4.11s
525:	learn: 0.0662381	total: 1.36s	remaining: 3.81s
600:	learn: 0.0618611	total: 1.52s	remaining: 3.54s
675:	learn: 0.0585125	total: 1.69s	remaining: 3.3s
750:	learn: 0.0551521	total: 1.86s	remaining: 3.1s
825:	learn: 0.0522209	total: 2.03s	remaining: 2.89s
900:	learn: 0.0495586	total: 2.21s	remaining: 2.69s
975:	learn: 0.0469809	total: 2.38s	remaining: 2.49s
1050:	learn: 0.0446712	total: 2.56s	remaining: 2.31s
1125:	learn: 0.0425087	total: 2.72s	remaining: 2.11s
1200:	learn: 0.0406153	total: 2.89s	remaining: 1.92s
1275:	learn: 0.0388726	total: 3.06s	remaining: 1.74s
1350:	learn: 0.0372206	total: 3.23s	remaining: 1.55s
1425:	learn: 0.0354792	total: 3.4s	remaining: 1.37s
1500:	learn: 0.0338721	total: 3.57s	remaining: 1.19s
1575:	learn: 0.0324336	total: 3.73s	remaining: 1s
1650:	learn: 0.0309736	total: 3.9s	remaining: 825ms
1725:	learn: 0.0296868	total: 4.1s	remaining: 650ms
1800:	learn: 0.0284672	total: 4.28s	remaining: 472ms
1875:	learn: 0.0271668	total: 4.45s	remaining: 294ms
1950:	learn: 0.0261413	total: 4.63s	remaining: 116ms
1999:	learn: 0.0254961	total: 4.75s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001584 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1554
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 184
[LightGBM] [Info] Start training from score 12.030618
0:	learn: 0.3893995	total: 3.08ms	remaining: 6.17s
75:	learn: 0.1317075	total: 190ms	remaining: 4.81s
150:	learn: 0.1076008	total: 365ms	remaining: 4.46s
225:	learn: 0.0970346	total: 533ms	remaining: 4.18s
300:	learn: 0.0886722	total: 698ms	remaining: 3.94s
375:	learn: 0.0824410	total: 907ms	remaining: 3.92s
450:	learn: 0.0768542	total: 1.11s	remaining: 3.82s
525:	learn: 0.0720036	total: 1.29s	remaining: 3.6s
600:	learn: 0.0676609	total: 1.46s	remaining: 3.39s
675:	learn: 0.0637814	total: 1.63s	remaining: 3.19s
750:	learn: 0.0599449	total: 1.8s	remaining: 2.99s
825:	learn: 0.0563209	total: 1.97s	remaining: 2.8s
900:	learn: 0.0535927	total: 2.17s	remaining: 2.65s
975:	learn: 0.0509674	total: 2.35s	remaining: 2.46s
1050:	learn: 0.0484635	total: 2.57s	remaining: 2.32s
1125:	learn: 0.0460092	total: 2.74s	remaining: 2.13s
1200:	learn: 0.0440123	total: 2.91s	remaining: 1.94s
1275:	learn: 0.0419448	total: 3.1s	remaining: 1.76s
1350:	learn: 0.0401043	total: 3.3s	remaining: 1.59s
1425:	learn: 0.0383702	total: 3.49s	remaining: 1.4s
1500:	learn: 0.0368212	total: 3.67s	remaining: 1.22s
1575:	learn: 0.0353567	total: 3.9s	remaining: 1.05s
1650:	learn: 0.0339563	total: 4.1s	remaining: 868ms
1725:	learn: 0.0326664	total: 4.32s	remaining: 685ms
1800:	learn: 0.0314878	total: 4.54s	remaining: 501ms
1875:	learn: 0.0303597	total: 4.76s	remaining: 315ms
1950:	learn: 0.0291622	total: 4.95s	remaining: 124ms
1999:	learn: 0.0284581	total: 5.07s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002607 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1542
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 183
[LightGBM] [Info] Start training from score 12.019949
0:	learn: 0.3875552	total: 4.65ms	remaining: 9.29s
75:	learn: 0.1298652	total: 202ms	remaining: 5.12s
150:	learn: 0.1066443	total: 373ms	remaining: 4.57s
225:	learn: 0.0946802	total: 542ms	remaining: 4.25s
300:	learn: 0.0864497	total: 750ms	remaining: 4.23s
375:	learn: 0.0805015	total: 922ms	remaining: 3.98s
450:	learn: 0.0743562	total: 1.11s	remaining: 3.83s
525:	learn: 0.0693321	total: 1.32s	remaining: 3.69s
600:	learn: 0.0649944	total: 1.52s	remaining: 3.55s
675:	learn: 0.0610757	total: 1.72s	remaining: 3.36s
750:	learn: 0.0576736	total: 1.88s	remaining: 3.13s
825:	learn: 0.0548723	total: 2.06s	remaining: 2.93s
900:	learn: 0.0524626	total: 2.25s	remaining: 2.75s
975:	learn: 0.0501943	total: 2.45s	remaining: 2.57s
1050:	learn: 0.0477231	total: 2.67s	remaining: 2.41s
1125:	learn: 0.0455092	total: 2.85s	remaining: 2.21s
1200:	learn: 0.0435910	total: 3.06s	remaining: 2.04s
1275:	learn: 0.0417373	total: 3.28s	remaining: 1.86s
1350:	learn: 0.0400044	total: 3.46s	remaining: 1.66s
1425:	learn: 0.0385135	total: 3.64s	remaining: 1.47s
1500:	learn: 0.0370922	total: 3.83s	remaining: 1.27s
1575:	learn: 0.0356355	total: 4.02s	remaining: 1.08s
1650:	learn: 0.0341630	total: 4.2s	remaining: 889ms
1725:	learn: 0.0329213	total: 4.38s	remaining: 695ms
1800:	learn: 0.0316948	total: 4.55s	remaining: 502ms
1875:	learn: 0.0305004	total: 4.72s	remaining: 312ms
1950:	learn: 0.0292612	total: 4.9s	remaining: 123ms
1999:	learn: 0.0285425	total: 5.05s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
 Averaged base models score: 0.1136 (0.0131)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [31]:
class StackingAveragedModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, base_models, meta_model, n_folds=5):
        self.base_models = base_models
        self.meta_model = meta_model
        self.n_folds = n_folds
   
    # We again fit the data on clones of the original models
    def fit(self, X, y):
        self.base_models_ = [list() for x in self.base_models]
        self.meta_model_ = clone(self.meta_model)
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=156)
        
        # Train cloned base models then create out-of-fold predictions
        # that are needed to train the cloned meta-model
        out_of_fold_predictions = np.zeros((X.shape[0], len(self.base_models)))
        for i, model in enumerate(self.base_models):
            for train_index, holdout_index in kfold.split(X, y):
                instance = clone(model)
                self.base_models_[i].append(instance)
                instance.fit(X[train_index], y[train_index])
                y_pred = instance.predict(X[holdout_index])
                out_of_fold_predictions[holdout_index, i] = y_pred
                
        # Now train the cloned  meta-model using the out-of-fold predictions as new feature
        self.meta_model_.fit(out_of_fold_predictions, y)
        return self
    def predict(self, X):
        meta_features = np.column_stack([
            np.column_stack([model.predict(X) for model in base_models]).mean(axis=1)
            for base_models in self.base_models_ ])
        return self.meta_model_.predict(meta_features)

In [32]:
stacked_averaged_models = StackingAveragedModels(base_models = (ENet, model_lgb, model_cat),
                                                 meta_model = lasso)

score = rmsle_cv(stacked_averaged_models)
print("Stacking Averaged models score: {:.4f} ({:.4f})".format(score.mean(), score.std()))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002962 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1496
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 178
[LightGBM] [Info] Start training from score 12.022471

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002839 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1498
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 177
[LightGBM] [Info] Start training from score 12.025076

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003348 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1491
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 174
[LightGBM] [Info] Start training from score 12.018309

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001878 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1501
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 177
[LightGBM] [Info] Start training from score 12.013465

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001788 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1489
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 176
[LightGBM] [Info] Start training from score 12.018845

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3889650	total: 6.28ms	remaining: 12.6s
75:	learn: 0.1294564	total: 262ms	remaining: 6.63s
150:	learn: 0.1051253	total: 432ms	remaining: 5.29s
225:	learn: 0.0937335	total: 615ms	remaining: 4.83s
300:	learn: 0.0850781	total: 800ms	remaining: 4.51s
375:	learn: 0.0781652	total: 970ms	remaining: 4.19s
450:	learn: 0.0722387	total: 1.14s	remaining: 3.91s
525:	learn: 0.0665547	total: 1.3s	remaining: 3.64s
600:	learn: 0.0619199	total: 1.46s	remaining: 3.39s
675:	learn: 0.0576599	total: 1.65s	remaining: 3.22s
750:	learn: 0.0542457	total: 1.81s	remaining: 3.01s
825:	learn: 0.0512279	total: 1.98s	remaining: 2.81s
900:	learn: 0.0482961	total: 2.17s	remaining: 2.64s
975:	learn: 0.0454309	total: 2.33s	remaining: 2.44s
1050:	learn: 0.0429662	total: 2.49s	remaining: 2.25s
1125:	learn: 0.0407335	total: 2.66s	remaining: 2.07s
1200:	learn: 0.0386450	total: 2.83s	remaining: 1.88s
1275:	learn: 0.0366976	total: 3.03s	remaining: 1.72s
1350:	learn: 0.0350883	total: 3.2s	remaining: 1.54s
1425:	learn: 0.0332131	total: 3.37s	remaining: 1.36s
1500:	learn: 0.0312773	total: 3.54s	remaining: 1.18s
1575:	learn: 0.0298007	total: 3.7s	remaining: 995ms
1650:	learn: 0.0283773	total: 3.86s	remaining: 817ms
1725:	learn: 0.0270685	total: 4.02s	remaining: 639ms
1800:	learn: 0.0257217	total: 4.18s	remaining: 462ms
1875:	learn: 0.0245644	total: 4.36s	remaining: 288ms
1950:	learn: 0.0234742	total: 4.52s	remaining: 114ms
1999:	learn: 0.0227709	total: 4.62s	remaining: 0us
0:	learn: 0.3874036	total: 2.81ms	remaining: 5.63s
75:	learn: 0.1287707	total: 180ms	remaining: 4.56s
150:	learn: 0.1048680	total: 369ms	remaining: 4.52s
225:	learn: 0.0928571	total: 529ms	remaining: 4.15s
300:	learn: 0.0840291	total: 700ms	remaining: 3.95s
375:	learn: 0.0777126	total: 872ms	remaining: 3.77s
450:	learn: 0.0717332	total: 1.05s	remaining: 3.6s
525:	learn: 0.0668414	total: 1.21s	remaining: 3.39s
600:	learn: 0.0625533	total: 1.39s	remaining: 3.23s
675:	learn: 0.0585943	total: 1.57s	remaining: 3.08s
750:	learn: 0.0551809	total: 1.75s	remaining: 2.91s
825:	learn: 0.0521639	total: 1.91s	remaining: 2.71s
900:	learn: 0.0492535	total: 2.08s	remaining: 2.53s
975:	learn: 0.0466219	total: 2.25s	remaining: 2.36s
1050:	learn: 0.0439768	total: 2.41s	remaining: 2.17s
1125:	learn: 0.0420145	total: 2.56s	remaining: 1.99s
1200:	learn: 0.0399117	total: 2.83s	remaining: 1.88s
1275:	learn: 0.0378374	total: 3.04s	remaining: 1.73s
1350:	learn: 0.0360237	total: 3.21s	remaining: 1.54s
1425:	learn: 0.0344604	total: 3.37s	remaining: 1.36s
1500:	learn: 0.0329103	total: 3.54s	remaining: 1.18s
1575:	learn: 0.0311794	total: 3.69s	remaining: 994ms
1650:	learn: 0.0297163	total: 3.86s	remaining: 815ms
1725:	learn: 0.0281628	total: 4.03s	remaining: 640ms
1800:	learn: 0.0268003	total: 4.22s	remaining: 466ms
1875:	learn: 0.0258150	total: 4.4s	remaining: 291ms
1950:	learn: 0.0247373	total: 4.57s	remaining: 115ms
1999:	learn: 0.0240664	total: 4.69s	remaining: 0us
0:	learn: 0.3888742	total: 4.84ms	remaining: 9.68s
75:	learn: 0.1300357	total: 218ms	remaining: 5.52s
150:	learn: 0.1073339	total: 415ms	remaining: 5.08s
225:	learn: 0.0946198	total: 623ms	remaining: 4.89s
300:	learn: 0.0858312	total: 810ms	remaining: 4.57s
375:	learn: 0.0783899	total: 990ms	remaining: 4.28s
450:	learn: 0.0728824	total: 1.23s	remaining: 4.22s
525:	learn: 0.0678646	total: 1.44s	remaining: 4.05s
600:	learn: 0.0636160	total: 1.65s	remaining: 3.85s
675:	learn: 0.0594693	total: 1.83s	remaining: 3.59s
750:	learn: 0.0559673	total: 2.02s	remaining: 3.37s
825:	learn: 0.0528651	total: 2.2s	remaining: 3.13s
900:	learn: 0.0500425	total: 2.41s	remaining: 2.94s
975:	learn: 0.0472262	total: 2.58s	remaining: 2.71s
1050:	learn: 0.0445976	total: 2.75s	remaining: 2.48s
1125:	learn: 0.0422014	total: 2.92s	remaining: 2.27s
1200:	learn: 0.0400674	total: 3.11s	remaining: 2.07s
1275:	learn: 0.0379431	total: 3.31s	remaining: 1.88s
1350:	learn: 0.0360243	total: 3.5s	remaining: 1.68s
1425:	learn: 0.0341727	total: 3.69s	remaining: 1.49s
1500:	learn: 0.0325098	total: 3.88s	remaining: 1.29s
1575:	learn: 0.0308090	total: 4.09s	remaining: 1.1s
1650:	learn: 0.0293161	total: 4.28s	remaining: 904ms
1725:	learn: 0.0279905	total: 4.5s	remaining: 714ms
1800:	learn: 0.0266105	total: 4.7s	remaining: 519ms
1875:	learn: 0.0253106	total: 4.88s	remaining: 323ms
1950:	learn: 0.0242039	total: 5.06s	remaining: 127ms
1999:	learn: 0.0236154	total: 5.19s	remaining: 0us
0:	learn: 0.3969480	total: 2.98ms	remaining: 5.95s
75:	learn: 0.1332251	total: 203ms	remaining: 5.13s
150:	learn: 0.1078487	total: 375ms	remaining: 4.6s
225:	learn: 0.0949671	total: 571ms	remaining: 4.48s
300:	learn: 0.0858343	total: 754ms	remaining: 4.25s
375:	learn: 0.0778461	total: 955ms	remaining: 4.13s
450:	learn: 0.0714394	total: 1.2s	remaining: 4.11s
525:	learn: 0.0666468	total: 1.38s	remaining: 3.86s
600:	learn: 0.0615912	total: 1.58s	remaining: 3.67s
675:	learn: 0.0572694	total: 1.76s	remaining: 3.45s
750:	learn: 0.0537473	total: 1.97s	remaining: 3.27s
825:	learn: 0.0501944	total: 2.16s	remaining: 3.07s
900:	learn: 0.0473067	total: 2.36s	remaining: 2.88s
975:	learn: 0.0449201	total: 2.55s	remaining: 2.68s
1050:	learn: 0.0423270	total: 2.74s	remaining: 2.47s
1125:	learn: 0.0401776	total: 2.93s	remaining: 2.28s
1200:	learn: 0.0381333	total: 3.13s	remaining: 2.08s
1275:	learn: 0.0358784	total: 3.31s	remaining: 1.88s
1350:	learn: 0.0341198	total: 3.5s	remaining: 1.68s
1425:	learn: 0.0323505	total: 3.69s	remaining: 1.49s
1500:	learn: 0.0309334	total: 3.89s	remaining: 1.29s
1575:	learn: 0.0293692	total: 4.08s	remaining: 1.1s
1650:	learn: 0.0279873	total: 4.27s	remaining: 904ms
1725:	learn: 0.0266426	total: 4.46s	remaining: 708ms
1800:	learn: 0.0253408	total: 4.65s	remaining: 514ms
1875:	learn: 0.0242772	total: 4.85s	remaining: 321ms
1950:	learn: 0.0232162	total: 5.05s	remaining: 127ms
1999:	learn: 0.0225500	total: 5.17s	remaining: 0us
0:	learn: 0.3859507	total: 2.67ms	remaining: 5.33s
75:	learn: 0.1263997	total: 239ms	remaining: 6.06s
150:	learn: 0.1036848	total: 459ms	remaining: 5.63s
225:	learn: 0.0913258	total: 659ms	remaining: 5.17s
300:	learn: 0.0831647	total: 852ms	remaining: 4.81s
375:	learn: 0.0758762	total: 1.04s	remaining: 4.5s
450:	learn: 0.0696562	total: 1.25s	remaining: 4.31s
525:	learn: 0.0645191	total: 1.47s	remaining: 4.12s
600:	learn: 0.0603603	total: 1.68s	remaining: 3.91s
675:	learn: 0.0566301	total: 1.93s	remaining: 3.77s
750:	learn: 0.0530478	total: 2.14s	remaining: 3.55s
825:	learn: 0.0498816	total: 2.38s	remaining: 3.38s
900:	learn: 0.0469861	total: 2.71s	remaining: 3.3s
975:	learn: 0.0442772	total: 2.98s	remaining: 3.13s
1050:	learn: 0.0418283	total: 3.25s	remaining: 2.94s
1125:	learn: 0.0394885	total: 3.49s	remaining: 2.71s
1200:	learn: 0.0374627	total: 3.73s	remaining: 2.48s
1275:	learn: 0.0356074	total: 3.98s	remaining: 2.25s
1350:	learn: 0.0337518	total: 4.24s	remaining: 2.04s
1425:	learn: 0.0318825	total: 4.5s	remaining: 1.81s
1500:	learn: 0.0302992	total: 4.69s	remaining: 1.56s
1575:	learn: 0.0290149	total: 4.89s	remaining: 1.31s
1650:	learn: 0.0277225	total: 5.09s	remaining: 1.07s
1725:	learn: 0.0263478	total: 5.28s	remaining: 838ms
1800:	learn: 0.0252295	total: 5.47s	remaining: 605ms
1875:	learn: 0.0241726	total: 5.67s	remaining: 375ms
1950:	learn: 0.0229813	total: 5.86s	remaining: 147ms
1999:	learn: 0.0222748	total: 5.98s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003320 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1501
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 175
[LightGBM] [Info] Start training from score 12.029324

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002527 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1498
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 176
[LightGBM] [Info] Start training from score 12.022165

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004122 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1494
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 177
[LightGBM] [Info] Start training from score 12.023416

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005179 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1508
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 181
[LightGBM] [Info] Start training from score 12.013897

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002347 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1494
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 176
[LightGBM] [Info] Start training from score 12.022440

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3796367	total: 6.79ms	remaining: 13.6s
75:	learn: 0.1248919	total: 214ms	remaining: 5.41s
150:	learn: 0.1003257	total: 423ms	remaining: 5.18s
225:	learn: 0.0881911	total: 586ms	remaining: 4.6s
300:	learn: 0.0790704	total: 775ms	remaining: 4.37s
375:	learn: 0.0721142	total: 962ms	remaining: 4.15s
450:	learn: 0.0663654	total: 1.12s	remaining: 3.86s
525:	learn: 0.0623125	total: 1.3s	remaining: 3.65s
600:	learn: 0.0581097	total: 1.49s	remaining: 3.46s
675:	learn: 0.0540494	total: 1.65s	remaining: 3.23s
750:	learn: 0.0505219	total: 1.81s	remaining: 3.01s
825:	learn: 0.0474851	total: 1.99s	remaining: 2.83s
900:	learn: 0.0446249	total: 2.18s	remaining: 2.66s
975:	learn: 0.0422704	total: 2.35s	remaining: 2.47s
1050:	learn: 0.0397972	total: 2.52s	remaining: 2.27s
1125:	learn: 0.0377282	total: 2.72s	remaining: 2.11s
1200:	learn: 0.0358267	total: 2.89s	remaining: 1.93s
1275:	learn: 0.0341197	total: 3.09s	remaining: 1.75s
1350:	learn: 0.0323025	total: 3.27s	remaining: 1.57s
1425:	learn: 0.0307974	total: 3.43s	remaining: 1.38s
1500:	learn: 0.0295249	total: 3.63s	remaining: 1.21s
1575:	learn: 0.0281138	total: 3.85s	remaining: 1.03s
1650:	learn: 0.0269832	total: 4.07s	remaining: 859ms
1725:	learn: 0.0260630	total: 4.25s	remaining: 675ms
1800:	learn: 0.0249466	total: 4.44s	remaining: 491ms
1875:	learn: 0.0237770	total: 4.63s	remaining: 306ms
1950:	learn: 0.0227982	total: 4.82s	remaining: 121ms
1999:	learn: 0.0222601	total: 4.94s	remaining: 0us
0:	learn: 0.3795768	total: 3.58ms	remaining: 7.17s
75:	learn: 0.1237580	total: 227ms	remaining: 5.75s
150:	learn: 0.0991531	total: 443ms	remaining: 5.43s
225:	learn: 0.0873016	total: 605ms	remaining: 4.75s
300:	learn: 0.0795360	total: 793ms	remaining: 4.47s
375:	learn: 0.0734728	total: 986ms	remaining: 4.26s
450:	learn: 0.0683833	total: 1.15s	remaining: 3.95s
525:	learn: 0.0634070	total: 1.33s	remaining: 3.74s
600:	learn: 0.0589229	total: 1.54s	remaining: 3.59s
675:	learn: 0.0550490	total: 1.72s	remaining: 3.37s
750:	learn: 0.0518144	total: 1.9s	remaining: 3.16s
825:	learn: 0.0485690	total: 2.08s	remaining: 2.96s
900:	learn: 0.0456065	total: 2.29s	remaining: 2.79s
975:	learn: 0.0429054	total: 2.46s	remaining: 2.58s
1050:	learn: 0.0405228	total: 2.65s	remaining: 2.39s
1125:	learn: 0.0382132	total: 2.8s	remaining: 2.18s
1200:	learn: 0.0361839	total: 3.03s	remaining: 2.01s
1275:	learn: 0.0340683	total: 3.25s	remaining: 1.84s
1350:	learn: 0.0322108	total: 3.44s	remaining: 1.65s
1425:	learn: 0.0307368	total: 3.61s	remaining: 1.45s
1500:	learn: 0.0291530	total: 3.79s	remaining: 1.26s
1575:	learn: 0.0277566	total: 3.97s	remaining: 1.07s
1650:	learn: 0.0264797	total: 4.15s	remaining: 878ms
1725:	learn: 0.0253600	total: 4.34s	remaining: 690ms
1800:	learn: 0.0241874	total: 4.58s	remaining: 506ms
1875:	learn: 0.0230962	total: 4.77s	remaining: 315ms
1950:	learn: 0.0220248	total: 4.95s	remaining: 124ms
1999:	learn: 0.0213445	total: 5.07s	remaining: 0us
0:	learn: 0.3781351	total: 5.05ms	remaining: 10.1s
75:	learn: 0.1239509	total: 210ms	remaining: 5.31s
150:	learn: 0.0992086	total: 384ms	remaining: 4.71s
225:	learn: 0.0873279	total: 563ms	remaining: 4.42s
300:	learn: 0.0792062	total: 779ms	remaining: 4.39s
375:	learn: 0.0729390	total: 965ms	remaining: 4.17s
450:	learn: 0.0668324	total: 1.14s	remaining: 3.92s
525:	learn: 0.0618223	total: 1.32s	remaining: 3.71s
600:	learn: 0.0571892	total: 1.51s	remaining: 3.51s
675:	learn: 0.0530854	total: 1.7s	remaining: 3.33s
750:	learn: 0.0495732	total: 1.87s	remaining: 3.11s
825:	learn: 0.0463519	total: 2.04s	remaining: 2.91s
900:	learn: 0.0433947	total: 2.23s	remaining: 2.72s
975:	learn: 0.0409112	total: 2.45s	remaining: 2.57s
1050:	learn: 0.0386393	total: 2.63s	remaining: 2.37s
1125:	learn: 0.0366899	total: 2.81s	remaining: 2.18s
1200:	learn: 0.0348318	total: 3s	remaining: 2s
1275:	learn: 0.0331451	total: 3.17s	remaining: 1.8s
1350:	learn: 0.0315620	total: 3.38s	remaining: 1.63s
1425:	learn: 0.0299138	total: 3.56s	remaining: 1.43s
1500:	learn: 0.0285559	total: 3.81s	remaining: 1.27s
1575:	learn: 0.0272022	total: 4s	remaining: 1.07s
1650:	learn: 0.0259906	total: 4.18s	remaining: 883ms
1725:	learn: 0.0248682	total: 4.36s	remaining: 693ms
1800:	learn: 0.0237897	total: 4.59s	remaining: 507ms
1875:	learn: 0.0226879	total: 4.76s	remaining: 315ms
1950:	learn: 0.0217655	total: 4.93s	remaining: 124ms
1999:	learn: 0.0210628	total: 5.04s	remaining: 0us
0:	learn: 0.3835071	total: 4.56ms	remaining: 9.12s
75:	learn: 0.1236913	total: 214ms	remaining: 5.42s
150:	learn: 0.0976816	total: 379ms	remaining: 4.64s
225:	learn: 0.0858370	total: 554ms	remaining: 4.35s
300:	learn: 0.0786259	total: 726ms	remaining: 4.1s
375:	learn: 0.0724980	total: 890ms	remaining: 3.84s
450:	learn: 0.0673915	total: 1.05s	remaining: 3.62s
525:	learn: 0.0626076	total: 1.22s	remaining: 3.41s
600:	learn: 0.0585272	total: 1.38s	remaining: 3.2s
675:	learn: 0.0555294	total: 1.55s	remaining: 3.04s
750:	learn: 0.0525750	total: 1.72s	remaining: 2.87s
825:	learn: 0.0496776	total: 1.89s	remaining: 2.69s
900:	learn: 0.0467091	total: 2.05s	remaining: 2.5s
975:	learn: 0.0441608	total: 2.21s	remaining: 2.32s
1050:	learn: 0.0415943	total: 2.37s	remaining: 2.14s
1125:	learn: 0.0392044	total: 2.54s	remaining: 1.97s
1200:	learn: 0.0370357	total: 2.71s	remaining: 1.8s
1275:	learn: 0.0349053	total: 2.89s	remaining: 1.64s
1350:	learn: 0.0333076	total: 3.05s	remaining: 1.47s
1425:	learn: 0.0315749	total: 3.25s	remaining: 1.31s
1500:	learn: 0.0299225	total: 3.41s	remaining: 1.13s
1575:	learn: 0.0285850	total: 3.58s	remaining: 963ms
1650:	learn: 0.0272206	total: 3.75s	remaining: 792ms
1725:	learn: 0.0258714	total: 3.94s	remaining: 625ms
1800:	learn: 0.0246929	total: 4.12s	remaining: 455ms
1875:	learn: 0.0236136	total: 4.29s	remaining: 284ms
1950:	learn: 0.0225216	total: 4.48s	remaining: 112ms
1999:	learn: 0.0217807	total: 4.61s	remaining: 0us
0:	learn: 0.3832533	total: 4.3ms	remaining: 8.59s
75:	learn: 0.1210557	total: 202ms	remaining: 5.12s
150:	learn: 0.0980698	total: 421ms	remaining: 5.16s
225:	learn: 0.0872071	total: 596ms	remaining: 4.68s
300:	learn: 0.0790252	total: 795ms	remaining: 4.49s
375:	learn: 0.0737647	total: 974ms	remaining: 4.21s
450:	learn: 0.0682253	total: 1.15s	remaining: 3.96s
525:	learn: 0.0634049	total: 1.34s	remaining: 3.77s
600:	learn: 0.0588958	total: 1.64s	remaining: 3.82s
675:	learn: 0.0550131	total: 1.87s	remaining: 3.67s
750:	learn: 0.0519788	total: 2.03s	remaining: 3.38s
825:	learn: 0.0488075	total: 2.21s	remaining: 3.14s
900:	learn: 0.0457560	total: 2.45s	remaining: 2.99s
975:	learn: 0.0431974	total: 2.69s	remaining: 2.82s
1050:	learn: 0.0409406	total: 2.96s	remaining: 2.67s
1125:	learn: 0.0388854	total: 3.19s	remaining: 2.48s
1200:	learn: 0.0368664	total: 3.41s	remaining: 2.27s
1275:	learn: 0.0347078	total: 3.66s	remaining: 2.08s
1350:	learn: 0.0328674	total: 3.91s	remaining: 1.88s
1425:	learn: 0.0313347	total: 4.09s	remaining: 1.65s
1500:	learn: 0.0299094	total: 4.26s	remaining: 1.42s
1575:	learn: 0.0285735	total: 4.45s	remaining: 1.2s
1650:	learn: 0.0271517	total: 4.62s	remaining: 976ms
1725:	learn: 0.0257302	total: 4.77s	remaining: 758ms
1800:	learn: 0.0245900	total: 4.94s	remaining: 546ms
1875:	learn: 0.0234921	total: 5.14s	remaining: 340ms
1950:	learn: 0.0224272	total: 5.33s	remaining: 134ms
1999:	learn: 0.0216500	total: 5.43s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003623 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1494
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 177
[LightGBM] [Info] Start training from score 12.020747

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001802 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1493
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 179
[LightGBM] [Info] Start training from score 12.022128

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001528 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1489
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 177
[LightGBM] [Info] Start training from score 12.019639

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002362 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1493
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 179
[LightGBM] [Info] Start training from score 12.010862

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002835 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1485
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 175
[LightGBM] [Info] Start training from score 12.021808

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3802419	total: 4.5ms	remaining: 9.01s
75:	learn: 0.1282479	total: 198ms	remaining: 5.01s
150:	learn: 0.1025834	total: 395ms	remaining: 4.84s
225:	learn: 0.0901530	total: 592ms	remaining: 4.65s
300:	learn: 0.0816239	total: 763ms	remaining: 4.31s
375:	learn: 0.0750040	total: 952ms	remaining: 4.11s
450:	learn: 0.0686506	total: 1.15s	remaining: 3.95s
525:	learn: 0.0637409	total: 1.33s	remaining: 3.73s
600:	learn: 0.0590853	total: 1.55s	remaining: 3.61s
675:	learn: 0.0551456	total: 1.72s	remaining: 3.37s
750:	learn: 0.0514223	total: 1.88s	remaining: 3.13s
825:	learn: 0.0482301	total: 2.05s	remaining: 2.92s
900:	learn: 0.0450875	total: 2.25s	remaining: 2.75s
975:	learn: 0.0421539	total: 2.43s	remaining: 2.55s
1050:	learn: 0.0396093	total: 2.6s	remaining: 2.34s
1125:	learn: 0.0373238	total: 2.76s	remaining: 2.14s
1200:	learn: 0.0351940	total: 2.94s	remaining: 1.96s
1275:	learn: 0.0331764	total: 3.12s	remaining: 1.77s
1350:	learn: 0.0312957	total: 3.28s	remaining: 1.58s
1425:	learn: 0.0297722	total: 3.48s	remaining: 1.4s
1500:	learn: 0.0282203	total: 3.64s	remaining: 1.21s
1575:	learn: 0.0268557	total: 3.81s	remaining: 1.02s
1650:	learn: 0.0255174	total: 4s	remaining: 847ms
1725:	learn: 0.0243135	total: 4.17s	remaining: 662ms
1800:	learn: 0.0230033	total: 4.37s	remaining: 483ms
1875:	learn: 0.0218592	total: 4.54s	remaining: 300ms
1950:	learn: 0.0208032	total: 4.73s	remaining: 119ms
1999:	learn: 0.0202386	total: 4.84s	remaining: 0us
0:	learn: 0.3854041	total: 4.34ms	remaining: 8.68s
75:	learn: 0.1282912	total: 203ms	remaining: 5.14s
150:	learn: 0.1022984	total: 381ms	remaining: 4.66s
225:	learn: 0.0890969	total: 542ms	remaining: 4.25s
300:	learn: 0.0790710	total: 720ms	remaining: 4.07s
375:	learn: 0.0722221	total: 908ms	remaining: 3.92s
450:	learn: 0.0658033	total: 1.09s	remaining: 3.74s
525:	learn: 0.0607238	total: 1.28s	remaining: 3.59s
600:	learn: 0.0563479	total: 1.44s	remaining: 3.35s
675:	learn: 0.0531910	total: 1.61s	remaining: 3.15s
750:	learn: 0.0502882	total: 1.78s	remaining: 2.97s
825:	learn: 0.0474736	total: 1.96s	remaining: 2.78s
900:	learn: 0.0447189	total: 2.12s	remaining: 2.58s
975:	learn: 0.0426185	total: 2.29s	remaining: 2.4s
1050:	learn: 0.0402746	total: 2.46s	remaining: 2.22s
1125:	learn: 0.0381971	total: 2.65s	remaining: 2.06s
1200:	learn: 0.0363253	total: 2.84s	remaining: 1.89s
1275:	learn: 0.0343909	total: 3.02s	remaining: 1.71s
1350:	learn: 0.0325466	total: 3.26s	remaining: 1.57s
1425:	learn: 0.0310414	total: 3.44s	remaining: 1.38s
1500:	learn: 0.0293977	total: 3.62s	remaining: 1.2s
1575:	learn: 0.0279349	total: 3.79s	remaining: 1.02s
1650:	learn: 0.0265843	total: 3.95s	remaining: 836ms
1725:	learn: 0.0252224	total: 4.12s	remaining: 654ms
1800:	learn: 0.0240612	total: 4.28s	remaining: 473ms
1875:	learn: 0.0229800	total: 4.45s	remaining: 294ms
1950:	learn: 0.0220330	total: 4.61s	remaining: 116ms
1999:	learn: 0.0213654	total: 4.73s	remaining: 0us
0:	learn: 0.3808504	total: 4.29ms	remaining: 8.58s
75:	learn: 0.1258302	total: 208ms	remaining: 5.27s
150:	learn: 0.1007041	total: 415ms	remaining: 5.08s
225:	learn: 0.0879178	total: 604ms	remaining: 4.74s
300:	learn: 0.0778207	total: 784ms	remaining: 4.42s
375:	learn: 0.0704188	total: 965ms	remaining: 4.17s
450:	learn: 0.0642815	total: 1.18s	remaining: 4.05s
525:	learn: 0.0591635	total: 1.36s	remaining: 3.81s
600:	learn: 0.0546557	total: 1.57s	remaining: 3.65s
675:	learn: 0.0509025	total: 1.78s	remaining: 3.49s
750:	learn: 0.0476826	total: 1.96s	remaining: 3.26s
825:	learn: 0.0448926	total: 2.15s	remaining: 3.06s
900:	learn: 0.0421393	total: 2.34s	remaining: 2.86s
975:	learn: 0.0397296	total: 2.53s	remaining: 2.65s
1050:	learn: 0.0376704	total: 2.72s	remaining: 2.46s
1125:	learn: 0.0355928	total: 2.92s	remaining: 2.27s
1200:	learn: 0.0332805	total: 3.12s	remaining: 2.08s
1275:	learn: 0.0316450	total: 3.31s	remaining: 1.88s
1350:	learn: 0.0298085	total: 3.5s	remaining: 1.68s
1425:	learn: 0.0280670	total: 3.68s	remaining: 1.48s
1500:	learn: 0.0266423	total: 3.88s	remaining: 1.29s
1575:	learn: 0.0252119	total: 4.12s	remaining: 1.11s
1650:	learn: 0.0240451	total: 4.31s	remaining: 910ms
1725:	learn: 0.0229783	total: 4.49s	remaining: 713ms
1800:	learn: 0.0218232	total: 4.7s	remaining: 520ms
1875:	learn: 0.0207896	total: 4.89s	remaining: 323ms
1950:	learn: 0.0199501	total: 5.09s	remaining: 128ms
1999:	learn: 0.0193055	total: 5.23s	remaining: 0us
0:	learn: 0.3852648	total: 5.33ms	remaining: 10.7s
75:	learn: 0.1268903	total: 228ms	remaining: 5.78s
150:	learn: 0.1021240	total: 450ms	remaining: 5.51s
225:	learn: 0.0901637	total: 688ms	remaining: 5.4s
300:	learn: 0.0816534	total: 927ms	remaining: 5.23s
375:	learn: 0.0742247	total: 1.18s	remaining: 5.08s
450:	learn: 0.0682472	total: 1.39s	remaining: 4.76s
525:	learn: 0.0627710	total: 1.61s	remaining: 4.53s
600:	learn: 0.0580252	total: 1.83s	remaining: 4.25s
675:	learn: 0.0543485	total: 2.07s	remaining: 4.06s
750:	learn: 0.0510051	total: 2.3s	remaining: 3.82s
825:	learn: 0.0478567	total: 2.54s	remaining: 3.61s
900:	learn: 0.0450743	total: 2.79s	remaining: 3.4s
975:	learn: 0.0426409	total: 3.03s	remaining: 3.17s
1050:	learn: 0.0402420	total: 3.27s	remaining: 2.95s
1125:	learn: 0.0377611	total: 3.51s	remaining: 2.72s
1200:	learn: 0.0357605	total: 3.75s	remaining: 2.5s
1275:	learn: 0.0338365	total: 3.98s	remaining: 2.25s
1350:	learn: 0.0321849	total: 4.19s	remaining: 2.01s
1425:	learn: 0.0307860	total: 4.42s	remaining: 1.78s
1500:	learn: 0.0293370	total: 4.68s	remaining: 1.56s
1575:	learn: 0.0279882	total: 4.88s	remaining: 1.31s
1650:	learn: 0.0266417	total: 5.08s	remaining: 1.07s
1725:	learn: 0.0253328	total: 5.34s	remaining: 848ms
1800:	learn: 0.0242011	total: 5.64s	remaining: 623ms
1875:	learn: 0.0231031	total: 5.84s	remaining: 386ms
1950:	learn: 0.0219677	total: 6.05s	remaining: 152ms
1999:	learn: 0.0213125	total: 6.2s	remaining: 0us
0:	learn: 0.3878632	total: 3.71ms	remaining: 7.42s
75:	learn: 0.1245098	total: 196ms	remaining: 4.97s
150:	learn: 0.1013287	total: 395ms	remaining: 4.84s
225:	learn: 0.0885375	total: 600ms	remaining: 4.71s
300:	learn: 0.0799758	total: 806ms	remaining: 4.55s
375:	learn: 0.0731575	total: 985ms	remaining: 4.25s
450:	learn: 0.0671869	total: 1.17s	remaining: 4.03s
525:	learn: 0.0619572	total: 1.35s	remaining: 3.78s
600:	learn: 0.0577284	total: 1.51s	remaining: 3.52s
675:	learn: 0.0538484	total: 1.7s	remaining: 3.34s
750:	learn: 0.0504490	total: 1.87s	remaining: 3.12s
825:	learn: 0.0474504	total: 2.04s	remaining: 2.89s
900:	learn: 0.0444205	total: 2.23s	remaining: 2.71s
975:	learn: 0.0416034	total: 2.41s	remaining: 2.52s
1050:	learn: 0.0392824	total: 2.6s	remaining: 2.35s
1125:	learn: 0.0370257	total: 2.78s	remaining: 2.15s
1200:	learn: 0.0351931	total: 2.99s	remaining: 1.99s
1275:	learn: 0.0333499	total: 3.22s	remaining: 1.83s
1350:	learn: 0.0314699	total: 3.42s	remaining: 1.64s
1425:	learn: 0.0299199	total: 3.61s	remaining: 1.45s
1500:	learn: 0.0283048	total: 3.78s	remaining: 1.26s
1575:	learn: 0.0267372	total: 3.95s	remaining: 1.06s
1650:	learn: 0.0253752	total: 4.12s	remaining: 871ms
1725:	learn: 0.0240386	total: 4.33s	remaining: 687ms
1800:	learn: 0.0229921	total: 4.52s	remaining: 500ms
1875:	learn: 0.0218118	total: 4.77s	remaining: 315ms
1950:	learn: 0.0207736	total: 5.02s	remaining: 126ms
1999:	learn: 0.0201500	total: 5.15s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003083 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1514
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 179
[LightGBM] [Info] Start training from score 12.027691

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001733 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1510
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 179
[LightGBM] [Info] Start training from score 12.034833

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002951 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1506
[LightGBM] [Info] Number of data points in the train set: 930, number of used features: 180
[LightGBM] [Info] Start training from score 12.029881

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002289 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1522
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 181
[LightGBM] [Info] Start training from score 12.025933

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001616 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1509
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 175
[LightGBM] [Info] Start training from score 12.034755

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3847056	total: 3.18ms	remaining: 6.35s
75:	learn: 0.1326975	total: 178ms	remaining: 4.51s
150:	learn: 0.1082403	total: 327ms	remaining: 4.01s
225:	learn: 0.0958836	total: 481ms	remaining: 3.77s
300:	learn: 0.0869455	total: 665ms	remaining: 3.75s
375:	learn: 0.0795048	total: 836ms	remaining: 3.61s
450:	learn: 0.0733279	total: 1000ms	remaining: 3.43s
525:	learn: 0.0671584	total: 1.16s	remaining: 3.26s
600:	learn: 0.0621565	total: 1.31s	remaining: 3.06s
675:	learn: 0.0579475	total: 1.47s	remaining: 2.87s
750:	learn: 0.0542373	total: 1.62s	remaining: 2.7s
825:	learn: 0.0509057	total: 1.77s	remaining: 2.52s
900:	learn: 0.0477117	total: 1.96s	remaining: 2.39s
975:	learn: 0.0449899	total: 2.12s	remaining: 2.22s
1050:	learn: 0.0423565	total: 2.27s	remaining: 2.05s
1125:	learn: 0.0402193	total: 2.42s	remaining: 1.88s
1200:	learn: 0.0381453	total: 2.58s	remaining: 1.72s
1275:	learn: 0.0361928	total: 2.73s	remaining: 1.55s
1350:	learn: 0.0342789	total: 2.88s	remaining: 1.38s
1425:	learn: 0.0325968	total: 3.08s	remaining: 1.24s
1500:	learn: 0.0308463	total: 3.28s	remaining: 1.09s
1575:	learn: 0.0293719	total: 3.47s	remaining: 933ms
1650:	learn: 0.0278560	total: 3.63s	remaining: 767ms
1725:	learn: 0.0264083	total: 3.81s	remaining: 604ms
1800:	learn: 0.0252901	total: 3.98s	remaining: 440ms
1875:	learn: 0.0242043	total: 4.14s	remaining: 274ms
1950:	learn: 0.0230754	total: 4.33s	remaining: 109ms
1999:	learn: 0.0224489	total: 4.47s	remaining: 0us
0:	learn: 0.3911833	total: 3.05ms	remaining: 6.09s
75:	learn: 0.1314275	total: 193ms	remaining: 4.89s
150:	learn: 0.1080268	total: 357ms	remaining: 4.37s
225:	learn: 0.0951466	total: 551ms	remaining: 4.32s
300:	learn: 0.0860380	total: 717ms	remaining: 4.05s
375:	learn: 0.0786456	total: 887ms	remaining: 3.83s
450:	learn: 0.0730641	total: 1.05s	remaining: 3.61s
525:	learn: 0.0686272	total: 1.21s	remaining: 3.4s
600:	learn: 0.0641133	total: 1.38s	remaining: 3.22s
675:	learn: 0.0602178	total: 1.57s	remaining: 3.08s
750:	learn: 0.0564331	total: 1.74s	remaining: 2.89s
825:	learn: 0.0529887	total: 1.9s	remaining: 2.7s
900:	learn: 0.0498685	total: 2.06s	remaining: 2.51s
975:	learn: 0.0471300	total: 2.22s	remaining: 2.33s
1050:	learn: 0.0443262	total: 2.41s	remaining: 2.17s
1125:	learn: 0.0417390	total: 2.58s	remaining: 2.01s
1200:	learn: 0.0397316	total: 2.77s	remaining: 1.84s
1275:	learn: 0.0374902	total: 2.97s	remaining: 1.68s
1350:	learn: 0.0356771	total: 3.17s	remaining: 1.52s
1425:	learn: 0.0339004	total: 3.33s	remaining: 1.34s
1500:	learn: 0.0321905	total: 3.52s	remaining: 1.17s
1575:	learn: 0.0304680	total: 3.72s	remaining: 1s
1650:	learn: 0.0291129	total: 3.89s	remaining: 822ms
1725:	learn: 0.0277296	total: 4.06s	remaining: 645ms
1800:	learn: 0.0264641	total: 4.23s	remaining: 467ms
1875:	learn: 0.0253082	total: 4.44s	remaining: 294ms
1950:	learn: 0.0242783	total: 4.61s	remaining: 116ms
1999:	learn: 0.0236188	total: 4.72s	remaining: 0us
0:	learn: 0.3929076	total: 4.33ms	remaining: 8.65s
75:	learn: 0.1297590	total: 187ms	remaining: 4.74s
150:	learn: 0.1043811	total: 347ms	remaining: 4.25s
225:	learn: 0.0916617	total: 524ms	remaining: 4.11s
300:	learn: 0.0827829	total: 677ms	remaining: 3.82s
375:	learn: 0.0750056	total: 833ms	remaining: 3.6s
450:	learn: 0.0690456	total: 1.02s	remaining: 3.52s
525:	learn: 0.0639612	total: 1.18s	remaining: 3.31s
600:	learn: 0.0595224	total: 1.37s	remaining: 3.18s
675:	learn: 0.0553750	total: 1.53s	remaining: 3s
750:	learn: 0.0522401	total: 1.69s	remaining: 2.81s
825:	learn: 0.0493250	total: 1.84s	remaining: 2.62s
900:	learn: 0.0463572	total: 2s	remaining: 2.44s
975:	learn: 0.0437799	total: 2.18s	remaining: 2.29s
1050:	learn: 0.0410894	total: 2.34s	remaining: 2.11s
1125:	learn: 0.0386825	total: 2.53s	remaining: 1.97s
1200:	learn: 0.0365008	total: 2.69s	remaining: 1.79s
1275:	learn: 0.0347502	total: 2.84s	remaining: 1.61s
1350:	learn: 0.0331591	total: 3s	remaining: 1.44s
1425:	learn: 0.0313758	total: 3.15s	remaining: 1.27s
1500:	learn: 0.0298026	total: 3.31s	remaining: 1.1s
1575:	learn: 0.0285338	total: 3.5s	remaining: 942ms
1650:	learn: 0.0271022	total: 3.67s	remaining: 776ms
1725:	learn: 0.0260601	total: 3.82s	remaining: 607ms
1800:	learn: 0.0247832	total: 4s	remaining: 442ms
1875:	learn: 0.0235499	total: 4.17s	remaining: 276ms
1950:	learn: 0.0225245	total: 4.32s	remaining: 109ms
1999:	learn: 0.0218424	total: 4.43s	remaining: 0us
0:	learn: 0.3885559	total: 4.99ms	remaining: 9.97s
75:	learn: 0.1288942	total: 189ms	remaining: 4.8s
150:	learn: 0.1055223	total: 370ms	remaining: 4.53s
225:	learn: 0.0948059	total: 601ms	remaining: 4.72s
300:	learn: 0.0865591	total: 817ms	remaining: 4.61s
375:	learn: 0.0791890	total: 1.01s	remaining: 4.36s
450:	learn: 0.0734416	total: 1.21s	remaining: 4.15s
525:	learn: 0.0682052	total: 1.39s	remaining: 3.91s
600:	learn: 0.0636158	total: 1.61s	remaining: 3.76s
675:	learn: 0.0600315	total: 1.81s	remaining: 3.54s
750:	learn: 0.0565155	total: 2.01s	remaining: 3.34s
825:	learn: 0.0533131	total: 2.2s	remaining: 3.13s
900:	learn: 0.0505308	total: 2.4s	remaining: 2.93s
975:	learn: 0.0477773	total: 2.6s	remaining: 2.73s
1050:	learn: 0.0451017	total: 2.79s	remaining: 2.52s
1125:	learn: 0.0426246	total: 2.97s	remaining: 2.3s
1200:	learn: 0.0404936	total: 3.16s	remaining: 2.1s
1275:	learn: 0.0381928	total: 3.35s	remaining: 1.9s
1350:	learn: 0.0360658	total: 3.52s	remaining: 1.69s
1425:	learn: 0.0338340	total: 3.69s	remaining: 1.49s
1500:	learn: 0.0318547	total: 3.9s	remaining: 1.3s
1575:	learn: 0.0301762	total: 4.13s	remaining: 1.11s
1650:	learn: 0.0287417	total: 4.29s	remaining: 908ms
1725:	learn: 0.0273821	total: 4.5s	remaining: 714ms
1800:	learn: 0.0261608	total: 4.66s	remaining: 515ms
1875:	learn: 0.0249655	total: 4.83s	remaining: 319ms
1950:	learn: 0.0237590	total: 5.02s	remaining: 126ms
1999:	learn: 0.0229938	total: 5.15s	remaining: 0us
0:	learn: 0.3927467	total: 4.06ms	remaining: 8.11s
75:	learn: 0.1279593	total: 200ms	remaining: 5.07s
150:	learn: 0.1038889	total: 391ms	remaining: 4.79s
225:	learn: 0.0920894	total: 621ms	remaining: 4.87s
300:	learn: 0.0834429	total: 838ms	remaining: 4.73s
375:	learn: 0.0768100	total: 1s	remaining: 4.32s
450:	learn: 0.0709188	total: 1.18s	remaining: 4.04s
525:	learn: 0.0659161	total: 1.35s	remaining: 3.77s
600:	learn: 0.0616290	total: 1.52s	remaining: 3.55s
675:	learn: 0.0579181	total: 1.7s	remaining: 3.34s
750:	learn: 0.0540223	total: 1.87s	remaining: 3.11s
825:	learn: 0.0509258	total: 2.03s	remaining: 2.89s
900:	learn: 0.0481587	total: 2.27s	remaining: 2.76s
975:	learn: 0.0458053	total: 2.42s	remaining: 2.54s
1050:	learn: 0.0431978	total: 2.58s	remaining: 2.33s
1125:	learn: 0.0407333	total: 2.77s	remaining: 2.15s
1200:	learn: 0.0385062	total: 2.97s	remaining: 1.98s
1275:	learn: 0.0365195	total: 3.13s	remaining: 1.78s
1350:	learn: 0.0347407	total: 3.31s	remaining: 1.59s
1425:	learn: 0.0328907	total: 3.48s	remaining: 1.4s
1500:	learn: 0.0311946	total: 3.77s	remaining: 1.25s
1575:	learn: 0.0296203	total: 3.94s	remaining: 1.06s
1650:	learn: 0.0281647	total: 4.12s	remaining: 872ms
1725:	learn: 0.0267874	total: 4.28s	remaining: 680ms
1800:	learn: 0.0255814	total: 4.44s	remaining: 490ms
1875:	learn: 0.0243570	total: 4.63s	remaining: 306ms
1950:	learn: 0.0233996	total: 4.84s	remaining: 122ms
1999:	learn: 0.0226052	total: 4.97s	remaining: 0us

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007074 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1503
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 180
[LightGBM] [Info] Start training from score 12.024857

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002443 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1504
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 181
[LightGBM] [Info] Start training from score 12.007325

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003020 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1504
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 181
[LightGBM] [Info] Start training from score 12.026876

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001970 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1511
[LightGBM] [Info] Number of data points in the train set: 931, number of used features: 179
[LightGBM] [Info] Start training from score 12.017683

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002015 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1500
[LightGBM] [Info] Number of data points in the train set: 932, number of used features: 176
[LightGBM] [Info] Start training from score 12.023001

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3886428	total: 4.73ms	remaining: 9.45s
75:	learn: 0.1263911	total: 188ms	remaining: 4.76s
150:	learn: 0.1018594	total: 370ms	remaining: 4.53s
225:	learn: 0.0895711	total: 522ms	remaining: 4.1s
300:	learn: 0.0810737	total: 672ms	remaining: 3.79s
375:	learn: 0.0742477	total: 831ms	remaining: 3.59s
450:	learn: 0.0691081	total: 1.01s	remaining: 3.46s
525:	learn: 0.0642022	total: 1.17s	remaining: 3.28s
600:	learn: 0.0596773	total: 1.32s	remaining: 3.07s
675:	learn: 0.0557590	total: 1.47s	remaining: 2.89s
750:	learn: 0.0522935	total: 1.63s	remaining: 2.71s
825:	learn: 0.0489657	total: 1.78s	remaining: 2.53s
900:	learn: 0.0459574	total: 1.98s	remaining: 2.41s
975:	learn: 0.0431825	total: 2.14s	remaining: 2.24s
1050:	learn: 0.0407067	total: 2.3s	remaining: 2.08s
1125:	learn: 0.0385201	total: 2.47s	remaining: 1.92s
1200:	learn: 0.0364536	total: 2.63s	remaining: 1.75s
1275:	learn: 0.0344784	total: 2.82s	remaining: 1.6s
1350:	learn: 0.0325398	total: 3.01s	remaining: 1.44s
1425:	learn: 0.0308105	total: 3.18s	remaining: 1.28s
1500:	learn: 0.0292728	total: 3.35s	remaining: 1.11s
1575:	learn: 0.0278449	total: 3.55s	remaining: 954ms
1650:	learn: 0.0267174	total: 3.71s	remaining: 785ms
1725:	learn: 0.0255607	total: 3.9s	remaining: 619ms
1800:	learn: 0.0244269	total: 4.05s	remaining: 448ms
1875:	learn: 0.0233067	total: 4.21s	remaining: 278ms
1950:	learn: 0.0223030	total: 4.39s	remaining: 110ms
1999:	learn: 0.0216383	total: 4.49s	remaining: 0us
0:	learn: 0.3893129	total: 3.58ms	remaining: 7.15s
75:	learn: 0.1332103	total: 179ms	remaining: 4.52s
150:	learn: 0.1086044	total: 342ms	remaining: 4.19s
225:	learn: 0.0954566	total: 505ms	remaining: 3.96s
300:	learn: 0.0859483	total: 660ms	remaining: 3.72s
375:	learn: 0.0796555	total: 813ms	remaining: 3.51s
450:	learn: 0.0732835	total: 971ms	remaining: 3.33s
525:	learn: 0.0681304	total: 1.15s	remaining: 3.23s
600:	learn: 0.0639510	total: 1.31s	remaining: 3.04s
675:	learn: 0.0598499	total: 1.46s	remaining: 2.86s
750:	learn: 0.0560917	total: 1.61s	remaining: 2.68s
825:	learn: 0.0527651	total: 1.76s	remaining: 2.5s
900:	learn: 0.0495276	total: 1.91s	remaining: 2.33s
975:	learn: 0.0467243	total: 2.09s	remaining: 2.2s
1050:	learn: 0.0439267	total: 2.25s	remaining: 2.04s
1125:	learn: 0.0415142	total: 2.41s	remaining: 1.87s
1200:	learn: 0.0392742	total: 2.56s	remaining: 1.7s
1275:	learn: 0.0373496	total: 2.71s	remaining: 1.54s
1350:	learn: 0.0355070	total: 2.88s	remaining: 1.38s
1425:	learn: 0.0337041	total: 3.03s	remaining: 1.22s
1500:	learn: 0.0319322	total: 3.22s	remaining: 1.07s
1575:	learn: 0.0305643	total: 3.4s	remaining: 915ms
1650:	learn: 0.0290767	total: 3.59s	remaining: 760ms
1725:	learn: 0.0276663	total: 3.77s	remaining: 598ms
1800:	learn: 0.0262881	total: 3.94s	remaining: 436ms
1875:	learn: 0.0251307	total: 4.11s	remaining: 272ms
1950:	learn: 0.0238086	total: 4.28s	remaining: 107ms
1999:	learn: 0.0230569	total: 4.41s	remaining: 0us
0:	learn: 0.3850613	total: 5.21ms	remaining: 10.4s
75:	learn: 0.1272953	total: 218ms	remaining: 5.53s
150:	learn: 0.1034268	total: 385ms	remaining: 4.71s
225:	learn: 0.0904135	total: 568ms	remaining: 4.46s
300:	learn: 0.0822016	total: 742ms	remaining: 4.19s
375:	learn: 0.0750617	total: 903ms	remaining: 3.9s
450:	learn: 0.0687187	total: 1.05s	remaining: 3.63s
525:	learn: 0.0634673	total: 1.24s	remaining: 3.48s
600:	learn: 0.0593380	total: 1.41s	remaining: 3.29s
675:	learn: 0.0554684	total: 1.57s	remaining: 3.08s
750:	learn: 0.0517971	total: 1.75s	remaining: 2.9s
825:	learn: 0.0481889	total: 1.91s	remaining: 2.72s
900:	learn: 0.0454164	total: 2.14s	remaining: 2.61s
975:	learn: 0.0427253	total: 2.31s	remaining: 2.43s
1050:	learn: 0.0405580	total: 2.5s	remaining: 2.25s
1125:	learn: 0.0386294	total: 2.66s	remaining: 2.07s
1200:	learn: 0.0366340	total: 2.83s	remaining: 1.88s
1275:	learn: 0.0348393	total: 3.03s	remaining: 1.72s
1350:	learn: 0.0330407	total: 3.19s	remaining: 1.53s
1425:	learn: 0.0313656	total: 3.35s	remaining: 1.35s
1500:	learn: 0.0297787	total: 3.51s	remaining: 1.17s
1575:	learn: 0.0283688	total: 3.67s	remaining: 989ms
1650:	learn: 0.0271284	total: 3.84s	remaining: 811ms
1725:	learn: 0.0259340	total: 4.02s	remaining: 639ms
1800:	learn: 0.0247895	total: 4.24s	remaining: 469ms
1875:	learn: 0.0237786	total: 4.43s	remaining: 293ms
1950:	learn: 0.0227710	total: 4.6s	remaining: 115ms
1999:	learn: 0.0221206	total: 4.7s	remaining: 0us
0:	learn: 0.3834341	total: 4.33ms	remaining: 8.66s
75:	learn: 0.1273376	total: 292ms	remaining: 7.38s
150:	learn: 0.1027153	total: 505ms	remaining: 6.19s
225:	learn: 0.0896304	total: 704ms	remaining: 5.53s
300:	learn: 0.0808605	total: 900ms	remaining: 5.08s
375:	learn: 0.0751597	total: 1.06s	remaining: 4.58s
450:	learn: 0.0700478	total: 1.21s	remaining: 4.16s
525:	learn: 0.0654326	total: 1.39s	remaining: 3.9s
600:	learn: 0.0611566	total: 1.57s	remaining: 3.65s
675:	learn: 0.0573136	total: 1.75s	remaining: 3.43s
750:	learn: 0.0536135	total: 1.93s	remaining: 3.2s
825:	learn: 0.0506149	total: 2.1s	remaining: 2.98s
900:	learn: 0.0478204	total: 2.25s	remaining: 2.75s
975:	learn: 0.0452941	total: 2.47s	remaining: 2.59s
1050:	learn: 0.0428939	total: 2.69s	remaining: 2.43s
1125:	learn: 0.0406584	total: 2.95s	remaining: 2.29s
1200:	learn: 0.0385605	total: 3.21s	remaining: 2.14s
1275:	learn: 0.0366381	total: 3.49s	remaining: 1.98s
1350:	learn: 0.0346329	total: 3.73s	remaining: 1.79s
1425:	learn: 0.0326493	total: 3.91s	remaining: 1.57s
1500:	learn: 0.0311914	total: 4.1s	remaining: 1.36s
1575:	learn: 0.0296974	total: 4.3s	remaining: 1.16s
1650:	learn: 0.0284359	total: 4.5s	remaining: 950ms
1725:	learn: 0.0271592	total: 4.71s	remaining: 747ms
1800:	learn: 0.0260761	total: 4.89s	remaining: 540ms
1875:	learn: 0.0250034	total: 5.1s	remaining: 337ms
1950:	learn: 0.0240313	total: 5.27s	remaining: 132ms
1999:	learn: 0.0233240	total: 5.39s	remaining: 0us
0:	learn: 0.3946699	total: 4.47ms	remaining: 8.94s
75:	learn: 0.1281662	total: 188ms	remaining: 4.75s
150:	learn: 0.1035053	total: 350ms	remaining: 4.29s
225:	learn: 0.0906020	total: 523ms	remaining: 4.1s
300:	learn: 0.0814043	total: 706ms	remaining: 3.99s
375:	learn: 0.0759622	total: 865ms	remaining: 3.74s
450:	learn: 0.0707678	total: 1.03s	remaining: 3.52s
525:	learn: 0.0659767	total: 1.22s	remaining: 3.41s
600:	learn: 0.0614995	total: 1.39s	remaining: 3.24s
675:	learn: 0.0573916	total: 1.56s	remaining: 3.05s
750:	learn: 0.0536695	total: 1.71s	remaining: 2.85s
825:	learn: 0.0501841	total: 1.87s	remaining: 2.66s
900:	learn: 0.0471642	total: 2.11s	remaining: 2.57s
975:	learn: 0.0444729	total: 2.27s	remaining: 2.39s
1050:	learn: 0.0418486	total: 2.46s	remaining: 2.22s
1125:	learn: 0.0396028	total: 2.62s	remaining: 2.03s
1200:	learn: 0.0376791	total: 2.77s	remaining: 1.84s
1275:	learn: 0.0355191	total: 2.93s	remaining: 1.66s
1350:	learn: 0.0337391	total: 3.08s	remaining: 1.48s
1425:	learn: 0.0320297	total: 3.23s	remaining: 1.3s
1500:	learn: 0.0303631	total: 3.39s	remaining: 1.13s
1575:	learn: 0.0288463	total: 3.58s	remaining: 965ms
1650:	learn: 0.0275462	total: 3.75s	remaining: 792ms
1725:	learn: 0.0262382	total: 3.93s	remaining: 624ms
1800:	learn: 0.0250663	total: 4.08s	remaining: 451ms
1875:	learn: 0.0239230	total: 4.25s	remaining: 281ms
1950:	learn: 0.0227937	total: 4.44s	remaining: 112ms
1999:	learn: 0.0220948	total: 4.55s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
Stacking Averaged models score: 0.1138 (0.0123)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [33]:
def rmsle(y, y_pred):
    return np.sqrt(mean_squared_error(y, y_pred))

In [34]:
stacked_averaged_models.fit(train.values, y_train)
stacked_train_pred = stacked_averaged_models.predict(train.values)
stacked_pred = np.expm1(stacked_averaged_models.predict(test.values))
print(rmsle(y_train, stacked_train_pred))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007423 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1545
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 185
[LightGBM] [Info] Start training from score 12.031454

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001521 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1530
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 179
[LightGBM] [Info] Start training from score 12.014533

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002568 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1543
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 181
[LightGBM] [Info] Start training from score 12.020309

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002994 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1534
[LightGBM] [Info] Number of data points in the train set: 1163, number of used features: 181
[LightGBM] [Info] Start training from score 12.025670

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002573 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1544
[LightGBM] [Info] Number of data points in the train set: 1164, number of used features: 181
[LightGBM] [Info] Start training from score 12.019516

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0:	learn: 0.3849366	total: 2.78ms	remaining: 5.55s
75:	learn: 0.1297256	total: 175ms	remaining: 4.43s
150:	learn: 0.1071786	total: 356ms	remaining: 4.36s
225:	learn: 0.0945483	total: 523ms	remaining: 4.1s
300:	learn: 0.0864424	total: 680ms	remaining: 3.84s
375:	learn: 0.0798815	total: 842ms	remaining: 3.64s
450:	learn: 0.0746702	total: 984ms	remaining: 3.38s
525:	learn: 0.0699880	total: 1.13s	remaining: 3.16s
600:	learn: 0.0655763	total: 1.3s	remaining: 3.02s
675:	learn: 0.0619746	total: 1.49s	remaining: 2.92s
750:	learn: 0.0586246	total: 1.7s	remaining: 2.83s
825:	learn: 0.0552250	total: 1.87s	remaining: 2.65s
900:	learn: 0.0525727	total: 2.03s	remaining: 2.48s
975:	learn: 0.0498959	total: 2.17s	remaining: 2.28s
1050:	learn: 0.0474672	total: 2.33s	remaining: 2.1s
1125:	learn: 0.0450962	total: 2.54s	remaining: 1.97s
1200:	learn: 0.0429850	total: 2.75s	remaining: 1.83s
1275:	learn: 0.0408657	total: 2.9s	remaining: 1.65s
1350:	learn: 0.0391670	total: 3.06s	remaining: 1.47s
1425:	learn: 0.0373974	total: 3.2s	remaining: 1.29s
1500:	learn: 0.0356502	total: 3.35s	remaining: 1.11s
1575:	learn: 0.0341657	total: 3.52s	remaining: 947ms
1650:	learn: 0.0328024	total: 3.73s	remaining: 790ms
1725:	learn: 0.0314522	total: 3.96s	remaining: 629ms
1800:	learn: 0.0299829	total: 4.21s	remaining: 465ms
1875:	learn: 0.0288321	total: 4.51s	remaining: 298ms
1950:	learn: 0.0277817	total: 4.77s	remaining: 120ms
1999:	learn: 0.0271137	total: 4.92s	remaining: 0us
0:	learn: 0.3878982	total: 3.69ms	remaining: 7.37s
75:	learn: 0.1283672	total: 245ms	remaining: 6.2s
150:	learn: 0.1059165	total: 468ms	remaining: 5.73s
225:	learn: 0.0939286	total: 680ms	remaining: 5.33s
300:	learn: 0.0853788	total: 888ms	remaining: 5.01s
375:	learn: 0.0788648	total: 1.15s	remaining: 4.96s
450:	learn: 0.0737561	total: 1.34s	remaining: 4.61s
525:	learn: 0.0691792	total: 1.51s	remaining: 4.23s
600:	learn: 0.0646874	total: 1.7s	remaining: 3.96s
675:	learn: 0.0612335	total: 1.87s	remaining: 3.66s
750:	learn: 0.0578880	total: 2.08s	remaining: 3.46s
825:	learn: 0.0548155	total: 2.29s	remaining: 3.25s
900:	learn: 0.0516615	total: 2.49s	remaining: 3.04s
975:	learn: 0.0492314	total: 2.72s	remaining: 2.86s
1050:	learn: 0.0468755	total: 2.91s	remaining: 2.63s
1125:	learn: 0.0445204	total: 3.11s	remaining: 2.42s
1200:	learn: 0.0425725	total: 3.31s	remaining: 2.2s
1275:	learn: 0.0407208	total: 3.48s	remaining: 1.98s
1350:	learn: 0.0388276	total: 3.65s	remaining: 1.75s
1425:	learn: 0.0371717	total: 3.84s	remaining: 1.54s
1500:	learn: 0.0356602	total: 4s	remaining: 1.33s
1575:	learn: 0.0340408	total: 4.16s	remaining: 1.12s
1650:	learn: 0.0327559	total: 4.31s	remaining: 911ms
1725:	learn: 0.0314605	total: 4.49s	remaining: 712ms
1800:	learn: 0.0302428	total: 4.7s	remaining: 519ms
1875:	learn: 0.0289199	total: 4.87s	remaining: 322ms
1950:	learn: 0.0278845	total: 5.05s	remaining: 127ms
1999:	learn: 0.0271793	total: 5.16s	remaining: 0us
0:	learn: 0.3871599	total: 2.72ms	remaining: 5.43s
75:	learn: 0.1301443	total: 190ms	remaining: 4.8s
150:	learn: 0.1053115	total: 355ms	remaining: 4.34s
225:	learn: 0.0930375	total: 516ms	remaining: 4.05s
300:	learn: 0.0841527	total: 667ms	remaining: 3.76s
375:	learn: 0.0772111	total: 815ms	remaining: 3.52s
450:	learn: 0.0718952	total: 985ms	remaining: 3.38s
525:	learn: 0.0675783	total: 1.17s	remaining: 3.28s
600:	learn: 0.0634556	total: 1.33s	remaining: 3.1s
675:	learn: 0.0599473	total: 1.49s	remaining: 2.92s
750:	learn: 0.0566400	total: 1.66s	remaining: 2.76s
825:	learn: 0.0533973	total: 1.87s	remaining: 2.66s
900:	learn: 0.0506390	total: 2.09s	remaining: 2.55s
975:	learn: 0.0481958	total: 2.33s	remaining: 2.44s
1050:	learn: 0.0457833	total: 2.52s	remaining: 2.27s
1125:	learn: 0.0434241	total: 2.69s	remaining: 2.09s
1200:	learn: 0.0412510	total: 2.87s	remaining: 1.91s
1275:	learn: 0.0393325	total: 3.04s	remaining: 1.73s
1350:	learn: 0.0375855	total: 3.21s	remaining: 1.54s
1425:	learn: 0.0358498	total: 3.38s	remaining: 1.36s
1500:	learn: 0.0340461	total: 3.57s	remaining: 1.19s
1575:	learn: 0.0327120	total: 3.74s	remaining: 1.01s
1650:	learn: 0.0314175	total: 3.92s	remaining: 828ms
1725:	learn: 0.0302183	total: 4.08s	remaining: 648ms
1800:	learn: 0.0289199	total: 4.26s	remaining: 471ms
1875:	learn: 0.0278166	total: 4.44s	remaining: 294ms
1950:	learn: 0.0267703	total: 4.61s	remaining: 116ms
1999:	learn: 0.0260818	total: 4.74s	remaining: 0us
0:	learn: 0.3855134	total: 2.41ms	remaining: 4.82s
75:	learn: 0.1260498	total: 177ms	remaining: 4.48s
150:	learn: 0.1038065	total: 358ms	remaining: 4.39s
225:	learn: 0.0928329	total: 521ms	remaining: 4.09s
300:	learn: 0.0843563	total: 704ms	remaining: 3.97s
375:	learn: 0.0787021	total: 868ms	remaining: 3.75s
450:	learn: 0.0737873	total: 1.03s	remaining: 3.54s
525:	learn: 0.0690222	total: 1.21s	remaining: 3.4s
600:	learn: 0.0650879	total: 1.39s	remaining: 3.23s
675:	learn: 0.0618275	total: 1.56s	remaining: 3.06s
750:	learn: 0.0582959	total: 1.75s	remaining: 2.9s
825:	learn: 0.0551791	total: 1.91s	remaining: 2.71s
900:	learn: 0.0522362	total: 2.09s	remaining: 2.55s
975:	learn: 0.0497212	total: 2.25s	remaining: 2.36s
1050:	learn: 0.0472827	total: 2.42s	remaining: 2.19s
1125:	learn: 0.0449151	total: 2.6s	remaining: 2.02s
1200:	learn: 0.0428597	total: 2.82s	remaining: 1.88s
1275:	learn: 0.0408529	total: 2.99s	remaining: 1.7s
1350:	learn: 0.0390116	total: 3.17s	remaining: 1.52s
1425:	learn: 0.0371361	total: 3.33s	remaining: 1.34s
1500:	learn: 0.0355325	total: 3.5s	remaining: 1.16s
1575:	learn: 0.0337647	total: 3.66s	remaining: 985ms
1650:	learn: 0.0323383	total: 3.83s	remaining: 809ms
1725:	learn: 0.0310219	total: 4.01s	remaining: 637ms
1800:	learn: 0.0297470	total: 4.18s	remaining: 462ms
1875:	learn: 0.0285736	total: 4.34s	remaining: 287ms
1950:	learn: 0.0274783	total: 4.51s	remaining: 113ms
1999:	learn: 0.0266971	total: 4.66s	remaining: 0us
0:	learn: 0.3855247	total: 2.93ms	remaining: 5.86s
75:	learn: 0.1295449	total: 185ms	remaining: 4.68s
150:	learn: 0.1063779	total: 374ms	remaining: 4.58s
225:	learn: 0.0945298	total: 532ms	remaining: 4.18s
300:	learn: 0.0863929	total: 696ms	remaining: 3.93s
375:	learn: 0.0795721	total: 868ms	remaining: 3.75s
450:	learn: 0.0743668	total: 1.04s	remaining: 3.57s
525:	learn: 0.0692159	total: 1.22s	remaining: 3.42s
600:	learn: 0.0650780	total: 1.39s	remaining: 3.23s
675:	learn: 0.0613326	total: 1.57s	remaining: 3.08s
750:	learn: 0.0577390	total: 1.75s	remaining: 2.91s
825:	learn: 0.0546327	total: 1.94s	remaining: 2.76s
900:	learn: 0.0519475	total: 2.11s	remaining: 2.58s
975:	learn: 0.0493661	total: 2.26s	remaining: 2.37s
1050:	learn: 0.0468950	total: 2.4s	remaining: 2.17s
1125:	learn: 0.0448438	total: 2.56s	remaining: 1.99s
1200:	learn: 0.0428665	total: 2.71s	remaining: 1.8s
1275:	learn: 0.0411180	total: 2.85s	remaining: 1.62s
1350:	learn: 0.0392525	total: 3s	remaining: 1.44s
1425:	learn: 0.0375482	total: 3.14s	remaining: 1.26s
1500:	learn: 0.0358896	total: 3.3s	remaining: 1.1s
1575:	learn: 0.0344695	total: 3.47s	remaining: 933ms
1650:	learn: 0.0330466	total: 3.62s	remaining: 766ms
1725:	learn: 0.0316958	total: 3.78s	remaining: 600ms
1800:	learn: 0.0304803	total: 4.01s	remaining: 443ms
1875:	learn: 0.0293594	total: 4.23s	remaining: 280ms
1950:	learn: 0.0283405	total: 4.4s	remaining: 110ms
1999:	learn: 0.0277706	total: 4.51s	remaining: 0us
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0.07950309140883853

In [35]:
model_xgb.fit(train, y_train)
xgb_train_pred = model_xgb.predict(train)
xgb_pred = np.expm1(model_xgb.predict(test))
print(rmsle(y_train, xgb_train_pred))

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [11:42:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "silent" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

0.08639715451359559

In [36]:
model_lgb.fit(train, y_train)
lgb_train_pred = model_lgb.predict(train)
lgb_pred = np.expm1(model_lgb.predict(test.values))
print(rmsle(y_train, lgb_train_pred))

[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003739 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1577
[LightGBM] [Info] Number of data points in the train set: 1454, number of used features: 187
[LightGBM] [Info] Start training from score 12.022296
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
0.07348583326631271

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [37]:
ENet.fit(train, y_train)
ENet_train_pred = ENet.predict(train)
ENet_pred = np.expm1(ENet.predict(test.values))
print(rmsle(y_train, ENet_train_pred))

0.10574089736153709

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(

In [38]:
model_cat.fit(train, y_train)
cat_train_pred = model_cat.predict(train)
cat_pred = np.expm1(model_cat.predict(test.values))
print(rmsle(y_train, cat_train_pred))

0:	learn: 0.3858046	total: 2.73ms	remaining: 5.46s
75:	learn: 0.1297603	total: 173ms	remaining: 4.38s
150:	learn: 0.1081228	total: 343ms	remaining: 4.2s
225:	learn: 0.0964389	total: 492ms	remaining: 3.87s
300:	learn: 0.0888362	total: 642ms	remaining: 3.63s
375:	learn: 0.0825587	total: 793ms	remaining: 3.43s
450:	learn: 0.0774791	total: 950ms	remaining: 3.26s
525:	learn: 0.0724736	total: 1.11s	remaining: 3.13s
600:	learn: 0.0682636	total: 1.28s	remaining: 2.99s
675:	learn: 0.0649795	total: 1.44s	remaining: 2.83s
750:	learn: 0.0615490	total: 1.59s	remaining: 2.65s
825:	learn: 0.0584976	total: 1.76s	remaining: 2.51s
900:	learn: 0.0559516	total: 1.92s	remaining: 2.33s
975:	learn: 0.0534741	total: 2.08s	remaining: 2.18s
1050:	learn: 0.0513651	total: 2.29s	remaining: 2.07s
1125:	learn: 0.0492517	total: 2.48s	remaining: 1.93s
1200:	learn: 0.0473416	total: 2.66s	remaining: 1.77s
1275:	learn: 0.0453856	total: 2.83s	remaining: 1.61s
1350:	learn: 0.0438157	total: 3.01s	remaining: 1.45s
1425:	learn: 0.0423460	total: 3.2s	remaining: 1.29s
1500:	learn: 0.0406889	total: 3.37s	remaining: 1.12s
1575:	learn: 0.0393327	total: 3.54s	remaining: 951ms
1650:	learn: 0.0379474	total: 3.7s	remaining: 782ms
1725:	learn: 0.0366195	total: 3.95s	remaining: 628ms
1800:	learn: 0.0353124	total: 4.18s	remaining: 462ms
1875:	learn: 0.0342345	total: 4.39s	remaining: 290ms
1950:	learn: 0.0332177	total: 4.61s	remaining: 116ms
1999:	learn: 0.0326094	total: 4.75s	remaining: 0us
0.03260942425236186

In [39]:
print('RMSLE score on train data:')
print(rmsle(y_train,stacked_train_pred*0.70 +
               cat_train_pred*0.15 + ENet_train_pred*0.15 ))

RMSLE score on train data:
0.0750246208867164

In [ ]:
ensemble = stacked_pred*0.70 + cat_pred*0.15 + lgb_pred*0.15

In [41]:
sub = pd.DataFrame()
sub['Id'] = test_ID
sub['SalePrice'] = ensemble
sub.to_csv('submission.csv',index=False)