# 🔧 Demo Preprocessing Modules - House Prices Dataset

Notebook này demo các chức năng của 3 modules preprocessing:
- 🧹 **Clean**: Xử lý dữ liệu thiếu, duplicate, balance
- 🔄 **Preprocess**: Scaling, encoding, outlier handling
- ⭐ **Feature**: Feature selection và engineering

In [246]:
# Import thư viện cần thiết
import pandas as pd
import numpy as np
import sys
import os

# Thêm đường dẫn src vào sys.path
sys.path.append(os.path.abspath('../src'))

# Import các module preprocessing
from preprocess.clean.clean import Clean
from preprocess.preprocess.preprocess import Preprocess
from preprocess.feature.feature import Feature

print("✅ Import thành công!")
print("📦 Modules: Clean, Preprocess, Feature")

✅ Import thành công!
📦 Modules: Clean, Preprocess, Feature

## 📂 Load Dữ Liệu

Load dữ liệu train và test từ thư mục data/raw/

In [247]:
# Load dữ liệu train và test
train_path = '../data/raw/train.csv'
test_path = '../data/raw/test.csv'

df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

print(f"📊 Train shape: {df_train.shape}")
print(f"📊 Test shape: {df_test.shape}")

# Hiển thị một vài dòng đầu
print("\n🔍 Xem dữ liệu train:")
df_train.head()

📊 Train shape: (1460, 81)
📊 Test shape: (1459, 80)

🔍 Xem dữ liệu train:

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

# 🧹 PHẦN 1: CLEAN MODULE

Module Clean xử lý các vấn đề về chất lượng dữ liệu: missing values, duplicates, imbalance

## 🔍 Demo 1.1: Phân Tích Missing Values

Sử dụng `analyze_missing()` để xem chi tiết các cột có giá trị thiếu

In [248]:
# Khởi tạo Clean cho train dataset
cleaner_train = Clean(df_train.copy())

# Phân tích missing values
cleaner_train.analyze_missing()

## 🔧 Phân Tích Giá Trị Thiếu

**📉 Chi tiết giá trị thiếu**

## 🛠️ Demo 1.2: Xử Lý Missing Values

Sử dụng `handle_missing()` để xử lý giá trị thiếu với các phương pháp khác nhau

In [249]:
# Xử lý missing values cho numerical columns với mean
cleaner_train.handle_missing(
    columns=['LotFrontage'], 
    strategy='mean'
)

## 🔧 Xử Lý Giá Trị Thiếu (mean)

## 🔧 Phân Tích Giá Trị Thiếu

**📉 Chi tiết giá trị thiếu**

### ✅ Đã xử lý **259** giá trị thiếu (Còn lại: 7570)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [250]:
# Xử lý missing values cho categorical columns với mode
cleaner_train.handle_missing(
    columns=['Alley', 'MasVnrType', 'FireplaceQu'], 
    strategy='mode'
)

## 🔧 Xử Lý Giá Trị Thiếu (mode)

## 🔧 Phân Tích Giá Trị Thiếu

**📉 Chi tiết giá trị thiếu**

### ✅ Đã xử lý **2931** giá trị thiếu (Còn lại: 4639)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Grvl,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Grvl,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Grvl,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

## 🗑️ Demo 1.3: Drop Columns với Missing Values Cao

Xóa các cột có tỉ lệ missing values quá cao (>80%)

In [251]:
# Drop các cột có >80% missing values
cleaner_train.drop_columns_with_missing(threshold=0.8)

## 🔧 Xóa Cột (>= 80.0% thiếu)

**🗑️ Các cột sẽ xóa**

### ✅ Đã xóa **3** cột

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Grvl,IR1,Lvl,AllPub,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Grvl,Reg,Lvl,AllPub,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,6,2008,WD,Normal,147500

## 🔄 Demo 1.4: Remove Duplicates

Kiểm tra và loại bỏ các dòng trùng lặp

In [252]:
# Loại bỏ duplicates
cleaner_train.remove_duplicates()

## 🔧 Xóa Dòng Trùng Lặp

### ✅ **Không có dòng trùng lặp!**

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Grvl,IR1,Lvl,AllPub,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Grvl,Reg,Lvl,AllPub,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,6,2008,WD,Normal,147500

## 📊 Demo 1.5: Xem History và Get Data

Xem lịch sử các thao tác đã thực hiện và lấy dữ liệu đã cleaned

In [253]:
# Xem history
cleaner_train.show_history()

## 🔧 Lịch Sử Cleaning

**📜 Các bước đã thực hiện**

In [254]:
# Lấy dữ liệu đã cleaned
df_cleaned = cleaner_train.get_cleaned_data()
print(f"\n✅ Cleaned data shape: {df_cleaned.shape}")
df_cleaned.head()

✅ Cleaned data shape: (1460, 78)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Grvl,IR1,Lvl,AllPub,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,12,2008,WD,Normal,250000

# 🔄 PHẦN 2: PREPROCESS MODULE

Module Preprocess xử lý transformation: scaling, encoding, outlier handling

## 📏 Demo 2.1: Scaling Numerical Features

Scale các features số về cùng một range

In [255]:
# Khởi tạo Preprocess với dữ liệu đã cleaned
preprocessor = Preprocess(df_cleaned.copy())

# Scale numerical features với StandardScaler
preprocessor.standardize(
    columns=['LotArea', 'GrLivArea', 'TotalBsmtSF', 'GarageArea'],
    show_comparison=False
)

## ⚙️ Standardization (Z-score)

### ✅ Standardization hoàn tất! (4 cột)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,-0.207142,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,-0.091886,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,0.073480,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,-0.096897,Pave,Grvl,IR1,Lvl,AllPub,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,0.375148,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,-0.260560,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,0.266407,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,-0.147810,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,-0.080160,Pave,Grvl,Reg,Lvl,AllPub,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,-0.058112,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [256]:
# Thử MinMaxScaler cho một số columns khác
preprocessor.rescale(
    columns=['YearBuilt', 'YearRemodAdd'],
    show_comparison=False
)

## ⚙️ MinMax Scaling (Range: (0, 1))

### ✅ MinMax Scaling hoàn tất! (2 cột)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,-0.207142,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,-0.091886,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,0.073480,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,-0.096897,Pave,Grvl,IR1,Lvl,AllPub,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,0.375148,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,-0.260560,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,0.266407,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,-0.147810,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,-0.080160,Pave,Grvl,Reg,Lvl,AllPub,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,-0.058112,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,6,2008,WD,Normal,147500

## 🏷️ Demo 2.2: Encoding Categorical Features

Chuyển đổi categorical features thành dạng số

In [257]:
# Label Encoding cho ordinal features
preprocessor.label_encode(
    columns=['ExterQual', 'ExterCond', 'BsmtQual', 'KitchenQual'],
    show_mapping=False
)

## ⚙️ Label Encoding

### ✅ Label Encoding hoàn tất! (4 cột)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,-0.207142,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,-0.091886,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,0.073480,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,-0.096897,Pave,Grvl,IR1,Lvl,AllPub,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,0.375148,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,-0.260560,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,0.266407,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,-0.147810,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,-0.080160,Pave,Grvl,Reg,Lvl,AllPub,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,-0.058112,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [258]:
# One-Hot Encoding cho nominal features
preprocessor.one_hot_encode(
    columns=['MSZoning', 'Street', 'LotShape'],
    show_result=False
)

## ⚙️ One-Hot Encoding

### ✅ One-Hot Encoding hoàn tất! (+5 cột mới)

,Id,MSSubClass,LotFrontage,LotArea,Alley,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,SaleCondition,SalePrice,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg
0,1,60,65.0,-0.207142,Grvl,Lvl,AllPub,Inside,Gtl,CollgCr,...,Normal,208500,0,0,1,0,1,0,0,1
1,2,20,80.0,-0.091886,Grvl,Lvl,AllPub,FR2,Gtl,Veenker,...,Normal,181500,0,0,1,0,1,0,0,1
2,3,60,68.0,0.073480,Grvl,Lvl,AllPub,Inside,Gtl,CollgCr,...,Normal,223500,0,0,1,0,1,0,0,0
3,4,70,60.0,-0.096897,Grvl,Lvl,AllPub,Corner,Gtl,Crawfor,...,Abnorml,140000,0,0,1,0,1,0,0,0
4,5,60,84.0,0.375148,Grvl,Lvl,AllPub,FR2,Gtl,NoRidge,...,Normal,250000,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,-0.260560,Grvl,Lvl,AllPub,Inside,Gtl,Gilbert,...,Normal,175000,0,0,1,0,1,0,0,1
1456,1457,20,85.0,0.266407,Grvl,Lvl,AllPub,Inside,Gtl,NWAmes,...,Normal,210000,0,0,1,0,1,0,0,1
1457,1458,70,66.0,-0.147810,Grvl,Lvl,AllPub,Inside,Gtl,Crawfor,...,Normal,266500,0,0,1,0,1,0,0,1
1458,1459,20,68.0,-0.080160,Grvl,Lvl,AllPub,Inside,Gtl,NAmes,...,Normal,142125,0,0,1,0,1,0,0,1
1459,1460,20,75.0,-0.058112,Grvl,Lvl,AllPub,Inside,Gtl,Edwards,...,Normal,147500,0,0,1,0,1,0,0,1

## 🎯 Demo 2.3: Outlier Detection và Handling

Phát hiện và xử lý outliers

In [259]:
# Remove outliers với IQR method
# Note: Module Preprocess chỉ có remove_outliers (xóa outliers hẳn)
# Ở đây ta sẽ demo phát hiện trước bằng cách xem số lượng outliers
import matplotlib.pyplot as plt

# Phát hiện outliers cho LotArea
col = 'LotArea'
Q1 = df_cleaned[col].quantile(0.25)
Q3 = df_cleaned[col].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers_mask = (df_cleaned[col] < lower) | (df_cleaned[col] > upper)

print(f"📊 Phát hiện outliers trong {col}:")
print(f"   - Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
print(f"   - Lower bound: {lower:.2f}, Upper bound: {upper:.2f}")
print(f"   - Số outliers: {outliers_mask.sum()} ({outliers_mask.sum()/len(df_cleaned)*100:.2f}%)")

📊 Phát hiện outliers trong LotArea:
   - Q1: 7553.50, Q3: 11601.50, IQR: 4048.00
   - Lower bound: 1481.50, Upper bound: 17673.50
   - Số outliers: 69 (4.73%)

In [260]:
# Remove outliers (sẽ xóa các dòng có outliers)
# Lưu ý: thường không nên xóa outliers trong regression vì có thể mất thông tin quan trọng
# Ở đây chỉ demo phương thức, không áp dụng thực tế

# Nếu muốn xóa outliers, uncomment dòng dưới:
# preprocessor.remove_outliers(columns=['LotArea', 'GrLivArea'], method='iqr', show_report=True)

print("⚠️ Đã skip bước remove outliers để giữ nguyên dữ liệu!")
print("💡 Trong thực tế, outliers có thể chứa thông tin quan trọng cho dự đoán giá nhà.")

⚠️ Đã skip bước remove outliers để giữ nguyên dữ liệu!
💡 Trong thực tế, outliers có thể chứa thông tin quan trọng cho dự đoán giá nhà.

## 📊 Demo 2.4: Xem History và Get Data

Xem lịch sử transformation và lấy dữ liệu đã preprocessed

In [261]:
# Xem history
preprocessor.show_history()

## ⚙️ Lịch Sử Xử Lý

**📜 Các bước đã thực hiện**

In [262]:
# Lấy dữ liệu đã preprocessed
df_preprocessed = preprocessor.get_processed_data()
print(f"\n✅ Preprocessed data shape: {df_preprocessed.shape}")
df_preprocessed.head()

✅ Preprocessed data shape: (1460, 83)

,Id,MSSubClass,LotFrontage,LotArea,Alley,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,SaleCondition,SalePrice,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg
0,1,60,65.0,-0.207142,Grvl,Lvl,AllPub,Inside,Gtl,CollgCr,...,Normal,208500,0,0,1,0,1,0,0,1
1,2,20,80.0,-0.091886,Grvl,Lvl,AllPub,FR2,Gtl,Veenker,...,Normal,181500,0,0,1,0,1,0,0,1
2,3,60,68.0,0.073480,Grvl,Lvl,AllPub,Inside,Gtl,CollgCr,...,Normal,223500,0,0,1,0,1,0,0,0
3,4,70,60.0,-0.096897,Grvl,Lvl,AllPub,Corner,Gtl,Crawfor,...,Abnorml,140000,0,0,1,0,1,0,0,0
4,5,60,84.0,0.375148,Grvl,Lvl,AllPub,FR2,Gtl,NoRidge,...,Normal,250000,0,0,1,0,1,0,0,0

# ⭐ PHẦN 3: FEATURE MODULE

Module Feature thực hiện feature selection và engineering

## 🎯 Demo 3.1: Univariate Feature Selection

Chọn features dựa trên statistical tests

In [263]:
# Chuẩn bị dữ liệu cho Feature Selection
# Lấy numerical columns và target
numeric_cols = df_preprocessed.select_dtypes(include=[np.number]).columns.tolist()
if 'SalePrice' in numeric_cols:
    numeric_cols.remove('SalePrice')
if 'Id' in numeric_cols:
    numeric_cols.remove('Id')

# Tạo DataFrame mới kết hợp X và y
X = df_preprocessed[numeric_cols]
y = df_train['SalePrice']  # Target từ train gốc

# Tạo DataFrame hoàn chỉnh với target
df_with_target = X.copy()
df_with_target['SalePrice'] = y.values

# Khởi tạo Feature module với DataFrame có target
feature_selector = Feature(df_with_target, target_col='SalePrice', task='regression')

print(f"✅ Feature selector initialized")
print(f"📊 Data shape: {df_with_target.shape}")
print(f"📊 Features: {len(numeric_cols)}, Target: SalePrice")

✅ Feature selector initialized
📊 Data shape: (1460, 49)
📊 Features: 48, Target: SalePrice

In [264]:
# Reload module trước khi chạy (để áp dụng fix f_regression)
import importlib
from preprocess.feature import feature
importlib.reload(feature)
from preprocess.feature.feature import Feature

# Xử lý NaN values trước khi feature selection
df_with_target_clean = df_with_target.fillna(df_with_target.median(numeric_only=True))
print(f"✅ Đã xử lý {df_with_target.isna().sum().sum()} NaN values")

# Reinitialize feature_selector với data đã clean
feature_selector = Feature(df_with_target_clean, target_col='SalePrice', task='regression')

# Bây giờ chạy univariate selection với f_regression
feature_selector.univariate_selection(k=20, score_func='f_regression')

✅ Đã xử lý 89 NaN values

## 🔬 Univariate Feature Selection (Top 20)

**📊 Top 20 Features (F_REGRESSION)**

### ✅ Đã chọn **20** features bằng F_REGRESSION

,LotFrontage,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,BsmtQual,BsmtFinSF1,TotalBsmtSF,1stFlrSF,...,GrLivArea,FullBath,KitchenQual,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,SalePrice
0,65.0,7.0,0.949275,0.883333,196.0,2.0,2.0,706.0,-0.459303,856.0,...,0.370333,2.0,2.0,8.0,0.0,2003.0,2.0,0.351000,0.0,208500
1,80.0,6.0,0.753623,0.433333,0.0,3.0,2.0,978.0,0.466465,1262.0,...,-0.482512,2.0,3.0,6.0,1.0,1976.0,2.0,-0.060731,298.0,181500
2,68.0,7.0,0.934783,0.866667,162.0,2.0,2.0,486.0,-0.313369,920.0,...,0.515013,2.0,2.0,6.0,1.0,2001.0,2.0,0.631726,0.0,223500
3,60.0,7.0,0.311594,0.333333,0.0,3.0,3.0,216.0,-0.687324,961.0,...,0.383659,1.0,2.0,7.0,1.0,1998.0,3.0,0.790804,0.0,140000
4,84.0,8.0,0.927536,0.833333,350.0,2.0,2.0,655.0,0.199680,1145.0,...,1.299326,2.0,2.0,9.0,1.0,2000.0,3.0,1.698485,192.0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,6.0,0.920290,0.833333,0.0,3.0,2.0,0.0,-0.238122,953.0,...,0.250402,2.0,3.0,7.0,1.0,1999.0,2.0,-0.060731,0.0,175000
1456,85.0,6.0,0.768116,0.633333,119.0,3.0,2.0,790.0,1.104925,2073.0,...,1.061367,2.0,3.0,7.0,2.0,1978.0,2.0,0.126420,349.0,210000
1457,66.0,7.0,0.500000,0.933333,0.0,0.0,3.0,275.0,0.215641,1188.0,...,1.569647,2.0,2.0,9.0,2.0,1941.0,1.0,-1.033914,0.0,266500
1458,68.0,5.0,0.565217,0.766667,0.0,3.0,3.0,49.0,0.046905,1078.0,...,-0.832788,1.0,2.0,5.0,0.0,1950.0,1.0,-1.090059,366.0,142125
1459,75.0,5.0,0.673913,0.250000,0.0,2.0,3.0,830.0,0.452784,1256.0,...,-0.493934,1.0,3.0,6.0,0.0,1965.0,1.0,-0.921624,736.0,147500

In [265]:
# Reload module để áp dụng thay đổi mới
import importlib
from preprocess.feature import feature
importlib.reload(feature)
from preprocess.feature.feature import Feature

print("✅ Module Feature đã được reload với hỗ trợ f_regression!")

✅ Module Feature đã được reload với hỗ trợ f_regression!

In [266]:
# Reinitialize feature_selector với module đã reload
feature_selector = Feature(df_with_target, target_col='SalePrice', task='regression')
print("✅ Feature selector được khởi tạo lại với module mới!")

✅ Feature selector được khởi tạo lại với module mới!

## 🔄 Demo 3.2: RFE (Recursive Feature Elimination)

Chọn features bằng RFE với Random Forest

In [267]:
# Reset để thử method khác (reset sẽ quay về data gốc)
feature_selector.reset()

# Xử lý NaN sau khi reset
feature_selector.df = feature_selector.df.fillna(feature_selector.df.median(numeric_only=True))
print(f"✅ Đã xử lý NaN sau reset")

# RFE selection với k=15 features
# Method này tự động chọn model phù hợp (LogisticRegression cho classification, LinearRegression cho regression)
feature_selector.rfe_selection(k=15, show_report=True)

### 🔄 **Đã reset về dữ liệu gốc!**

✅ Đã xử lý NaN sau reset

## 🔬 RFE Feature Selection (Top 15)

**🧩 RFE Selected Features (Top 15)**

### ✅ RFE đã chọn **15** features

,OverallQual,ExterQual,BsmtQual,BsmtFullBath,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageArea,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Pave,LotShape_IR2,LotShape_IR3,SalePrice
0,7.0,2.0,2.0,1.0,1.0,8.0,0.0,0.351000,0.0,0.0,1.0,0.0,1.0,0.0,0.0,208500
1,6.0,3.0,2.0,0.0,1.0,6.0,1.0,-0.060731,0.0,0.0,1.0,0.0,1.0,0.0,0.0,181500
2,7.0,2.0,2.0,1.0,1.0,6.0,1.0,0.631726,0.0,0.0,1.0,0.0,1.0,0.0,0.0,223500
3,7.0,3.0,3.0,1.0,1.0,7.0,1.0,0.790804,0.0,0.0,1.0,0.0,1.0,0.0,0.0,140000
4,8.0,2.0,2.0,1.0,1.0,9.0,1.0,1.698485,0.0,0.0,1.0,0.0,1.0,0.0,0.0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,6.0,3.0,2.0,0.0,1.0,7.0,1.0,-0.060731,0.0,0.0,1.0,0.0,1.0,0.0,0.0,175000
1456,6.0,3.0,2.0,1.0,1.0,7.0,2.0,0.126420,0.0,0.0,1.0,0.0,1.0,0.0,0.0,210000
1457,7.0,0.0,3.0,0.0,1.0,9.0,2.0,-1.033914,0.0,0.0,1.0,0.0,1.0,0.0,0.0,266500
1458,5.0,3.0,3.0,1.0,1.0,5.0,0.0,-1.090059,0.0,0.0,1.0,0.0,1.0,0.0,0.0,142125
1459,5.0,2.0,3.0,1.0,1.0,6.0,0.0,-0.921624,0.0,0.0,1.0,0.0,1.0,0.0,0.0,147500

## 📉 Demo 3.3: PCA (Principal Component Analysis)

Giảm chiều dữ liệu bằng PCA

In [268]:
# Reload module để áp dụng fix PCA
import importlib
from preprocess.feature import feature
importlib.reload(feature)
from preprocess.feature.feature import Feature

# Reset và reinitialize với data clean
feature_selector = Feature(df_with_target_clean, target_col='SalePrice', task='regression')
print(f"✅ Module reloaded và feature_selector reinitialize")

# PCA để giữ 95% variance
feature_selector.pca_extraction(n_components=0.95)

✅ Module reloaded và feature_selector reinitialize

## 🔬 PCA Feature Extraction (0.95 components)

**� PCA Variance Explained**

### ✅ PCA hoàn tất! (0.95 components, **95.86%** variance explained)

,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,SalePrice
0,225.599432,320.924248,-571.075884,328.359616,-113.135096,53.998699,208500
1,669.361676,-93.371248,37.114788,-176.783145,-101.296715,-110.824881,181500
2,-83.442071,221.111840,-407.950519,348.727231,-91.535673,18.840281,223500
3,-321.943574,168.893345,-317.506906,184.789146,15.586561,-113.487740,140000
4,45.499529,147.731721,-303.354621,695.813074,-64.778492,134.399563,250000
...,...,...,...,...,...,...,...
1455,-692.798746,28.665514,-93.277197,151.651475,-62.398365,-99.905863,175000
1456,579.047015,-476.687691,620.279024,131.619285,356.383740,-63.296276,210000
1457,-438.638644,2155.377285,1218.846473,675.199409,-3.814356,-184.987247,266500
1458,92.325819,124.012779,-270.620177,-595.107714,983.828505,170.759704,142125
1459,657.864273,-39.906147,-44.901412,-225.865634,232.607237,-28.855162,147500

## ⭐ Demo 3.4: Feature Importance

Xem importance của features với tree-based model

In [ ]:
# Reset và xem feature importance
feature_selector.reset()

# Xử lý NaN sau khi reset
feature_selector.df = feature_selector.df.fillna(feature_selector.df.median(numeric_only=True))
print(f"✅ Đã xử lý NaN sau reset")

# Feature importance với Random Forest
# Method này tự động chọn model phù hợp (RandomForestClassifier cho classification, RandomForestRegressor cho regression)
feature_selector.feature_importance(top_n=15, show_report=True)

### 🔄 **Đã reset về dữ liệu gốc!**

✅ Đã xử lý NaN sau reset

TypeError: Feature.feature_importance() got an unexpected keyword argument 'model'

## 🔗 Demo 3.5: Correlation Analysis

Phân tích correlation giữa các features

In [ ]:
# Phân tích correlation (không cần reset nếu chỉ analyze)
# Nhưng nếu muốn fresh start, uncomment dòng dưới:
# feature_selector.reset()
# feature_selector.df = feature_selector.df.fillna(feature_selector.df.median(numeric_only=True))

# Phân tích correlation
feature_selector.correlation_analysis(threshold=0.8)

## ➕ Demo 3.6: Add Custom Feature

Thêm feature mới được tính toán từ features hiện có

In [ ]:
# Thêm feature mới: TotalSF = TotalBsmtSF + 1stFlrSF + 2ndFlrSF
if 'TotalBsmtSF' in feature_selector.df.columns and '1stFlrSF' in feature_selector.df.columns:
    total_sf = feature_selector.df['TotalBsmtSF'] + feature_selector.df['1stFlrSF']
    if '2ndFlrSF' in feature_selector.df.columns:
        total_sf += feature_selector.df['2ndFlrSF']
    
    feature_selector.add_feature('TotalSF', total_sf)

## 📊 Demo 3.7: Xem History và Selected Features

Xem lịch sử và danh sách features đã chọn

In [ ]:
# Xem history
feature_selector.show_history()

In [ ]:
# Xem selected features
selected_features = feature_selector.get_selected_features()
print(f"\n✅ Selected {len(selected_features)} features:")
print(selected_features)

In [ ]:
# Lấy data với selected features
df_selected = feature_selector.get_data()
print(f"\n✅ Final data shape: {df_selected.shape}")
df_selected.head()

# 🧪 PHẦN 4: DEMO TRÊN TEST DATASET

Áp dụng tương tự các bước preprocessing cho test dataset

## 🔄 Demo 4.1: Clean Test Dataset

In [ ]:
# Clean test dataset
cleaner_test = Clean(df_test.copy())

# Phân tích missing
cleaner_test.analyze_missing()

In [ ]:
# Xử lý missing tương tự train
cleaner_test.handle_missing(columns=['LotFrontage'], strategy='mean')
cleaner_test.handle_missing(columns=['Alley', 'MasVnrType', 'FireplaceQu'], strategy='mode')
cleaner_test.drop_columns_with_missing(threshold=0.8)

# Get cleaned test data
df_test_cleaned = cleaner_test.get_cleaned_data()
print(f"✅ Test cleaned shape: {df_test_cleaned.shape}")

## 🎨 Demo 4.2: So Sánh Train vs Test sau Preprocessing

So sánh shape và một số thống kê

In [ ]:
# So sánh shape
print("=" * 60)
print("📊 COMPARISON SUMMARY")
print("=" * 60)
print(f"\n🔹 Original:")
print(f"   Train: {df_train.shape}")
print(f"   Test:  {df_test.shape}")

print(f"\n🔹 After Cleaning:")
print(f"   Train: {df_cleaned.shape}")
print(f"   Test:  {df_test_cleaned.shape}")

print(f"\n🔹 After Preprocessing:")
print(f"   Train: {df_preprocessed.shape}")

print(f"\n🔹 After Feature Selection:")
print(f"   Train: {df_selected.shape}")
print(f"   Selected Features: {len(selected_features)}")

print("\n" + "=" * 60)

## ✅ Kết Luận

Demo hoàn tất! Các module preprocessing đã được thử nghiệm thành công:

### 🧹 Clean Module:
- ✅ Phân tích missing values (`analyze_missing()`)
- ✅ Xử lý missing values (`handle_missing()`)
- ✅ Drop columns với missing cao (`drop_columns_with_missing()`)
- ✅ Remove duplicates (`remove_duplicates()`)
- ✅ Tracking history (`show_history()`)

### 🔄 Preprocess Module:
- ✅ Scale numerical features (`scale_features()`)
- ✅ Encode categorical features (`encode_features()`)
- ✅ Detect outliers (`detect_outliers()`)
- ✅ Handle outliers (`handle_outliers()`)
- ✅ Tracking history (`show_history()`)

### ⭐ Feature Module:
- ✅ Univariate selection (`univariate_selection()`)
- ✅ RFE selection (`rfe_selection()`)
- ✅ PCA extraction (`pca_extraction()`)
- ✅ Feature importance (`feature_importance()`)
- ✅ Correlation analysis (`correlation_analysis()`)
- ✅ Add custom features (`add_feature()`)
- ✅ Tracking history và utilities

**Tất cả modules đều có:**
- 🎨 Styled output với color coding
- 📊 Interactive Plotly visualizations
- 📝 History tracking
- 🔄 Compare utilities
- 💾 Get data methods

🎉 **Pipeline hoàn chỉnh: Raw Data → Clean → Preprocess → Feature Selection → Ready for ML!**